<?php

namespace Database\Seeders;

use Exception;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class WorldCountriesGeneralizedTableSeeder extends Seeder
{
    public function run()
    {
        ini_set('memory_limit', '4048M');

        try {
            DB::table('world_countries_generalized')->delete();
            $s3FilePath = 'world_countries/world_country_geometry.json';

            $fileContents = Storage::disk('s3')->get($s3FilePath);
            if (! $fileContents) {
                throw new Exception('Failed to get file contents from S3');
            }
            $geometry = json_decode($fileContents, true);
            $countries = [
                [
                    'OGR_FID' => 252,
                    'geometry' => '',
                    'country' => 'Afghanistan',
                    'iso' => 'AF',
                    'countryaff' => 'Afghanistan',
                    'aff_iso' => 'AF',
                ],
                [
                    'OGR_FID' => 253,
                    'geometry' => '',
                    'country' => 'Albania',
                    'iso' => 'AL',
                    'countryaff' => 'Albania',
                    'aff_iso' => 'AL',
                ],
                [
                    'OGR_FID' => 254,
                    'geometry' => '',
                    'country' => 'Algeria',
                    'iso' => 'DZ',
                    'countryaff' => 'Algeria',
                    'aff_iso' => 'DZ',
                ],
                [
                    'OGR_FID' => 255,
                    'geometry' => '',
                    'country' => 'American Samoa',
                    'iso' => 'AS',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 256,
                    'geometry' => '',
                    'country' => 'Andorra',
                    'iso' => 'AD',
                    'countryaff' => 'Andorra',
                    'aff_iso' => 'AD',
                ],
                [
                    'OGR_FID' => 257,
                    'geometry' => '',
                    'country' => 'Angola',
                    'iso' => 'AO',
                    'countryaff' => 'Angola',
                    'aff_iso' => 'AO',
                ],
                [
                    'OGR_FID' => 258,
                    'geometry' => '',
                    'country' => 'Anguilla',
                    'iso' => 'AI',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 259,
                    'geometry' => '',
                    'country' => 'Antarctica',
                    'iso' => 'AQ',
                    'countryaff' => null,
                    'aff_iso' => null,
                ],
                [
                    'OGR_FID' => 260,
                    'geometry' => '',
                    'country' => 'Antigua and Barbuda',
                    'iso' => 'AG',
                    'countryaff' => 'Antigua and Barbuda',
                    'aff_iso' => 'AG',
                ],
                [
                    'OGR_FID' => 261,
                    'geometry' => '',
                    'country' => 'Argentina',
                    'iso' => 'AR',
                    'countryaff' => 'Argentina',
                    'aff_iso' => 'AR',
                ],
                [
                    'OGR_FID' => 262,
                    'geometry' => '',                                                                                                                                                            'country' => 'Armenia',
                    'iso' => 'AM',
                    'countryaff' => 'Armenia',
                    'aff_iso' => 'AM',
                ],
                [
                    'OGR_FID' => 263,
                    'geometry' => '',
                    'country' => 'Aruba',
                    'iso' => 'AW',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 264,
                    'geometry' => '',
                    'country' => 'Australia',
                    'iso' => 'AU',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 265,
                    'geometry' => '',
                    'country' => 'Austria',
                    'iso' => 'AT',
                    'countryaff' => 'Austria',
                    'aff_iso' => 'AT',
                ],
                [
                    'OGR_FID' => 266,
                    'geometry' => '',
                    'country' => 'Azerbaijan',
                    'iso' => 'AZ',
                    'countryaff' => 'Azerbaijan',
                    'aff_iso' => 'AZ',
                ],
                [
                    'OGR_FID' => 267,
                    'geometry' => '',
                    'country' => 'Azores',
                    'iso' => '',
                    'countryaff' => 'Portugal',
                    'aff_iso' => '',
                ],
                [
                    'OGR_FID' => 268,
                    'geometry' => '',
                    'country' => 'Bahamas',
                    'iso' => 'BS',
                    'countryaff' => 'Bahamas',
                    'aff_iso' => 'BS',
                ],
                [
                    'OGR_FID' => 269,
                    'geometry' => '',
                    'country' => 'Bahrain',
                    'iso' => 'BH',
                    'countryaff' => 'Bahrain',
                    'aff_iso' => 'BH',
                ],
                [
                    'OGR_FID' => 270,
                    'geometry' => '',
                    'country' => 'Bangladesh',
                    'iso' => 'BD',
                    'countryaff' => 'Bangladesh',
                    'aff_iso' => 'BD',
                ],
                [
                    'OGR_FID' => 271,
                    'geometry' => '',
                    'country' => 'Barbados',
                    'iso' => 'BB',
                    'countryaff' => 'Barbados',
                    'aff_iso' => 'BB',
                ],
                [
                    'OGR_FID' => 272,
                    'geometry' => '',
                    'country' => 'Belarus',
                    'iso' => 'BY',
                    'countryaff' => 'Belarus',
                    'aff_iso' => 'BY',
                ],
                [
                    'OGR_FID' => 273,
                    'geometry' => '',
                    'country' => 'Belgium',
                    'iso' => 'BE',
                    'countryaff' => 'Belgium',
                    'aff_iso' => 'BE',
                ],
                [
                    'OGR_FID' => 274,
                    'geometry' => '',
                    'country' => 'Belize',
                    'iso' => 'BZ',
                    'countryaff' => 'Belize',
                    'aff_iso' => 'BZ',
                ],
                [
                    'OGR_FID' => 275,
                    'geometry' => '',
                    'country' => 'Benin',
                    'iso' => 'BJ',
                    'countryaff' => 'Benin',
                    'aff_iso' => 'BJ',
                ],
                [
                    'OGR_FID' => 276,
                    'geometry' => '',
                    'country' => 'Bermuda',
                    'iso' => 'BM',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 277,
                    'geometry' => '',
                    'country' => 'Bhutan',
                    'iso' => 'BT',
                    'countryaff' => 'Bhutan',
                    'aff_iso' => 'BT',
                ],
                [
                    'OGR_FID' => 278,
                    'geometry' => '',
                    'country' => 'Bolivia',
                    'iso' => 'BO',
                    'countryaff' => 'Bolivia, Plurinational State of',
                    'aff_iso' => 'BO',
                ],
                [
                    'OGR_FID' => 279,
                    'geometry' => '',
                    'country' => 'Bonaire',
                    'iso' => 'BQ',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 280,
                    'geometry' => '',
                    'country' => 'Bosnia and Herzegovina',
                    'iso' => 'BA',
                    'countryaff' => 'Bosnia and Herzegovina',
                    'aff_iso' => 'BA',
                ],
                [
                    'OGR_FID' => 281,
                    'geometry' => '',
                    'country' => 'Botswana',
                    'iso' => 'BW',
                    'countryaff' => 'Botswana',
                    'aff_iso' => 'BW',
                ],
                [
                    'OGR_FID' => 282,
                    'geometry' => '',
                    'country' => 'Bouvet Island',
                    'iso' => 'BV',
                    'countryaff' => 'Norway',
                    'aff_iso' => 'NO',
                ],
                [
                    'OGR_FID' => 283,
                    'geometry' => '',
                    'country' => 'Brazil',
                    'iso' => 'BR',
                    'countryaff' => 'Brazil',
                    'aff_iso' => 'BR',
                ],
                [
                    'OGR_FID' => 284,
                    'geometry' => '',
                    'country' => 'British Indian Ocean Territory',
                    'iso' => 'IO',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 285,
                    'geometry' => '',
                    'country' => 'British Virgin Islands',
                    'iso' => 'VG',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 286,
                    'geometry' => '',
                    'country' => 'Brunei Darussalam',
                    'iso' => 'BN',
                    'countryaff' => 'Brunei Darussalam',
                    'aff_iso' => 'BN',
                ],
                [
                    'OGR_FID' => 287,
                    'geometry' => '',
                    'country' => 'Bulgaria',
                    'iso' => 'BG',
                    'countryaff' => 'Bulgaria',
                    'aff_iso' => 'BG',
                ],
                [
                    'OGR_FID' => 288,
                    'geometry' => '',
                    'country' => 'Burkina Faso',
                    'iso' => 'BF',
                    'countryaff' => 'Burkina Faso',
                    'aff_iso' => 'BF',
                ],
                [
                    'OGR_FID' => 289,
                    'geometry' => '',
                    'country' => 'Burundi',
                    'iso' => 'BI',
                    'countryaff' => 'Burundi',
                    'aff_iso' => 'BI',
                ],
                [
                    'OGR_FID' => 290,
                    'geometry' => '',
                    'country' => 'Cabo Verde',
                    'iso' => 'CV',
                    'countryaff' => 'Cabo Verde',
                    'aff_iso' => 'CV',
                ],
                [
                    'OGR_FID' => 291,
                    'geometry' => '',
                    'country' => 'Cambodia',
                    'iso' => 'KH',
                    'countryaff' => 'Cambodia',
                    'aff_iso' => 'KH',
                ],
                [
                    'OGR_FID' => 292,
                    'geometry' => '',
                    'country' => 'Cameroon',
                    'iso' => 'CM',
                    'countryaff' => 'Cameroon',
                    'aff_iso' => 'CM',
                ],
                [
                    'OGR_FID' => 293,
                    'geometry' => '',
                    'country' => 'Canada',
                    'iso' => 'CA',
                    'countryaff' => 'Canada',
                    'aff_iso' => 'CA',
                ],
                [
                    'OGR_FID' => 294,
                    'geometry' => '',
                    'country' => 'Canarias',
                    'iso' => '',
                    'countryaff' => 'Spain',
                    'aff_iso' => '',
                ],
                [
                    'OGR_FID' => 295,
                    'geometry' => '',
                    'country' => 'Cayman Islands',
                    'iso' => 'KY',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 296,
                    'geometry' => '',
                    'country' => 'Central African Republic',
                    'iso' => 'CF',
                    'countryaff' => 'Central African Republic',
                    'aff_iso' => 'CF',
                ],
                [
                    'OGR_FID' => 297,
                    'geometry' => '',
                    'country' => 'Chad',
                    'iso' => 'TD',
                    'countryaff' => 'Chad',
                    'aff_iso' => 'TD',
                ],
                [
                    'OGR_FID' => 298,
                    'geometry' => '',
                    'country' => 'Chile',
                    'iso' => 'CL',
                    'countryaff' => 'Chile',
                    'aff_iso' => 'CL',
                ],
                [
                    'OGR_FID' => 299,
                    'geometry' => '',
                    'country' => 'China',
                    'iso' => 'CN',
                    'countryaff' => 'China',
                    'aff_iso' => 'CN',
                ],
                [
                    'OGR_FID' => 300,
                    'geometry' => '',
                    'country' => 'Christmas Island',
                    'iso' => 'CX',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 301,
                    'geometry' => '',
                    'country' => 'Cocos Islands',
                    'iso' => 'CC',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 302,
                    'geometry' => '',
                    'country' => 'Colombia',
                    'iso' => 'CO',
                    'countryaff' => 'Colombia',
                    'aff_iso' => 'CO',
                ],
                [
                    'OGR_FID' => 303,
                    'geometry' => '',
                    'country' => 'Comoros',
                    'iso' => 'KM',
                    'countryaff' => 'Comoros',
                    'aff_iso' => 'KM',
                ],
                [
                    'OGR_FID' => 304,
                    'geometry' => '',
                    'country' => 'Congo',
                    'iso' => 'CG',
                    'countryaff' => 'Congo',
                    'aff_iso' => 'CG',
                ],
                [
                    'OGR_FID' => 305,
                    'geometry' => '',
                    'country' => 'Congo DRC',
                    'iso' => 'CD',
                    'countryaff' => 'Congo, The Democratic Republic of the',
                    'aff_iso' => 'CD',
                ],
                [
                    'OGR_FID' => 306,
                    'geometry' => '',
                    'country' => 'Cook Islands',
                    'iso' => 'CK',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 307,
                    'geometry' => '',
                    'country' => 'Costa Rica',
                    'iso' => 'CR',
                    'countryaff' => 'Costa Rica',
                    'aff_iso' => 'CR',
                ],
                [
                    'OGR_FID' => 308,
                    'geometry' => '',
                    'country' => 'Côte d\'Ivoire',
                    'iso' => 'CI',
                    'countryaff' => 'Côte d\'Ivoire',
                    'aff_iso' => 'CI',
                ],
                [
                    'OGR_FID' => 309,
                    'geometry' => '',
                    'country' => 'Croatia',
                    'iso' => 'HR',
                    'countryaff' => 'Croatia',
                    'aff_iso' => 'HR',
                ],
                [
                    'OGR_FID' => 310,
                    'geometry' => '',
                    'country' => 'Cuba',
                    'iso' => 'CU',
                    'countryaff' => 'Cuba',
                    'aff_iso' => 'CU',
                ],
                [
                    'OGR_FID' => 311,
                    'geometry' => '',
                    'country' => 'Curacao',
                    'iso' => 'CW',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 312,
                    'geometry' => '',
                    'country' => 'Cyprus',
                    'iso' => 'CY',
                    'countryaff' => 'Cyprus',
                    'aff_iso' => 'CY',
                ],
                [
                    'OGR_FID' => 313,
                    'geometry' => '',
                    'country' => 'Czech Republic',
                    'iso' => 'CZ',
                    'countryaff' => 'Czechia',
                    'aff_iso' => 'CZ',
                ],
                [
                    'OGR_FID' => 314,
                    'geometry' => '',
                    'country' => 'Denmark',
                    'iso' => 'DK',
                    'countryaff' => 'Denmark',
                    'aff_iso' => 'DK',
                ],
                [
                    'OGR_FID' => 315,
                    'geometry' => '',
                    'country' => 'Djibouti',
                    'iso' => 'DJ',
                    'countryaff' => 'Djibouti',
                    'aff_iso' => 'DJ',
                ],
                [
                    'OGR_FID' => 316,
                    'geometry' => '',
                    'country' => 'Dominica',
                    'iso' => 'DM',
                    'countryaff' => 'Dominica',
                    'aff_iso' => 'DM',
                ],
                [
                    'OGR_FID' => 317,
                    'geometry' => '',
                    'country' => 'Dominican Republic',
                    'iso' => 'DO',
                    'countryaff' => 'Dominican Republic',
                    'aff_iso' => 'DO',
                ],
                [
                    'OGR_FID' => 318,
                    'geometry' => '',
                    'country' => 'Ecuador',
                    'iso' => 'EC',
                    'countryaff' => 'Ecuador',
                    'aff_iso' => 'EC',
                ],
                [
                    'OGR_FID' => 319,
                    'geometry' => '',
                    'country' => 'Egypt',
                    'iso' => 'EG',
                    'countryaff' => 'Egypt',
                    'aff_iso' => 'EG',
                ],
                [
                    'OGR_FID' => 320,
                    'geometry' => '',
                    'country' => 'El Salvador',
                    'iso' => 'SV',
                    'countryaff' => 'El Salvador',
                    'aff_iso' => 'SV',
                ],
                [
                    'OGR_FID' => 321,
                    'geometry' => '',
                    'country' => 'Equatorial Guinea',
                    'iso' => 'GQ',
                    'countryaff' => 'Equatorial Guinea',
                    'aff_iso' => 'GQ',
                ],
                [
                    'OGR_FID' => 322,
                    'geometry' => '',
                    'country' => 'Eritrea',
                    'iso' => 'ER',
                    'countryaff' => 'Eritrea',
                    'aff_iso' => 'ER',
                ],
                [
                    'OGR_FID' => 323,
                    'geometry' => '',
                    'country' => 'Estonia',
                    'iso' => 'EE',
                    'countryaff' => 'Estonia',
                    'aff_iso' => 'EE',
                ],
                [
                    'OGR_FID' => 324,
                    'geometry' => '',
                    'country' => 'Eswatini',
                    'iso' => 'SZ',
                    'countryaff' => 'Eswatini',
                    'aff_iso' => 'SZ',
                ],
                [
                    'OGR_FID' => 325,
                    'geometry' => '',
                    'country' => 'Ethiopia',
                    'iso' => 'ET',
                    'countryaff' => 'Ethiopia',
                    'aff_iso' => 'ET',
                ],
                [
                    'OGR_FID' => 326,
                    'geometry' => '',
                    'country' => 'Falkland Islands',
                    'iso' => 'FK',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 327,
                    'geometry' => '',
                    'country' => 'Faroe Islands',
                    'iso' => 'FO',
                    'countryaff' => 'Denmark',
                    'aff_iso' => 'DK',
                ],
                [
                    'OGR_FID' => 328,
                    'geometry' => '',
                    'country' => 'Fiji',
                    'iso' => 'FJ',
                    'countryaff' => 'Fiji',
                    'aff_iso' => 'FJ',
                ],
                [
                    'OGR_FID' => 329,
                    'geometry' => '',
                    'country' => 'Finland',
                    'iso' => 'FI',
                    'countryaff' => 'Finland',
                    'aff_iso' => 'FI',
                ],
                [
                    'OGR_FID' => 330,
                    'geometry' => '',
                    'country' => 'France',
                    'iso' => 'FR',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 331,
                    'geometry' => '',
                    'country' => 'French Guiana',
                    'iso' => 'GF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 332,
                    'geometry' => '',
                    'country' => 'French Polynesia',
                    'iso' => 'PF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 333,
                    'geometry' => '',
                    'country' => 'French Southern Territories',
                    'iso' => 'TF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 334,
                    'geometry' => '',
                    'country' => 'Gabon',
                    'iso' => 'GA',
                    'countryaff' => 'Gabon',
                    'aff_iso' => 'GA',
                ],
                [
                    'OGR_FID' => 335,
                    'geometry' => '',
                    'country' => 'Gambia',
                    'iso' => 'GM',
                    'countryaff' => 'Gambia',
                    'aff_iso' => 'GM',
                ],
                [
                    'OGR_FID' => 336,
                    'geometry' => '',
                    'country' => 'Georgia',
                    'iso' => 'GE',
                    'countryaff' => 'Georgia',
                    'aff_iso' => 'GE',
                ],
                [
                    'OGR_FID' => 337,
                    'geometry' => '',
                    'country' => 'Germany',
                    'iso' => 'DE',
                    'countryaff' => 'Germany',
                    'aff_iso' => 'DE',
                ],
                [
                    'OGR_FID' => 338,
                    'geometry' => '',
                    'country' => 'Ghana',
                    'iso' => 'GH',
                    'countryaff' => 'Ghana',
                    'aff_iso' => 'GH',
                ],
                [
                    'OGR_FID' => 339,
                    'geometry' => '',
                    'country' => 'Gibraltar',
                    'iso' => 'GI',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 340,
                    'geometry' => '',
                    'country' => 'Glorioso Islands',
                    'iso' => 'TF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 341,
                    'geometry' => '',
                    'country' => 'Greece',
                    'iso' => 'GR',
                    'countryaff' => 'Greece',
                    'aff_iso' => 'GR',
                ],
                [
                    'OGR_FID' => 342,
                    'geometry' => '',
                    'country' => 'Greenland',
                    'iso' => 'GL',
                    'countryaff' => 'Denmark',
                    'aff_iso' => 'DK',
                ],
                [
                    'OGR_FID' => 343,
                    'geometry' => '',
                    'country' => 'Grenada',
                    'iso' => 'GD',
                    'countryaff' => 'Grenada',
                    'aff_iso' => 'GD',
                ],
                [
                    'OGR_FID' => 344,
                    'geometry' => '',
                    'country' => 'Guadeloupe',
                    'iso' => 'GP',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 345,
                    'geometry' => '',
                    'country' => 'Guam',
                    'iso' => 'GU',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 346,
                    'geometry' => '',
                    'country' => 'Guatemala',
                    'iso' => 'GT',
                    'countryaff' => 'Guatemala',
                    'aff_iso' => 'GT',
                ],
                [
                    'OGR_FID' => 347,
                    'geometry' => '',
                    'country' => 'Guernsey',
                    'iso' => 'GG',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 348,
                    'geometry' => '',
                    'country' => 'Guinea',
                    'iso' => 'GN',
                    'countryaff' => 'Guinea',
                    'aff_iso' => 'GN',
                ],
                [
                    'OGR_FID' => 349,
                    'geometry' => '',
                    'country' => 'Guinea-Bissau',
                    'iso' => 'GW',
                    'countryaff' => 'Guinea-Bissau',
                    'aff_iso' => 'GW',
                ],
                [
                    'OGR_FID' => 350,
                    'geometry' => '',
                    'country' => 'Guyana',
                    'iso' => 'GY',
                    'countryaff' => 'Guyana',
                    'aff_iso' => 'GY',
                ],
                [
                    'OGR_FID' => 351,
                    'geometry' => '',
                    'country' => 'Haiti',
                    'iso' => 'HT',
                    'countryaff' => 'Haiti',
                    'aff_iso' => 'HT',
                ],
                [
                    'OGR_FID' => 352,
                    'geometry' => '',
                    'country' => 'Heard Island and McDonald Islands',
                    'iso' => 'HM',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 353,
                    'geometry' => '',
                    'country' => 'Honduras',
                    'iso' => 'HN',
                    'countryaff' => 'Honduras',
                    'aff_iso' => 'HN',
                ],
                [
                    'OGR_FID' => 354,
                    'geometry' => '',
                    'country' => 'Hungary',
                    'iso' => 'HU',
                    'countryaff' => 'Hungary',
                    'aff_iso' => 'HU',
                ],
                [
                    'OGR_FID' => 355,
                    'geometry' => '',
                    'country' => 'Iceland',
                    'iso' => 'IS',
                    'countryaff' => 'Iceland',
                    'aff_iso' => 'IS',
                ],
                [
                    'OGR_FID' => 356,
                    'geometry' => '',
                    'country' => 'India',
                    'iso' => 'IN',
                    'countryaff' => 'India',
                    'aff_iso' => 'IN',
                ],
                [
                    'OGR_FID' => 357,
                    'geometry' => '',
                    'country' => 'Indonesia',
                    'iso' => 'ID',
                    'countryaff' => 'Indonesia',
                    'aff_iso' => 'ID',
                ],
                [
                    'OGR_FID' => 358,
                    'geometry' => '',
                    'country' => 'Iran',
                    'iso' => 'IR',
                    'countryaff' => 'Iran, Islamic Republic of',
                    'aff_iso' => 'IR',
                ],
                [
                    'OGR_FID' => 359,
                    'geometry' => '',
                    'country' => 'Iraq',
                    'iso' => 'IQ',
                    'countryaff' => 'Iraq',
                    'aff_iso' => 'IQ',
                ],
                [
                    'OGR_FID' => 360,
                    'geometry' => '',
                    'country' => 'Ireland',
                    'iso' => 'IE',
                    'countryaff' => 'Ireland',
                    'aff_iso' => 'IE',
                ],
                [
                    'OGR_FID' => 361,
                    'geometry' => '',
                    'country' => 'Isle of Man',
                    'iso' => 'IM',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 362,
                    'geometry' => '',
                    'country' => 'Israel',
                    'iso' => 'IL',
                    'countryaff' => 'Israel',
                    'aff_iso' => 'IL',
                ],
                [
                    'OGR_FID' => 363,
                    'geometry' => '',
                    'country' => 'Italy',
                    'iso' => 'IT',
                    'countryaff' => 'Italy',
                    'aff_iso' => 'IT',
                ],
                [
                    'OGR_FID' => 364,
                    'geometry' => '',
                    'country' => 'Jamaica',
                    'iso' => 'JM',
                    'countryaff' => 'Jamaica',
                    'aff_iso' => 'JM',
                ],
                [
                    'OGR_FID' => 365,
                    'geometry' => '',
                    'country' => 'Japan',
                    'iso' => 'JP',
                    'countryaff' => 'Japan',
                    'aff_iso' => 'JP',
                ],
                [
                    'OGR_FID' => 366,
                    'geometry' => '',
                    'country' => 'Jersey',
                    'iso' => 'JE',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 367,
                    'geometry' => '',
                    'country' => 'Jordan',
                    'iso' => 'JO',
                    'countryaff' => 'Jordan',
                    'aff_iso' => 'JO',
                ],
                [
                    'OGR_FID' => 368,
                    'geometry' => '',
                    'country' => 'Juan De Nova Island',
                    'iso' => 'TF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 369,
                    'geometry' => '',
                    'country' => 'Kazakhstan',
                    'iso' => 'KZ',
                    'countryaff' => 'Kazakhstan',
                    'aff_iso' => 'KZ',
                ],
                [
                    'OGR_FID' => 370,
                    'geometry' => '',
                    'country' => 'Kenya',
                    'iso' => 'KE',
                    'countryaff' => 'Kenya',
                    'aff_iso' => 'KE',
                ],
                [
                    'OGR_FID' => 371,
                    'geometry' => '',
                    'country' => 'Kiribati',

                    'iso' => 'KI',
                    'countryaff' => 'Kiribati',
                    'aff_iso' => 'KI',
                ],
                [
                    'OGR_FID' => 372,
                    'geometry' => '',
                    'country' => 'Kuwait',
                    'iso' => 'KW',
                    'countryaff' => 'Kuwait',
                    'aff_iso' => 'KW',
                ],
                [
                    'OGR_FID' => 373,
                    'geometry' => '',
                    'country' => 'Kyrgyzstan',
                    'iso' => 'KG',
                    'countryaff' => 'Kyrgyzstan',
                    'aff_iso' => 'KG',
                ],
                [
                    'OGR_FID' => 374,
                    'geometry' => '',
                    'country' => 'Laos',
                    'iso' => 'LA',
                    'countryaff' => 'Lao People\'s Democratic Republic',
                    'aff_iso' => 'LA',
                ],
                [
                    'OGR_FID' => 375,
                    'geometry' => '',
                    'country' => 'Latvia',
                    'iso' => 'LV',
                    'countryaff' => 'Latvia',
                    'aff_iso' => 'LV',
                ],
                [
                    'OGR_FID' => 376,
                    'geometry' => '',
                    'country' => 'Lebanon',
                    'iso' => 'LB',
                    'countryaff' => 'Lebanon',
                    'aff_iso' => 'LB',
                ],
                [
                    'OGR_FID' => 377,
                    'geometry' => '',
                    'country' => 'Lesotho',
                    'iso' => 'LS',
                    'countryaff' => 'Lesotho',
                    'aff_iso' => 'LS',
                ],
                [
                    'OGR_FID' => 378,
                    'geometry' => '',
                    'country' => 'Liberia',
                    'iso' => 'LR',
                    'countryaff' => 'Liberia',
                    'aff_iso' => 'LR',
                ],
                [
                    'OGR_FID' => 379,
                    'geometry' => '',
                    'country' => 'Libya',
                    'iso' => 'LY',
                    'countryaff' => 'Libya',
                    'aff_iso' => 'LY',
                ],
                [
                    'OGR_FID' => 380,
                    'geometry' => '',
                    'country' => 'Liechtenstein',
                    'iso' => 'LI',
                    'countryaff' => 'Liechtenstein',
                    'aff_iso' => 'LI',
                ],
                [
                    'OGR_FID' => 381,
                    'geometry' => '',
                    'country' => 'Lithuania',
                    'iso' => 'LT',
                    'countryaff' => 'Lithuania',
                    'aff_iso' => 'LT',
                ],
                [
                    'OGR_FID' => 382,
                    'geometry' => '',
                    'country' => 'Luxembourg',
                    'iso' => 'LU',
                    'countryaff' => 'Luxembourg',
                    'aff_iso' => 'LU',
                ],
                [
                    'OGR_FID' => 383,
                    'geometry' => '',
                    'country' => 'Madagascar',
                    'iso' => 'MG',
                    'countryaff' => 'Madagascar',
                    'aff_iso' => 'MG',
                ],
                [
                    'OGR_FID' => 384,
                    'geometry' => '',
                    'country' => 'Madeira',
                    'iso' => '',
                    'countryaff' => 'Portugal',
                    'aff_iso' => '',
                ],
                [
                    'OGR_FID' => 385,
                    'geometry' => '',
                    'country' => 'Malawi',
                    'iso' => 'MW',
                    'countryaff' => 'Malawi',
                    'aff_iso' => 'MW',
                ],
                [
                    'OGR_FID' => 386,
                    'geometry' => '',
                    'country' => 'Malaysia',
                    'iso' => 'MY',
                    'countryaff' => 'Malaysia',
                    'aff_iso' => 'MY',
                ],
                [
                    'OGR_FID' => 387,
                    'geometry' => '',
                    'country' => 'Maldives',
                    'iso' => 'MV',
                    'countryaff' => 'Maldives',
                    'aff_iso' => 'MV',
                ],
                [
                    'OGR_FID' => 388,
                    'geometry' => '',
                    'country' => 'Mali',
                    'iso' => 'ML',
                    'countryaff' => 'Mali',
                    'aff_iso' => 'ML',
                ],
                [
                    'OGR_FID' => 389,
                    'geometry' => '',
                    'country' => 'Malta',
                    'iso' => 'MT',
                    'countryaff' => 'Malta',
                    'aff_iso' => 'MT',
                ],
                [
                    'OGR_FID' => 390,
                    'geometry' => '',
                    'country' => 'Marshall Islands',
                    'iso' => 'MH',
                    'countryaff' => 'Marshall Islands',
                    'aff_iso' => 'MH',
                ],
                [
                    'OGR_FID' => 391,
                    'geometry' => '',
                    'country' => 'Martinique',
                    'iso' => 'MQ',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 392,
                    'geometry' => '',
                    'country' => 'Mauritania',
                    'iso' => 'MR',
                    'countryaff' => 'Mauritania',
                    'aff_iso' => 'MR',
                ],
                [
                    'OGR_FID' => 393,
                    'geometry' => '',
                    'country' => 'Mauritius',
                    'iso' => 'MU',
                    'countryaff' => 'Mauritius',
                    'aff_iso' => 'MU',
                ],
                [
                    'OGR_FID' => 394,
                    'geometry' => '',
                    'country' => 'Mayotte',
                    'iso' => 'YT',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 395,
                    'geometry' => '',
                    'country' => 'Mexico',
                    'iso' => 'MX',
                    'countryaff' => 'Mexico',
                    'aff_iso' => 'MX',
                ],
                [
                    'OGR_FID' => 396,
                    'geometry' => '',
                    'country' => 'Micronesia',
                    'iso' => 'FM',
                    'countryaff' => 'Micronesia, Federated States of',
                    'aff_iso' => 'FM',
                ],
                [
                    'OGR_FID' => 397,
                    'geometry' => '',
                    'country' => 'Moldova',
                    'iso' => 'MD',
                    'countryaff' => 'Moldova, Republic of',
                    'aff_iso' => 'MD',
                ],
                [
                    'OGR_FID' => 398,
                    'geometry' => '',
                    'country' => 'Monaco',
                    'iso' => 'MC',
                    'countryaff' => 'Monaco',
                    'aff_iso' => 'MC',
                ],
                [
                    'OGR_FID' => 399,
                    'geometry' => '',
                    'country' => 'Mongolia',
                    'iso' => 'MN',
                    'countryaff' => 'Mongolia',
                    'aff_iso' => 'MN',
                ],
                [
                    'OGR_FID' => 400,
                    'geometry' => '',
                    'country' => 'Montenegro',
                    'iso' => 'ME',
                    'countryaff' => 'Montenegro',
                    'aff_iso' => 'ME',
                ],
                [
                    'OGR_FID' => 401,
                    'geometry' => '',
                    'country' => 'Montserrat',
                    'iso' => 'MS',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 402,
                    'geometry' => '',
                    'country' => 'Morocco',
                    'iso' => 'MA',
                    'countryaff' => 'Morocco',
                    'aff_iso' => 'MA',
                ],
                [
                    'OGR_FID' => 403,
                    'geometry' => '',
                    'country' => 'Mozambique',
                    'iso' => 'MZ',
                    'countryaff' => 'Mozambique',
                    'aff_iso' => 'MZ',
                ],
                [
                    'OGR_FID' => 404,
                    'geometry' => '',
                    'country' => 'Myanmar',
                    'iso' => 'MM',
                    'countryaff' => 'Myanmar',
                    'aff_iso' => 'MM',
                ],
                [
                    'OGR_FID' => 405,
                    'geometry' => '',
                    'country' => 'Namibia',
                    'iso' => 'NA',
                    'countryaff' => 'Namibia',
                    'aff_iso' => 'NA',
                ],
                [
                    'OGR_FID' => 406,
                    'geometry' => '',
                    'country' => 'Nauru',
                    'iso' => 'NR',
                    'countryaff' => 'Nauru',
                    'aff_iso' => 'NR',
                ],
                [
                    'OGR_FID' => 407,
                    'geometry' => '',
                    'country' => 'Nepal',
                    'iso' => 'NP',
                    'countryaff' => 'Nepal',
                    'aff_iso' => 'NP',
                ],
                [
                    'OGR_FID' => 408,
                    'geometry' => '',
                    'country' => 'Netherlands',
                    'iso' => 'NL',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 409,
                    'geometry' => '',
                    'country' => 'New Caledonia',
                    'iso' => 'NC',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 410,
                    'geometry' => '',
                    'country' => 'New Zealand',
                    'iso' => 'NZ',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 411,
                    'geometry' => '',
                    'country' => 'Nicaragua',
                    'iso' => 'NI',
                    'countryaff' => 'Nicaragua',
                    'aff_iso' => 'NI',
                ],
                [
                    'OGR_FID' => 412,
                    'geometry' => '',
                    'country' => 'Niger',
                    'iso' => 'NE',
                    'countryaff' => 'Niger',
                    'aff_iso' => 'NE',
                ],
                [
                    'OGR_FID' => 413,
                    'geometry' => '',
                    'country' => 'Nigeria',
                    'iso' => 'NG',
                    'countryaff' => 'Nigeria',
                    'aff_iso' => 'NG',
                ],
                [
                    'OGR_FID' => 414,
                    'geometry' => '',
                    'country' => 'Niue',
                    'iso' => 'NU',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 415,
                    'geometry' => '',
                    'country' => 'Norfolk Island',
                    'iso' => 'NF',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 416,
                    'geometry' => '',
                    'country' => 'North Korea',
                    'iso' => 'KP',
                    'countryaff' => 'Korea, Democratic People\'s Republic of',
                    'aff_iso' => 'KP',
                ],
                [
                    'OGR_FID' => 417,
                    'geometry' => '',
                    'country' => 'North Macedonia',
                    'iso' => 'MK',
                    'countryaff' => 'North Macedonia',
                    'aff_iso' => 'MK',
                ],
                [
                    'OGR_FID' => 418,
                    'geometry' => '',
                    'country' => 'Northern Mariana Islands',
                    'iso' => 'MP',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 419,
                    'geometry' => '',
                    'country' => 'Norway',
                    'iso' => 'NO',
                    'countryaff' => 'Norway',
                    'aff_iso' => 'NO',
                ],
                [
                    'OGR_FID' => 420,
                    'geometry' => '',
                    'country' => 'Oman',
                    'iso' => 'OM',
                    'countryaff' => 'Oman',
                    'aff_iso' => 'OM',
                ],
                [
                    'OGR_FID' => 421,
                    'geometry' => '',
                    'country' => 'Pakistan',
                    'iso' => 'PK',
                    'countryaff' => 'Pakistan',
                    'aff_iso' => 'PK',
                ],
                [
                    'OGR_FID' => 422,
                    'geometry' => '',
                    'country' => 'Palau',
                    'iso' => 'PW',
                    'countryaff' => 'Palau',
                    'aff_iso' => 'PW',
                ],
                [
                    'OGR_FID' => 423,
                    'geometry' => '',
                    'country' => 'Palestinian Territory',
                    'iso' => 'PS',
                    'countryaff' => 'Palestine, State of',
                    'aff_iso' => 'PS',
                ],
                [
                    'OGR_FID' => 424,
                    'geometry' => '',
                    'country' => 'Panama',
                    'iso' => 'PA',
                    'countryaff' => 'Panama',
                    'aff_iso' => 'PA',
                ],
                [
                    'OGR_FID' => 425,
                    'geometry' => '',
                    'country' => 'Papua New Guinea',
                    'iso' => 'PG',
                    'countryaff' => 'Papua New Guinea',
                    'aff_iso' => 'PG',
                ],
                [
                    'OGR_FID' => 426,
                    'geometry' => '',
                    'country' => 'Paraguay',
                    'iso' => 'PY',
                    'countryaff' => 'Paraguay',
                    'aff_iso' => 'PY',
                ],
                [
                    'OGR_FID' => 427,
                    'geometry' => '',
                    'country' => 'Peru',
                    'iso' => 'PE',
                    'countryaff' => 'Peru',
                    'aff_iso' => 'PE',
                ],
                [
                    'OGR_FID' => 428,
                    'geometry' => '',
                    'country' => 'Philippines',
                    'iso' => 'PH',
                    'countryaff' => 'Philippines',
                    'aff_iso' => 'PH',
                ],
                [
                    'OGR_FID' => 429,
                    'geometry' => '',
                    'country' => 'Pitcairn',
                    'iso' => 'PN',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 430,
                    'geometry' => '',
                    'country' => 'Poland',
                    'iso' => 'PL',
                    'countryaff' => 'Poland',
                    'aff_iso' => 'PL',
                ],
                [
                    'OGR_FID' => 431,
                    'geometry' => '',
                    'country' => 'Portugal',
                    'iso' => 'PT',
                    'countryaff' => 'Portugal',
                    'aff_iso' => 'PT',
                ],
                [
                    'OGR_FID' => 432,
                    'geometry' => '',
                    'country' => 'Puerto Rico',
                    'iso' => 'PR',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 433,
                    'geometry' => '',
                    'country' => 'Qatar',
                    'iso' => 'QA',
                    'countryaff' => 'Qatar',
                    'aff_iso' => 'QA',
                ],
                [
                    'OGR_FID' => 434,
                    'geometry' => '',
                    'country' => 'Réunion',
                    'iso' => 'RE',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 435,
                    'geometry' => '',
                    'country' => 'Romania',
                    'iso' => 'RO',
                    'countryaff' => 'Romania',
                    'aff_iso' => 'RO',
                ],
                [
                    'OGR_FID' => 436,
                    'geometry' => '',
                    'country' => 'Russian Federation',
                    'iso' => 'RU',
                    'countryaff' => 'Russian Federation',
                    'aff_iso' => 'RU',
                ],
                [
                    'OGR_FID' => 437,
                    'geometry' => '',
                    'country' => 'Rwanda',
                    'iso' => 'RW',
                    'countryaff' => 'Rwanda',
                    'aff_iso' => 'RW',
                ],
                [
                    'OGR_FID' => 438,
                    'geometry' => '',
                    'country' => 'Saba',
                    'iso' => 'BQ',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 439,
                    'geometry' => '',
                    'country' => 'Saint Barthelemy',
                    'iso' => 'BL',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 440,
                    'geometry' => '',
                    'country' => 'Saint Eustatius',
                    'iso' => 'BQ',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 441,
                    'geometry' => '',
                    'country' => 'Saint Helena',
                    'iso' => 'SH',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 442,
                    'geometry' => '',
                    'country' => 'Saint Kitts and Nevis',
                    'iso' => 'KN',
                    'countryaff' => 'Saint Kitts and Nevis',
                    'aff_iso' => 'KN',
                ],
                [
                    'OGR_FID' => 443,
                    'geometry' => '',
                    'country' => 'Saint Lucia',
                    'iso' => 'LC',
                    'countryaff' => 'Saint Lucia',
                    'aff_iso' => 'LC',
                ],
                [
                    'OGR_FID' => 444,
                    'geometry' => '',
                    'country' => 'Saint Martin',
                    'iso' => 'MF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 445,
                    'geometry' => '',
                    'country' => 'Saint Pierre and Miquelon',
                    'iso' => 'PM',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 446,
                    'geometry' => '',
                    'country' => 'Saint Vincent and the Grenadines',
                    'iso' => 'VC',
                    'countryaff' => 'Saint Vincent and the Grenadines',
                    'aff_iso' => 'VC',
                ],
                [
                    'OGR_FID' => 447,
                    'geometry' => '',
                    'country' => 'Samoa',
                    'iso' => 'WS',
                    'countryaff' => 'Samoa',
                    'aff_iso' => 'WS',
                ],
                [
                    'OGR_FID' => 448,
                    'geometry' => '',
                    'country' => 'San Marino',
                    'iso' => 'SM',
                    'countryaff' => 'San Marino',
                    'aff_iso' => 'SM',
                ],
                [
                    'OGR_FID' => 449,
                    'geometry' => '',
                    'country' => 'Sao Tome and Principe',
                    'iso' => 'ST',
                    'countryaff' => 'São Tomé and Príncipe',
                    'aff_iso' => 'ST',
                ],
                [
                    'OGR_FID' => 450,
                    'geometry' => '',
                    'country' => 'Saudi Arabia',
                    'iso' => 'SA',
                    'countryaff' => 'Saudi Arabia',
                    'aff_iso' => 'SA',
                ],
                [
                    'OGR_FID' => 451,
                    'geometry' => '',
                    'country' => 'Senegal',
                    'iso' => 'SN',
                    'countryaff' => 'Senegal',
                    'aff_iso' => 'SN',
                ],
                [
                    'OGR_FID' => 452,
                    'geometry' => '',
                    'country' => 'Serbia',
                    'iso' => 'RS',
                    'countryaff' => 'Serbia',
                    'aff_iso' => 'RS',
                ],
                [
                    'OGR_FID' => 453,
                    'geometry' => '',
                    'country' => 'Seychelles',
                    'iso' => 'SC',
                    'countryaff' => 'Seychelles',
                    'aff_iso' => 'SC',
                ],
                [
                    'OGR_FID' => 454,
                    'geometry' => '',
                    'country' => 'Sierra Leone',
                    'iso' => 'SL',
                    'countryaff' => 'Sierra Leone',
                    'aff_iso' => 'SL',
                ],
                [
                    'OGR_FID' => 455,
                    'geometry' => '',
                    'country' => 'Singapore',
                    'iso' => 'SG',
                    'countryaff' => 'Singapore',
                    'aff_iso' => 'SG',
                ],
                [
                    'OGR_FID' => 456,
                    'geometry' => '',
                    'country' => 'Sint Maarten',
                    'iso' => 'SX',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 457,
                    'geometry' => '',
                    'country' => 'Slovakia',
                    'iso' => 'SK',
                    'countryaff' => 'Slovakia',
                    'aff_iso' => 'SK',
                ],
                [
                    'OGR_FID' => 458,
                    'geometry' => '',
                    'country' => 'Slovenia',
                    'iso' => 'SI',
                    'countryaff' => 'Slovenia',
                    'aff_iso' => 'SI',
                ],
                [
                    'OGR_FID' => 459,
                    'geometry' => '',
                    'country' => 'Solomon Islands',
                    'iso' => 'SB',
                    'countryaff' => 'Solomon Islands',
                    'aff_iso' => 'SB',
                ],
                [
                    'OGR_FID' => 460,
                    'geometry' => '',
                    'country' => 'Somalia',
                    'iso' => 'SO',
                    'countryaff' => 'Somalia',
                    'aff_iso' => 'SO',
                ],
                [
                    'OGR_FID' => 461,
                    'geometry' => '',
                    'country' => 'South Africa',
                    'iso' => 'ZA',
                    'countryaff' => 'South Africa',
                    'aff_iso' => 'ZA',
                ],
                [
                    'OGR_FID' => 462,
                    'geometry' => '',
                    'country' => 'South Georgia and South Sandwich Islands',
                    'iso' => 'GS',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 463,
                    'geometry' => '',
                    'country' => 'South Korea',
                    'iso' => 'KR',
                    'countryaff' => 'Korea, Republic of',
                    'aff_iso' => 'KR',
                ],
                [
                    'OGR_FID' => 464,
                    'geometry' => '',
                    'country' => 'South Sudan',
                    'iso' => 'SS',
                    'countryaff' => 'South Sudan',
                    'aff_iso' => 'SS',
                ],
                [
                    'OGR_FID' => 465,
                    'geometry' => '',
                    'country' => 'Spain',
                    'iso' => 'ES',
                    'countryaff' => 'Spain',
                    'aff_iso' => 'ES',
                ],
                [
                    'OGR_FID' => 466,
                    'geometry' => '',
                    'country' => 'Sri Lanka',
                    'iso' => 'LK',
                    'countryaff' => 'Sri Lanka',
                    'aff_iso' => 'LK',
                ],
                [
                    'OGR_FID' => 467,
                    'geometry' => '',
                    'country' => 'Sudan',
                    'iso' => 'SD',
                    'countryaff' => 'Sudan',
                    'aff_iso' => 'SD',
                ],
                [
                    'OGR_FID' => 468,
                    'geometry' => '',
                    'country' => 'Suriname',
                    'iso' => 'SR',
                    'countryaff' => 'Suriname',
                    'aff_iso' => 'SR',
                ],
                [
                    'OGR_FID' => 469,
                    'geometry' => '',
                    'country' => 'Svalbard',
                    'iso' => 'SJ',
                    'countryaff' => 'Norway',
                    'aff_iso' => 'NO',
                ],
                [
                    'OGR_FID' => 470,
                    'geometry' => '',
                    'country' => 'Sweden',
                    'iso' => 'SE',
                    'countryaff' => 'Sweden',
                    'aff_iso' => 'SE',
                ],
                [
                    'OGR_FID' => 471,
                    'geometry' => '',
                    'country' => 'Switzerland',
                    'iso' => 'CH',
                    'countryaff' => 'Switzerland',
                    'aff_iso' => 'CH',
                ],
                [
                    'OGR_FID' => 472,
                    'geometry' => '',
                    'country' => 'Syria',
                    'iso' => 'SY',
                    'countryaff' => 'Syrian Arab Republic',
                    'aff_iso' => 'SY',
                ],
                [
                    'OGR_FID' => 473,
                    'geometry' => '',
                    'country' => 'Tajikistan',
                    'iso' => 'TJ',
                    'countryaff' => 'Tajikistan',
                    'aff_iso' => 'TJ',
                ],
                [
                    'OGR_FID' => 474,
                    'geometry' => '',
                    'country' => 'Tanzania',
                    'iso' => 'TZ',
                    'countryaff' => 'Tanzania, United Republic of',
                    'aff_iso' => 'TZ',
                ],
                [
                    'OGR_FID' => 475,
                    'geometry' => '',
                    'country' => 'Thailand',
                    'iso' => 'TH',
                    'countryaff' => 'Thailand',
                    'aff_iso' => 'TH',
                ],
                [
                    'OGR_FID' => 476,
                    'geometry' => '',
                    'country' => 'Timor-Leste',
                    'iso' => 'TL',
                    'countryaff' => 'Timor-Leste',
                    'aff_iso' => 'TL',
                ],
                [
                    'OGR_FID' => 477,
                    'geometry' => '',
                    'country' => 'Togo',
                    'iso' => 'TG',
                    'countryaff' => 'Togo',
                    'aff_iso' => 'TG',
                ],
                [
                    'OGR_FID' => 478,
                    'geometry' => '',
                    'country' => 'Tokelau',
                    'iso' => 'TK',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 479,
                    'geometry' => '',
                    'country' => 'Tonga',
                    'iso' => 'TO',
                    'countryaff' => 'Tonga',
                    'aff_iso' => 'TO',
                ],
                [
                    'OGR_FID' => 480,
                    'geometry' => '',
                    'country' => 'Trinidad and Tobago',
                    'iso' => 'TT',
                    'countryaff' => 'Trinidad and Tobago',
                    'aff_iso' => 'TT',
                ],
                [
                    'OGR_FID' => 481,
                    'geometry' => '',
                    'country' => 'Tunisia',
                    'iso' => 'TN',
                    'countryaff' => 'Tunisia',
                    'aff_iso' => 'TN',
                ],
                [
                    'OGR_FID' => 482,
                    'geometry' => '',
                    'country' => 'Turkiye',
                    'iso' => 'TR',
                    'countryaff' => 'Turkiye',
                    'aff_iso' => 'TR',
                ],
                [
                    'OGR_FID' => 483,
                    'geometry' => '',
                    'country' => 'Turkmenistan',
                    'iso' => 'TM',
                    'countryaff' => 'Turkmenistan',
                    'aff_iso' => 'TM',
                ],
                [
                    'OGR_FID' => 484,
                    'geometry' => '',
                    'country' => 'Turks and Caicos Islands',
                    'iso' => 'TC',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 485,
                    'geometry' => '',
                    'country' => 'Tuvalu',
                    'iso' => 'TV',
                    'countryaff' => 'Tuvalu',
                    'aff_iso' => 'TV',
                ],
                [
                    'OGR_FID' => 486,
                    'geometry' => '',
                    'country' => 'Uganda',
                    'iso' => 'UG',
                    'countryaff' => 'Uganda',
                    'aff_iso' => 'UG',
                ],
                [
                    'OGR_FID' => 487,
                    'geometry' => '',
                    'country' => 'Ukraine',
                    'iso' => 'UA',
                    'countryaff' => 'Ukraine',
                    'aff_iso' => 'UA',
                ],
                [
                    'OGR_FID' => 488,
                    'geometry' => '',
                    'country' => 'United Arab Emirates',
                    'iso' => 'AE',
                    'countryaff' => 'United Arab Emirates',
                    'aff_iso' => 'AE',
                ],
                [
                    'OGR_FID' => 489,
                    'geometry' => '',
                    'country' => 'United Kingdom',
                    'iso' => 'GB',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 490,
                    'geometry' => '',
                    'country' => 'United States',
                    'iso' => 'US',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 491,
                    'geometry' => '',
                    'country' => 'United States Minor Outlying Islands',
                    'iso' => 'UM',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 492,
                    'geometry' => '',
                    'country' => 'Uruguay',
                    'iso' => 'UY',
                    'countryaff' => 'Uruguay',
                    'aff_iso' => 'UY',
                ],
                [
                    'OGR_FID' => 493,
                    'geometry' => '',
                    'country' => 'US Virgin Islands',
                    'iso' => 'VI',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 494,
                    'geometry' => '',
                    'country' => 'Uzbekistan',
                    'iso' => 'UZ',
                    'countryaff' => 'Uzbekistan',
                    'aff_iso' => 'UZ',
                ],
                [
                    'OGR_FID' => 495,
                    'geometry' => '',
                    'country' => 'Vanuatu',
                    'iso' => 'VU',
                    'countryaff' => 'Vanuatu',
                    'aff_iso' => 'VU',
                ],
                [
                    'OGR_FID' => 496,
                    'geometry' => '',
                    'country' => 'Vatican City',
                    'iso' => 'VA',
                    'countryaff' => 'Holy See (Vatican City State)',
                    'aff_iso' => 'VA',
                ],
                [
                    'OGR_FID' => 497,
                    'geometry' => '',
                    'country' => 'Venezuela',
                    'iso' => 'VE',
                    'countryaff' => 'Venezuela, Bolivarian Republic of',
                    'aff_iso' => 'VE',
                ],
                [
                    'OGR_FID' => 498,
                    'geometry' => '',
                    'country' => 'Vietnam',
                    'iso' => 'VN',
                    'countryaff' => 'Viet Nam',
                    'aff_iso' => 'VN',
                ],
                [
                    'OGR_FID' => 499,
                    'geometry' => '',
                    'country' => 'Wallis and Futuna',
                    'iso' => 'WF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 500,
                    'geometry' => '',
                    'country' => 'Yemen',
                    'iso' => 'YE',
                    'countryaff' => 'Yemen',
                    'aff_iso' => 'YE',
                ],
                [
                    'OGR_FID' => 501,
                    'geometry' => '',
                    'country' => 'Zambia',
                    'iso' => 'ZM',
                    'countryaff' => 'Zambia',
                    'aff_iso' => 'ZM',
                ],
                [
                    'OGR_FID' => 502,
                    'geometry' => '',
                    'country' => 'Zimbabwe',
                    'iso' => 'ZW',
                    'countryaff' => 'Zimbabwe',
                    'aff_iso' => 'ZW',
                ],
            ];

            foreach ($countries as $country) {
                if (isset($geometry[$country['iso']])) {
                    $country['geometry'] = DB::raw('ST_GeomFromGeoJSON(' . json_encode($geometry[$country['iso']]) . ')');
                    DB::table('world_countries_generalized')->insert($country);
                }
            }
        } catch (Exception $e) {
            Log::error('Failed to retrieve file from S3: ' . $e->getMessage());
        }
    }
}
