<?php

namespace Database\Seeders;

use Exception;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class WorldCountriesGeneralizedTableSeeder extends Seeder
{

    public function run()
    {
        ini_set('memory_limit', '4048M');

        try {
            DB::table('world_countries_generalized')->delete();
            $s3FilePath = 'world_countries/world_country_geometry.json';

            $fileContents = Storage::disk('s3')->get($s3FilePath);
            if (! $fileContents) {
                throw new Exception('Failed to get file contents from S3');
            }
            $geometry = json_decode($fileContents, true);
            $countries = [
                [
                    'OGR_FID' => 252,
                    'geometry' => '',
                    'country' => 'Afghanistan',
                    'iso' => 'AFG',
                    'countryaff' => 'Afghanistan',
                    'aff_iso' => 'AF',
                ],
                [
                    'OGR_FID' => 253,
                    'geometry' => '',
                    'country' => 'Albania',
                    'iso' => 'ALB',
                    'countryaff' => 'Albania',
                    'aff_iso' => 'AL',
                ],
                [
                    'OGR_FID' => 254,
                    'geometry' => '',
                    'country' => 'Algeria',
                    'iso' => 'DZA',
                    'countryaff' => 'Algeria',
                    'aff_iso' => 'DZ',
                ],
                [
                    'OGR_FID' => 255,
                    'geometry' => '',
                    'country' => 'American Samoa',
                    'iso' => 'ASM',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 256,
                    'geometry' => '',
                    'country' => 'Andorra',
                    'iso' => 'AND',
                    'countryaff' => 'Andorra',
                    'aff_iso' => 'AD',
                ],
                [
                    'OGR_FID' => 257,
                    'geometry' => '',
                    'country' => 'Angola',
                    'iso' => 'AGO',
                    'countryaff' => 'Angola',
                    'aff_iso' => 'AO',
                ],
                [
                    'OGR_FID' => 258,
                    'geometry' => '',
                    'country' => 'Anguilla',
                    'iso' => 'AIA',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 259,
                    'geometry' => '',
                    'country' => 'Antarctica',
                    'iso' => 'ATA',
                    'countryaff' => null,
                    'aff_iso' => null,
                ],
                [
                    'OGR_FID' => 260,
                    'geometry' => '',
                    'country' => 'Antigua and Barbuda',
                    'iso' => 'ATG',
                    'countryaff' => 'Antigua and Barbuda',
                    'aff_iso' => 'AG',
                ],
                [
                    'OGR_FID' => 261,
                    'geometry' => '',
                    'country' => 'Argentina',
                    'iso' => 'ARG',
                    'countryaff' => 'Argentina',
                    'aff_iso' => 'AR',
                ],
                [
                    'OGR_FID' => 262,
                    'geometry' => '',
                    'country' => 'Armenia',
                    'iso' => 'ARM',
                    'countryaff' => 'Armenia',
                    'aff_iso' => 'AM',
                ],
                [
                    'OGR_FID' => 263,
                    'geometry' => '',
                    'country' => 'Aruba',
                    'iso' => 'ABW',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 264,
                    'geometry' => '',
                    'country' => 'Australia',
                    'iso' => 'AUS',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 265,
                    'geometry' => '',
                    'country' => 'Austria',
                    'iso' => 'AUT',
                    'countryaff' => 'Austria',
                    'aff_iso' => 'AT',
                ],
                [
                    'OGR_FID' => 266,
                    'geometry' => '',
                    'country' => 'Azerbaijan',
                    'iso' => 'AZE',
                    'countryaff' => 'Azerbaijan',
                    'aff_iso' => 'AZ',
                ],
                [
                    'OGR_FID' => 267,
                    'geometry' => '',
                    'country' => 'Azores',
                    'iso' => '',
                    'countryaff' => 'Portugal',
                    'aff_iso' => '',
                ],
                [
                    'OGR_FID' => 268,
                    'geometry' => '',
                    'country' => 'Bahamas',
                    'iso' => 'BHS',
                    'countryaff' => 'Bahamas',
                    'aff_iso' => 'BS',
                ],
                [
                    'OGR_FID' => 269,
                    'geometry' => '',
                    'country' => 'Bahrain',
                    'iso' => 'BHR',
                    'countryaff' => 'Bahrain',
                    'aff_iso' => 'BH',
                ],
                [
                    'OGR_FID' => 270,
                    'geometry' => '',
                    'country' => 'Bangladesh',
                    'iso' => 'BGD',
                    'countryaff' => 'Bangladesh',
                    'aff_iso' => 'BD',
                ],
                [
                    'OGR_FID' => 271,
                    'geometry' => '',
                    'country' => 'Barbados',
                    'iso' => 'BRB',
                    'countryaff' => 'Barbados',
                    'aff_iso' => 'BB',
                ],
                [
                    'OGR_FID' => 272,
                    'geometry' => '',
                    'country' => 'Belarus',
                    'iso' => 'BLR',
                    'countryaff' => 'Belarus',
                    'aff_iso' => 'BY',
                ],
                [
                    'OGR_FID' => 273,
                    'geometry' => '',
                    'country' => 'Belgium',
                    'iso' => 'BEL',
                    'countryaff' => 'Belgium',
                    'aff_iso' => 'BE',
                ],
                [
                    'OGR_FID' => 274,
                    'geometry' => '',
                    'country' => 'Belize',
                    'iso' => 'BLZ',
                    'countryaff' => 'Belize',
                    'aff_iso' => 'BZ',
                ],
                [
                    'OGR_FID' => 275,
                    'geometry' => '',
                    'country' => 'Benin',
                    'iso' => 'BEN',
                    'countryaff' => 'Benin',
                    'aff_iso' => 'BJ',
                ],
                [
                    'OGR_FID' => 276,
                    'geometry' => '',
                    'country' => 'Bermuda',
                    'iso' => 'BMU',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 277,
                    'geometry' => '',
                    'country' => 'Bhutan',
                    'iso' => 'BTN',
                    'countryaff' => 'Bhutan',
                    'aff_iso' => 'BT',
                ],
                [
                    'OGR_FID' => 278,
                    'geometry' => '',
                    'country' => 'Bolivia',
                    'iso' => 'BOL',
                    'countryaff' => 'Bolivia, Plurinational State of',
                    'aff_iso' => 'BO',
                ],
                [
                    'OGR_FID' => 279,
                    'geometry' => '',
                    'country' => 'Bonaire',
                    'iso' => 'BES',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 280,
                    'geometry' => '',
                    'country' => 'Bosnia and Herzegovina',
                    'iso' => 'BIH',
                    'countryaff' => 'Bosnia and Herzegovina',
                    'aff_iso' => 'BA',
                ],
                [
                    'OGR_FID' => 281,
                    'geometry' => '',
                    'country' => 'Botswana',
                    'iso' => 'BWA',
                    'countryaff' => 'Botswana',
                    'aff_iso' => 'BW',
                ],
                [
                    'OGR_FID' => 282,
                    'geometry' => '',
                    'country' => 'Bouvet Island',
                    'iso' => 'BVT',
                    'countryaff' => 'Norway',
                    'aff_iso' => 'NO',
                ],
                [
                    'OGR_FID' => 283,
                    'geometry' => '',
                    'country' => 'Brazil',
                    'iso' => 'BRA',
                    'countryaff' => 'Brazil',
                    'aff_iso' => 'BR',
                ],
                [
                    'OGR_FID' => 284,
                    'geometry' => '',
                    'country' => 'British Indian Ocean Territory',
                    'iso' => 'IOT',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 285,
                    'geometry' => '',
                    'country' => 'British Virgin Islands',
                    'iso' => 'VGB',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 286,
                    'geometry' => '',
                    'country' => 'Brunei Darussalam',
                    'iso' => 'BRN',
                    'countryaff' => 'Brunei Darussalam',
                    'aff_iso' => 'BN',
                ],
                [
                    'OGR_FID' => 287,
                    'geometry' => '',
                    'country' => 'Bulgaria',
                    'iso' => 'BGR',
                    'countryaff' => 'Bulgaria',
                    'aff_iso' => 'BG',
                ],
                [
                    'OGR_FID' => 288,
                    'geometry' => '',
                    'country' => 'Burkina Faso',
                    'iso' => 'BFA',
                    'countryaff' => 'Burkina Faso',
                    'aff_iso' => 'BF',
                ],
                [
                    'OGR_FID' => 289,
                    'geometry' => '',
                    'country' => 'Burundi',
                    'iso' => 'BDI',
                    'countryaff' => 'Burundi',
                    'aff_iso' => 'BI',
                ],
                [
                    'OGR_FID' => 290,
                    'geometry' => '',
                    'country' => 'Cabo Verde',
                    'iso' => 'CPV',
                    'countryaff' => 'Cabo Verde',
                    'aff_iso' => 'CV',
                ],
                [
                    'OGR_FID' => 291,
                    'geometry' => '',
                    'country' => 'Cambodia',
                    'iso' => 'KHM',
                    'countryaff' => 'Cambodia',
                    'aff_iso' => 'KH',
                ],
                [
                    'OGR_FID' => 292,
                    'geometry' => '',
                    'country' => 'Cameroon',
                    'iso' => 'CMR',
                    'countryaff' => 'Cameroon',
                    'aff_iso' => 'CM',
                ],
                [
                    'OGR_FID' => 293,
                    'geometry' => '',
                    'country' => 'Canada',
                    'iso' => 'CAN',
                    'countryaff' => 'Canada',
                    'aff_iso' => 'CA',
                ],
                [
                    'OGR_FID' => 294,
                    'geometry' => '',
                    'country' => 'Canarias',
                    'iso' => '',
                    'countryaff' => 'Spain',
                    'aff_iso' => '',
                ],
                [
                    'OGR_FID' => 295,
                    'geometry' => '',
                    'country' => 'Cayman Islands',
                    'iso' => 'CYM',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 296,
                    'geometry' => '',
                    'country' => 'Central African Republic',
                    'iso' => 'CAF',
                    'countryaff' => 'Central African Republic',
                    'aff_iso' => 'CF',
                ],
                [
                    'OGR_FID' => 297,
                    'geometry' => '',
                    'country' => 'Chad',
                    'iso' => 'TCD',
                    'countryaff' => 'Chad',
                    'aff_iso' => 'TD',
                ],
                [
                    'OGR_FID' => 298,
                    'geometry' => '',
                    'country' => 'Chile',
                    'iso' => 'CHL',
                    'countryaff' => 'Chile',
                    'aff_iso' => 'CL',
                ],
                [
                    'OGR_FID' => 299,
                    'geometry' => '',
                    'country' => 'China',
                    'iso' => 'CHN',
                    'countryaff' => 'China',
                    'aff_iso' => 'CN',
                ],
                [
                    'OGR_FID' => 300,
                    'geometry' => '',
                    'country' => 'Christmas Island',
                    'iso' => 'CXR',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 301,
                    'geometry' => '',
                    'country' => 'Cocos Islands',
                    'iso' => 'CCK',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 302,
                    'geometry' => '',
                    'country' => 'Colombia',
                    'iso' => 'COL',
                    'countryaff' => 'Colombia',
                    'aff_iso' => 'CO',
                ],
                [
                    'OGR_FID' => 303,
                    'geometry' => '',
                    'country' => 'Comoros',
                    'iso' => 'COM',
                    'countryaff' => 'Comoros',
                    'aff_iso' => 'KM',
                ],
                [
                    'OGR_FID' => 304,
                    'geometry' => '',
                    'country' => 'Congo',
                    'iso' => 'COG',
                    'countryaff' => 'Congo',
                    'aff_iso' => 'CG',
                ],
                [
                    'OGR_FID' => 305,
                    'geometry' => '',
                    'country' => 'Congo DRC',
                    'iso' => 'COD',
                    'countryaff' => 'Congo, The Democratic Republic of the',
                    'aff_iso' => 'CD',
                ],
                [
                    'OGR_FID' => 306,
                    'geometry' => '',
                    'country' => 'Cook Islands',
                    'iso' => 'COK',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 307,
                    'geometry' => '',
                    'country' => 'Costa Rica',
                    'iso' => 'CRI',
                    'countryaff' => 'Costa Rica',
                    'aff_iso' => 'CR',
                ],
                [
                    'OGR_FID' => 308,
                    'geometry' => '',
                    'country' => 'Côte d\'Ivoire',
                    'iso' => 'CIV',
                    'countryaff' => 'Côte d\'Ivoire',
                    'aff_iso' => 'CI',
                ],
                [
                    'OGR_FID' => 309,
                    'geometry' => '',
                    'country' => 'Croatia',
                    'iso' => 'HRV',
                    'countryaff' => 'Croatia',
                    'aff_iso' => 'HR',
                ],
                [
                    'OGR_FID' => 310,
                    'geometry' => '',
                    'country' => 'Cuba',
                    'iso' => 'CUB',
                    'countryaff' => 'Cuba',
                    'aff_iso' => 'CU',
                ],
                [
                    'OGR_FID' => 311,
                    'geometry' => '',
                    'country' => 'Curacao',
                    'iso' => 'CUW',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 312,
                    'geometry' => '',
                    'country' => 'Cyprus',
                    'iso' => 'CYP',
                    'countryaff' => 'Cyprus',
                    'aff_iso' => 'CY',
                ],
                [
                    'OGR_FID' => 313,
                    'geometry' => '',
                    'country' => 'Czech Republic',
                    'iso' => 'CZE',
                    'countryaff' => 'Czechia',
                    'aff_iso' => 'CZ',
                ],
                [
                    'OGR_FID' => 314,
                    'geometry' => '',
                    'country' => 'Denmark',
                    'iso' => 'DNK',
                    'countryaff' => 'Denmark',
                    'aff_iso' => 'DK',
                ],
                [
                    'OGR_FID' => 315,
                    'geometry' => '',
                    'country' => 'Djibouti',
                    'iso' => 'DJI',
                    'countryaff' => 'Djibouti',
                    'aff_iso' => 'DJ',
                ],
                [
                    'OGR_FID' => 316,
                    'geometry' => '',
                    'country' => 'Dominica',
                    'iso' => 'DMA',
                    'countryaff' => 'Dominica',
                    'aff_iso' => 'DM',
                ],
                [
                    'OGR_FID' => 317,
                    'geometry' => '',
                    'country' => 'Dominican Republic',
                    'iso' => 'DOM',
                    'countryaff' => 'Dominican Republic',
                    'aff_iso' => 'DO',
                ],
                [
                    'OGR_FID' => 318,
                    'geometry' => '',
                    'country' => 'Ecuador',
                    'iso' => 'ECU',
                    'countryaff' => 'Ecuador',
                    'aff_iso' => 'EC',
                ],
                [
                    'OGR_FID' => 319,
                    'geometry' => '',
                    'country' => 'Egypt',
                    'iso' => 'EGY',
                    'countryaff' => 'Egypt',
                    'aff_iso' => 'EG',
                ],
                [
                    'OGR_FID' => 320,
                    'geometry' => '',
                    'country' => 'El Salvador',
                    'iso' => 'SLV',
                    'countryaff' => 'El Salvador',
                    'aff_iso' => 'SV',
                ],
                [
                    'OGR_FID' => 321,
                    'geometry' => '',
                    'country' => 'Equatorial Guinea',
                    'iso' => 'GNQ',
                    'countryaff' => 'Equatorial Guinea',
                    'aff_iso' => 'GQ',
                ],
                [
                    'OGR_FID' => 322,
                    'geometry' => '',
                    'country' => 'Eritrea',
                    'iso' => 'ERI',
                    'countryaff' => 'Eritrea',
                    'aff_iso' => 'ER',
                ],
                [
                    'OGR_FID' => 323,
                    'geometry' => '',
                    'country' => 'Estonia',
                    'iso' => 'EST',
                    'countryaff' => 'Estonia',
                    'aff_iso' => 'EE',
                ],
                [
                    'OGR_FID' => 324,
                    'geometry' => '',
                    'country' => 'Eswatini',
                    'iso' => 'SWZ',
                    'countryaff' => 'Eswatini',
                    'aff_iso' => 'SZ',
                ],
                [
                    'OGR_FID' => 325,
                    'geometry' => '',
                    'country' => 'Ethiopia',
                    'iso' => 'ETH',
                    'countryaff' => 'Ethiopia',
                    'aff_iso' => 'ET',
                ],
                [
                    'OGR_FID' => 326,
                    'geometry' => '',
                    'country' => 'Falkland Islands',
                    'iso' => 'FLK',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 327,
                    'geometry' => '',
                    'country' => 'Faroe Islands',
                    'iso' => 'FRO',
                    'countryaff' => 'Denmark',
                    'aff_iso' => 'DK',
                ],
                [
                    'OGR_FID' => 328,
                    'geometry' => '',
                    'country' => 'Fiji',
                    'iso' => 'FJI',
                    'countryaff' => 'Fiji',
                    'aff_iso' => 'FJ',
                ],
                [
                    'OGR_FID' => 329,
                    'geometry' => '',
                    'country' => 'Finland',
                    'iso' => 'FIN',
                    'countryaff' => 'Finland',
                    'aff_iso' => 'FI',
                ],
                [
                    'OGR_FID' => 330,
                    'geometry' => '',
                    'country' => 'France',
                    'iso' => 'FRA',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 331,
                    'geometry' => '',
                    'country' => 'French Guiana',
                    'iso' => 'GUF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 332,
                    'geometry' => '',
                    'country' => 'French Polynesia',
                    'iso' => 'PYF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 333,
                    'geometry' => '',
                    'country' => 'French Southern Territories',
                    'iso' => 'ATF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 334,
                    'geometry' => '',
                    'country' => 'Gabon',
                    'iso' => 'GAB',
                    'countryaff' => 'Gabon',
                    'aff_iso' => 'GA',
                ],
                [
                    'OGR_FID' => 335,
                    'geometry' => '',
                    'country' => 'Gambia',
                    'iso' => 'GMB',
                    'countryaff' => 'Gambia',
                    'aff_iso' => 'GM',
                ],
                [
                    'OGR_FID' => 336,
                    'geometry' => '',
                    'country' => 'Georgia',
                    'iso' => 'GEO',
                    'countryaff' => 'Georgia',
                    'aff_iso' => 'GE',
                ],
                [
                    'OGR_FID' => 337,
                    'geometry' => '',
                    'country' => 'Germany',
                    'iso' => 'DEU',
                    'countryaff' => 'Germany',
                    'aff_iso' => 'DE',
                ],
                [
                    'OGR_FID' => 338,
                    'geometry' => '',
                    'country' => 'Ghana',
                    'iso' => 'GHA',
                    'countryaff' => 'Ghana',
                    'aff_iso' => 'GH',
                ],
                [
                    'OGR_FID' => 339,
                    'geometry' => '',
                    'country' => 'Gibraltar',
                    'iso' => 'GIB',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 340,
                    'geometry' => '',
                    'country' => 'Glorioso Islands',
                    'iso' => 'ATF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 341,
                    'geometry' => '',
                    'country' => 'Greece',
                    'iso' => 'GRC',
                    'countryaff' => 'Greece',
                    'aff_iso' => 'GR',
                ],
                [
                    'OGR_FID' => 342,
                    'geometry' => '',
                    'country' => 'Greenland',
                    'iso' => 'GRL',
                    'countryaff' => 'Denmark',
                    'aff_iso' => 'DK',
                ],
                [
                    'OGR_FID' => 343,
                    'geometry' => '',
                    'country' => 'Grenada',
                    'iso' => 'GRD',
                    'countryaff' => 'Grenada',
                    'aff_iso' => 'GD',
                ],
                [
                    'OGR_FID' => 344,
                    'geometry' => '',
                    'country' => 'Guadeloupe',
                    'iso' => 'GLP',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 345,
                    'geometry' => '',
                    'country' => 'Guam',
                    'iso' => 'GUM',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 346,
                    'geometry' => '',
                    'country' => 'Guatemala',
                    'iso' => 'GTM',
                    'countryaff' => 'Guatemala',
                    'aff_iso' => 'GT',
                ],
                [
                    'OGR_FID' => 347,
                    'geometry' => '',
                    'country' => 'Guernsey',
                    'iso' => 'GGY',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 348,
                    'geometry' => '',
                    'country' => 'Guinea',
                    'iso' => 'GIN',
                    'countryaff' => 'Guinea',
                    'aff_iso' => 'GN',
                ],
                [
                    'OGR_FID' => 349,
                    'geometry' => '',
                    'country' => 'Guinea-Bissau',
                    'iso' => 'GNB',
                    'countryaff' => 'Guinea-Bissau',
                    'aff_iso' => 'GW',
                ],
                [
                    'OGR_FID' => 350,
                    'geometry' => '',
                    'country' => 'Guyana',
                    'iso' => 'GUY',
                    'countryaff' => 'Guyana',
                    'aff_iso' => 'GY',
                ],
                [
                    'OGR_FID' => 351,
                    'geometry' => '',
                    'country' => 'Haiti',
                    'iso' => 'HTI',
                    'countryaff' => 'Haiti',
                    'aff_iso' => 'HT',
                ],
                [
                    'OGR_FID' => 352,
                    'geometry' => '',
                    'country' => 'Heard Island and McDonald Islands',
                    'iso' => 'HMD',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 353,
                    'geometry' => '',
                    'country' => 'Honduras',
                    'iso' => 'HND',
                    'countryaff' => 'Honduras',
                    'aff_iso' => 'HN',
                ],
                [
                    'OGR_FID' => 354,
                    'geometry' => '',
                    'country' => 'Hungary',
                    'iso' => 'HUN',
                    'countryaff' => 'Hungary',
                    'aff_iso' => 'HU',
                ],
                [
                    'OGR_FID' => 355,
                    'geometry' => '',
                    'country' => 'Iceland',
                    'iso' => 'ISL',
                    'countryaff' => 'Iceland',
                    'aff_iso' => 'IS',
                ],
                [
                    'OGR_FID' => 356,
                    'geometry' => '',
                    'country' => 'India',
                    'iso' => 'IND',
                    'countryaff' => 'India',
                    'aff_iso' => 'IN',
                ],
                [
                    'OGR_FID' => 357,
                    'geometry' => '',
                    'country' => 'Indonesia',
                    'iso' => 'IDN',
                    'countryaff' => 'Indonesia',
                    'aff_iso' => 'ID',
                ],
                [
                    'OGR_FID' => 358,
                    'geometry' => '',
                    'country' => 'Iran',
                    'iso' => 'IRN',
                    'countryaff' => 'Iran, Islamic Republic of',
                    'aff_iso' => 'IR',
                ],
                [
                    'OGR_FID' => 359,
                    'geometry' => '',
                    'country' => 'Iraq',
                    'iso' => 'IRQ',
                    'countryaff' => 'Iraq',
                    'aff_iso' => 'IQ',
                ],
                [
                    'OGR_FID' => 360,
                    'geometry' => '',
                    'country' => 'Ireland',
                    'iso' => 'IRL',
                    'countryaff' => 'Ireland',
                    'aff_iso' => 'IE',
                ],
                [
                    'OGR_FID' => 361,
                    'geometry' => '',
                    'country' => 'Isle of Man',
                    'iso' => 'IMN',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 362,
                    'geometry' => '',
                    'country' => 'Israel',
                    'iso' => 'ISR',
                    'countryaff' => 'Israel',
                    'aff_iso' => 'IL',
                ],
                [
                    'OGR_FID' => 363,
                    'geometry' => '',
                    'country' => 'Italy',
                    'iso' => 'ITA',
                    'countryaff' => 'Italy',
                    'aff_iso' => 'IT',
                ],
                [
                    'OGR_FID' => 364,
                    'geometry' => '',
                    'country' => 'Jamaica',
                    'iso' => 'JAM',
                    'countryaff' => 'Jamaica',
                    'aff_iso' => 'JM',
                ],
                [
                    'OGR_FID' => 365,
                    'geometry' => '',
                    'country' => 'Japan',
                    'iso' => 'JPN',
                    'countryaff' => 'Japan',
                    'aff_iso' => 'JP',
                ],
                [
                    'OGR_FID' => 366,
                    'geometry' => '',
                    'country' => 'Jersey',
                    'iso' => 'JEY',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 367,
                    'geometry' => '',
                    'country' => 'Jordan',
                    'iso' => 'JOR',
                    'countryaff' => 'Jordan',
                    'aff_iso' => 'JO',
                ],
                [
                    'OGR_FID' => 368,
                    'geometry' => '',
                    'country' => 'Juan De Nova Island',
                    'iso' => 'ATF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 369,
                    'geometry' => '',
                    'country' => 'Kazakhstan',
                    'iso' => 'KAZ',
                    'countryaff' => 'Kazakhstan',
                    'aff_iso' => 'KZ',
                ],
                [
                    'OGR_FID' => 370,
                    'geometry' => '',
                    'country' => 'Kenya',
                    'iso' => 'KEN',
                    'countryaff' => 'Kenya',
                    'aff_iso' => 'KE',
                ],
                [
                    'OGR_FID' => 371,
                    'geometry' => '',
                    'country' => 'Kiribati',
                    'iso' => 'KIR',
                    'countryaff' => 'Kiribati',
                    'aff_iso' => 'KI',
                ],
                [
                    'OGR_FID' => 372,
                    'geometry' => '',
                    'country' => 'Kuwait',
                    'iso' => 'KWT',
                    'countryaff' => 'Kuwait',
                    'aff_iso' => 'KW',
                ],
                [
                    'OGR_FID' => 373,
                    'geometry' => '',
                    'country' => 'Kyrgyzstan',
                    'iso' => 'KGZ',
                    'countryaff' => 'Kyrgyzstan',
                    'aff_iso' => 'KG',
                ],
                [
                    'OGR_FID' => 374,
                    'geometry' => '',
                    'country' => 'Laos',
                    'iso' => 'LAO',
                    'countryaff' => 'Lao People\'s Democratic Republic',
                    'aff_iso' => 'LA',
                ],
                [
                    'OGR_FID' => 375,
                    'geometry' => '',
                    'country' => 'Latvia',
                    'iso' => 'LVA',
                    'countryaff' => 'Latvia',
                    'aff_iso' => 'LV',
                ],
                [
                    'OGR_FID' => 376,
                    'geometry' => '',
                    'country' => 'Lebanon',
                    'iso' => 'LBN',
                    'countryaff' => 'Lebanon',
                    'aff_iso' => 'LB',
                ],
                [
                    'OGR_FID' => 377,
                    'geometry' => '',
                    'country' => 'Lesotho',
                    'iso' => 'LSO',
                    'countryaff' => 'Lesotho',
                    'aff_iso' => 'LS',
                ],
                [
                    'OGR_FID' => 378,
                    'geometry' => '',
                    'country' => 'Liberia',
                    'iso' => 'LBR',
                    'countryaff' => 'Liberia',
                    'aff_iso' => 'LR',
                ],
                [
                    'OGR_FID' => 379,
                    'geometry' => '',
                    'country' => 'Libya',
                    'iso' => 'LBY',
                    'countryaff' => 'Libya',
                    'aff_iso' => 'LY',
                ],
                [
                    'OGR_FID' => 380,
                    'geometry' => '',
                    'country' => 'Liechtenstein',
                    'iso' => 'LIE',
                    'countryaff' => 'Liechtenstein',
                    'aff_iso' => 'LI',
                ],
                [
                    'OGR_FID' => 381,
                    'geometry' => '',
                    'country' => 'Lithuania',
                    'iso' => 'LTU',
                    'countryaff' => 'Lithuania',
                    'aff_iso' => 'LT',
                ],
                [
                    'OGR_FID' => 382,
                    'geometry' => '',
                    'country' => 'Luxembourg',
                    'iso' => 'LUX',
                    'countryaff' => 'Luxembourg',
                    'aff_iso' => 'LU',
                ],
                [
                    'OGR_FID' => 383,
                    'geometry' => '',
                    'country' => 'Madagascar',
                    'iso' => 'MDG',
                    'countryaff' => 'Madagascar',
                    'aff_iso' => 'MG',
                ],
                [
                    'OGR_FID' => 384,
                    'geometry' => '',
                    'country' => 'Madeira',
                    'iso' => '',
                    'countryaff' => 'Portugal',
                    'aff_iso' => '',
                ],
                [
                    'OGR_FID' => 385,
                    'geometry' => '',
                    'country' => 'Malawi',
                    'iso' => 'MWI',
                    'countryaff' => 'Malawi',
                    'aff_iso' => 'MW',
                ],
                [
                    'OGR_FID' => 386,
                    'geometry' => '',
                    'country' => 'Malaysia',
                    'iso' => 'MYS',
                    'countryaff' => 'Malaysia',
                    'aff_iso' => 'MY',
                ],
                [
                    'OGR_FID' => 387,
                    'geometry' => '',
                    'country' => 'Maldives',
                    'iso' => 'MDV',
                    'countryaff' => 'Maldives',
                    'aff_iso' => 'MV',
                ],
                [
                    'OGR_FID' => 388,
                    'geometry' => '',
                    'country' => 'Mali',
                    'iso' => 'MLI',
                    'countryaff' => 'Mali',
                    'aff_iso' => 'ML',
                ],
                [
                    'OGR_FID' => 389,
                    'geometry' => '',
                    'country' => 'Malta',
                    'iso' => 'MLT',
                    'countryaff' => 'Malta',
                    'aff_iso' => 'MT',
                ],
                [
                    'OGR_FID' => 390,
                    'geometry' => '',
                    'country' => 'Marshall Islands',
                    'iso' => 'MHL',
                    'countryaff' => 'Marshall Islands',
                    'aff_iso' => 'MH',
                ],
                [
                    'OGR_FID' => 391,
                    'geometry' => '',
                    'country' => 'Martinique',
                    'iso' => 'MTQ',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 392,
                    'geometry' => '',
                    'country' => 'Mauritania',
                    'iso' => 'MRT',
                    'countryaff' => 'Mauritania',
                    'aff_iso' => 'MR',
                ],
                [
                    'OGR_FID' => 393,
                    'geometry' => '',
                    'country' => 'Mauritius',
                    'iso' => 'MUS',
                    'countryaff' => 'Mauritius',
                    'aff_iso' => 'MU',
                ],
                [
                    'OGR_FID' => 394,
                    'geometry' => '',
                    'country' => 'Mayotte',
                    'iso' => 'MYT',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 395,
                    'geometry' => '',
                    'country' => 'Mexico',
                    'iso' => 'MEX',
                    'countryaff' => 'Mexico',
                    'aff_iso' => 'MX',
                ],
                [
                    'OGR_FID' => 396,
                    'geometry' => '',
                    'country' => 'Micronesia',
                    'iso' => 'FSM',
                    'countryaff' => 'Micronesia, Federated States of',
                    'aff_iso' => 'FM',
                ],
                [
                    'OGR_FID' => 397,
                    'geometry' => '',
                    'country' => 'Moldova',
                    'iso' => 'MDA',
                    'countryaff' => 'Moldova, Republic of',
                    'aff_iso' => 'MD',
                ],
                [
                    'OGR_FID' => 398,
                    'geometry' => '',
                    'country' => 'Monaco',
                    'iso' => 'MCO',
                    'countryaff' => 'Monaco',
                    'aff_iso' => 'MC',
                ],
                [
                    'OGR_FID' => 399,
                    'geometry' => '',
                    'country' => 'Mongolia',
                    'iso' => 'MNG',
                    'countryaff' => 'Mongolia',
                    'aff_iso' => 'MN',
                ],
                [
                    'OGR_FID' => 400,
                    'geometry' => '',
                    'country' => 'Montenegro',
                    'iso' => 'MNE',
                    'countryaff' => 'Montenegro',
                    'aff_iso' => 'ME',
                ],
                [
                    'OGR_FID' => 401,
                    'geometry' => '',
                    'country' => 'Montserrat',
                    'iso' => 'MSR',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 402,
                    'geometry' => '',
                    'country' => 'Morocco',
                    'iso' => 'MAR',
                    'countryaff' => 'Morocco',
                    'aff_iso' => 'MA',
                ],
                [
                    'OGR_FID' => 403,
                    'geometry' => '',
                    'country' => 'Mozambique',
                    'iso' => 'MOZ',
                    'countryaff' => 'Mozambique',
                    'aff_iso' => 'MZ',
                ],
                [
                    'OGR_FID' => 404,
                    'geometry' => '',
                    'country' => 'Myanmar',
                    'iso' => 'MMR',
                    'countryaff' => 'Myanmar',
                    'aff_iso' => 'MM',
                ],
                [
                    'OGR_FID' => 405,
                    'geometry' => '',
                    'country' => 'Namibia',
                    'iso' => 'NAM',
                    'countryaff' => 'Namibia',
                    'aff_iso' => 'NA',
                ],
                [
                    'OGR_FID' => 406,
                    'geometry' => '',
                    'country' => 'Nauru',
                    'iso' => 'NRU',
                    'countryaff' => 'Nauru',
                    'aff_iso' => 'NR',
                ],
                [
                    'OGR_FID' => 407,
                    'geometry' => '',
                    'country' => 'Nepal',
                    'iso' => 'NPL',
                    'countryaff' => 'Nepal',
                    'aff_iso' => 'NP',
                ],
                [
                    'OGR_FID' => 408,
                    'geometry' => '',
                    'country' => 'Netherlands',
                    'iso' => 'NLD',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 409,
                    'geometry' => '',
                    'country' => 'New Caledonia',
                    'iso' => 'NCL',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 410,
                    'geometry' => '',
                    'country' => 'New Zealand',
                    'iso' => 'NZL',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 411,
                    'geometry' => '',
                    'country' => 'Nicaragua',
                    'iso' => 'NIC',
                    'countryaff' => 'Nicaragua',
                    'aff_iso' => 'NI',
                ],
                [
                    'OGR_FID' => 412,
                    'geometry' => '',
                    'country' => 'Niger',
                    'iso' => 'NER',
                    'countryaff' => 'Niger',
                    'aff_iso' => 'NE',
                ],
                [
                    'OGR_FID' => 413,
                    'geometry' => '',
                    'country' => 'Nigeria',
                    'iso' => 'NGA',
                    'countryaff' => 'Nigeria',
                    'aff_iso' => 'NG',
                ],
                [
                    'OGR_FID' => 414,
                    'geometry' => '',
                    'country' => 'Niue',
                    'iso' => 'NIU',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 415,
                    'geometry' => '',
                    'country' => 'Norfolk Island',
                    'iso' => 'NFK',
                    'countryaff' => 'Australia',
                    'aff_iso' => 'AU',
                ],
                [
                    'OGR_FID' => 416,
                    'geometry' => '',
                    'country' => 'North Korea',
                    'iso' => 'PRK',
                    'countryaff' => 'Korea, Democratic People\'s Republic of',
                    'aff_iso' => 'KP',
                ],
                [
                    'OGR_FID' => 417,
                    'geometry' => '',
                    'country' => 'North Macedonia',
                    'iso' => 'MKD',
                    'countryaff' => 'North Macedonia',
                    'aff_iso' => 'MK',
                ],
                [
                    'OGR_FID' => 418,
                    'geometry' => '',
                    'country' => 'Northern Mariana Islands',
                    'iso' => 'MNP',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 419,
                    'geometry' => '',
                    'country' => 'Norway',
                    'iso' => 'NOR',
                    'countryaff' => 'Norway',
                    'aff_iso' => 'NO',
                ],
                [
                    'OGR_FID' => 420,
                    'geometry' => '',
                    'country' => 'Oman',
                    'iso' => 'OMN',
                    'countryaff' => 'Oman',
                    'aff_iso' => 'OM',
                ],
                [
                    'OGR_FID' => 421,
                    'geometry' => '',
                    'country' => 'Pakistan',
                    'iso' => 'PAK',
                    'countryaff' => 'Pakistan',
                    'aff_iso' => 'PK',
                ],
                [
                    'OGR_FID' => 422,
                    'geometry' => '',
                    'country' => 'Palau',
                    'iso' => 'PLW',
                    'countryaff' => 'Palau',
                    'aff_iso' => 'PW',
                ],
                [
                    'OGR_FID' => 423,
                    'geometry' => '',
                    'country' => 'Palestinian Territory',
                    'iso' => 'PSE',
                    'countryaff' => 'Palestine, State of',
                    'aff_iso' => 'PS',
                ],
                [
                    'OGR_FID' => 424,
                    'geometry' => '',
                    'country' => 'Panama',
                    'iso' => 'PAN',
                    'countryaff' => 'Panama',
                    'aff_iso' => 'PA',
                ],
                [
                    'OGR_FID' => 425,
                    'geometry' => '',
                    'country' => 'Papua New Guinea',
                    'iso' => 'PNG',
                    'countryaff' => 'Papua New Guinea',
                    'aff_iso' => 'PG',
                ],
                [
                    'OGR_FID' => 426,
                    'geometry' => '',
                    'country' => 'Paraguay',
                    'iso' => 'PRY',
                    'countryaff' => 'Paraguay',
                    'aff_iso' => 'PY',
                ],
                [
                    'OGR_FID' => 427,
                    'geometry' => '',
                    'country' => 'Peru',
                    'iso' => 'PER',
                    'countryaff' => 'Peru',
                    'aff_iso' => 'PE',
                ],
                [
                    'OGR_FID' => 428,
                    'geometry' => '',
                    'country' => 'Philippines',
                    'iso' => 'PHL',
                    'countryaff' => 'Philippines',
                    'aff_iso' => 'PH',
                ],
                [
                    'OGR_FID' => 429,
                    'geometry' => '',
                    'country' => 'Pitcairn',
                    'iso' => 'PCN',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 430,
                    'geometry' => '',
                    'country' => 'Poland',
                    'iso' => 'POL',
                    'countryaff' => 'Poland',
                    'aff_iso' => 'PL',
                ],
                [
                    'OGR_FID' => 431,
                    'geometry' => '',
                    'country' => 'Portugal',
                    'iso' => 'PRT',
                    'countryaff' => 'Portugal',
                    'aff_iso' => 'PT',
                ],
                [
                    'OGR_FID' => 432,
                    'geometry' => '',
                    'country' => 'Puerto Rico',
                    'iso' => 'PRI',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 433,
                    'geometry' => '',
                    'country' => 'Qatar',
                    'iso' => 'QAT',
                    'countryaff' => 'Qatar',
                    'aff_iso' => 'QA',
                ],
                [
                    'OGR_FID' => 434,
                    'geometry' => '',
                    'country' => 'Réunion',
                    'iso' => 'REU',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 435,
                    'geometry' => '',
                    'country' => 'Romania',
                    'iso' => 'ROU',
                    'countryaff' => 'Romania',
                    'aff_iso' => 'RO',
                ],
                [
                    'OGR_FID' => 436,
                    'geometry' => '',
                    'country' => 'Russian Federation',
                    'iso' => 'RUS',
                    'countryaff' => 'Russian Federation',
                    'aff_iso' => 'RU',
                ],
                [
                    'OGR_FID' => 437,
                    'geometry' => '',
                    'country' => 'Rwanda',
                    'iso' => 'RWA',
                    'countryaff' => 'Rwanda',
                    'aff_iso' => 'RW',
                ],
                [
                    'OGR_FID' => 438,
                    'geometry' => '',
                    'country' => 'Saba',
                    'iso' => 'BES',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 439,
                    'geometry' => '',
                    'country' => 'Saint Barthelemy',
                    'iso' => 'BLM',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 440,
                    'geometry' => '',
                    'country' => 'Saint Eustatius',
                    'iso' => 'BES',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 441,
                    'geometry' => '',
                    'country' => 'Saint Helena',
                    'iso' => 'SHN',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 442,
                    'geometry' => '',
                    'country' => 'Saint Kitts and Nevis',
                    'iso' => 'KNA',
                    'countryaff' => 'Saint Kitts and Nevis',
                    'aff_iso' => 'KN',
                ],
                [
                    'OGR_FID' => 443,
                    'geometry' => '',
                    'country' => 'Saint Lucia',
                    'iso' => 'LCA',
                    'countryaff' => 'Saint Lucia',
                    'aff_iso' => 'LC',
                ],
                [
                    'OGR_FID' => 444,
                    'geometry' => '',
                    'country' => 'Saint Martin',
                    'iso' => 'MAF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 445,
                    'geometry' => '',
                    'country' => 'Saint Pierre and Miquelon',
                    'iso' => 'SPM',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 446,
                    'geometry' => '',
                    'country' => 'Saint Vincent and the Grenadines',
                    'iso' => 'VCT',
                    'countryaff' => 'Saint Vincent and the Grenadines',
                    'aff_iso' => 'VC',
                ],
                [
                    'OGR_FID' => 447,
                    'geometry' => '',
                    'country' => 'Samoa',
                    'iso' => 'WSM',
                    'countryaff' => 'Samoa',
                    'aff_iso' => 'WS',
                ],
                [
                    'OGR_FID' => 448,
                    'geometry' => '',
                    'country' => 'San Marino',
                    'iso' => 'SMR',
                    'countryaff' => 'San Marino',
                    'aff_iso' => 'SM',
                ],
                [
                    'OGR_FID' => 449,
                    'geometry' => '',
                    'country' => 'Sao Tome and Principe',
                    'iso' => 'STP',
                    'countryaff' => 'São Tomé and Príncipe',
                    'aff_iso' => 'ST',
                ],
                [
                    'OGR_FID' => 450,
                    'geometry' => '',
                    'country' => 'Saudi Arabia',
                    'iso' => 'SAU',
                    'countryaff' => 'Saudi Arabia',
                    'aff_iso' => 'SA',
                ],
                [
                    'OGR_FID' => 451,
                    'geometry' => '',
                    'country' => 'Senegal',
                    'iso' => 'SEN',
                    'countryaff' => 'Senegal',
                    'aff_iso' => 'SN',
                ],
                [
                    'OGR_FID' => 452,
                    'geometry' => '',
                    'country' => 'Serbia',
                    'iso' => 'SRB',
                    'countryaff' => 'Serbia',
                    'aff_iso' => 'RS',
                ],
                [
                    'OGR_FID' => 453,
                    'geometry' => '',
                    'country' => 'Seychelles',
                    'iso' => 'SYC',
                    'countryaff' => 'Seychelles',
                    'aff_iso' => 'SC',
                ],
                [
                    'OGR_FID' => 454,
                    'geometry' => '',
                    'country' => 'Sierra Leone',
                    'iso' => 'SLE',
                    'countryaff' => 'Sierra Leone',
                    'aff_iso' => 'SL',
                ],
                [
                    'OGR_FID' => 455,
                    'geometry' => '',
                    'country' => 'Singapore',
                    'iso' => 'SGP',
                    'countryaff' => 'Singapore',
                    'aff_iso' => 'SG',
                ],
                [
                    'OGR_FID' => 456,
                    'geometry' => '',
                    'country' => 'Sint Maarten',
                    'iso' => 'SXM',
                    'countryaff' => 'Netherlands',
                    'aff_iso' => 'NL',
                ],
                [
                    'OGR_FID' => 457,
                    'geometry' => '',
                    'country' => 'Slovakia',
                    'iso' => 'SVK',
                    'countryaff' => 'Slovakia',
                    'aff_iso' => 'SK',
                ],
                [
                    'OGR_FID' => 458,
                    'geometry' => '',
                    'country' => 'Slovenia',
                    'iso' => 'SVN',
                    'countryaff' => 'Slovenia',
                    'aff_iso' => 'SI',
                ],
                [
                    'OGR_FID' => 459,
                    'geometry' => '',
                    'country' => 'Solomon Islands',
                    'iso' => 'SLB',
                    'countryaff' => 'Solomon Islands',
                    'aff_iso' => 'SB',
                ],
                [
                    'OGR_FID' => 460,
                    'geometry' => '',
                    'country' => 'Somalia',
                    'iso' => 'SOM',
                    'countryaff' => 'Somalia',
                    'aff_iso' => 'SO',
                ],
                [
                    'OGR_FID' => 461,
                    'geometry' => '',
                    'country' => 'South Africa',
                    'iso' => 'ZAF',
                    'countryaff' => 'South Africa',
                    'aff_iso' => 'ZA',
                ],
                [
                    'OGR_FID' => 462,
                    'geometry' => '',
                    'country' => 'South Georgia and South Sandwich Islands',
                    'iso' => 'SGS',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 463,
                    'geometry' => '',
                    'country' => 'South Korea',
                    'iso' => 'KOR',
                    'countryaff' => 'Korea, Republic of',
                    'aff_iso' => 'KR',
                ],
                [
                    'OGR_FID' => 464,
                    'geometry' => '',
                    'country' => 'South Sudan',
                    'iso' => 'SSD',
                    'countryaff' => 'South Sudan',
                    'aff_iso' => 'SS',
                ],
                [
                    'OGR_FID' => 465,
                    'geometry' => '',
                    'country' => 'Spain',
                    'iso' => 'ESP',
                    'countryaff' => 'Spain',
                    'aff_iso' => 'ES',
                ],
                [
                    'OGR_FID' => 466,
                    'geometry' => '',
                    'country' => 'Sri Lanka',
                    'iso' => 'LKA',
                    'countryaff' => 'Sri Lanka',
                    'aff_iso' => 'LK',
                ],
                [
                    'OGR_FID' => 467,
                    'geometry' => '',
                    'country' => 'Sudan',
                    'iso' => 'SDN',
                    'countryaff' => 'Sudan',
                    'aff_iso' => 'SD',
                ],
                [
                    'OGR_FID' => 468,
                    'geometry' => '',
                    'country' => 'Suriname',
                    'iso' => 'SUR',
                    'countryaff' => 'Suriname',
                    'aff_iso' => 'SR',
                ],
                [
                    'OGR_FID' => 469,
                    'geometry' => '',
                    'country' => 'Svalbard',
                    'iso' => 'SJM',
                    'countryaff' => 'Norway',
                    'aff_iso' => 'NO',
                ],
                [
                    'OGR_FID' => 470,
                    'geometry' => '',
                    'country' => 'Sweden',
                    'iso' => 'SWE',
                    'countryaff' => 'Sweden',
                    'aff_iso' => 'SE',
                ],
                [
                    'OGR_FID' => 471,
                    'geometry' => '',
                    'country' => 'Switzerland',
                    'iso' => 'CHE',
                    'countryaff' => 'Switzerland',
                    'aff_iso' => 'CH',
                ],
                [
                    'OGR_FID' => 472,
                    'geometry' => '',
                    'country' => 'Syria',
                    'iso' => 'SYR',
                    'countryaff' => 'Syrian Arab Republic',
                    'aff_iso' => 'SY',
                ],
                [
                    'OGR_FID' => 473,
                    'geometry' => '',
                    'country' => 'Tajikistan',
                    'iso' => 'TJK',
                    'countryaff' => 'Tajikistan',
                    'aff_iso' => 'TJ',
                ],
                [
                    'OGR_FID' => 474,
                    'geometry' => '',
                    'country' => 'Tanzania',
                    'iso' => 'TZA',
                    'countryaff' => 'Tanzania, United Republic of',
                    'aff_iso' => 'TZ',
                ],
                [
                    'OGR_FID' => 475,
                    'geometry' => '',
                    'country' => 'Thailand',
                    'iso' => 'THA',
                    'countryaff' => 'Thailand',
                    'aff_iso' => 'TH',
                ],
                [
                    'OGR_FID' => 476,
                    'geometry' => '',
                    'country' => 'Timor-Leste',
                    'iso' => 'TLS',
                    'countryaff' => 'Timor-Leste',
                    'aff_iso' => 'TL',
                ],
                [
                    'OGR_FID' => 477,
                    'geometry' => '',
                    'country' => 'Togo',
                    'iso' => 'TGO',
                    'countryaff' => 'Togo',
                    'aff_iso' => 'TG',
                ],
                [
                    'OGR_FID' => 478,
                    'geometry' => '',
                    'country' => 'Tokelau',
                    'iso' => 'TKL',
                    'countryaff' => 'New Zealand',
                    'aff_iso' => 'NZ',
                ],
                [
                    'OGR_FID' => 479,
                    'geometry' => '',
                    'country' => 'Tonga',
                    'iso' => 'TON',
                    'countryaff' => 'Tonga',
                    'aff_iso' => 'TO',
                ],
                [
                    'OGR_FID' => 480,
                    'geometry' => '',
                    'country' => 'Trinidad and Tobago',
                    'iso' => 'TTO',
                    'countryaff' => 'Trinidad and Tobago',
                    'aff_iso' => 'TT',
                ],
                [
                    'OGR_FID' => 481,
                    'geometry' => '',
                    'country' => 'Tunisia',
                    'iso' => 'TUN',
                    'countryaff' => 'Tunisia',
                    'aff_iso' => 'TN',
                ],
                [
                    'OGR_FID' => 482,
                    'geometry' => '',
                    'country' => 'Turkiye',
                    'iso' => 'TUR',
                    'countryaff' => 'Turkiye',
                    'aff_iso' => 'TR',
                ],
                [
                    'OGR_FID' => 483,
                    'geometry' => '',
                    'country' => 'Turkmenistan',
                    'iso' => 'TKM',
                    'countryaff' => 'Turkmenistan',
                    'aff_iso' => 'TM',
                ],
                [
                    'OGR_FID' => 484,
                    'geometry' => '',
                    'country' => 'Turks and Caicos Islands',
                    'iso' => 'TCA',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 485,
                    'geometry' => '',
                    'country' => 'Tuvalu',
                    'iso' => 'TUV',
                    'countryaff' => 'Tuvalu',
                    'aff_iso' => 'TV',
                ],
                [
                    'OGR_FID' => 486,
                    'geometry' => '',
                    'country' => 'Uganda',
                    'iso' => 'UGA',
                    'countryaff' => 'Uganda',
                    'aff_iso' => 'UG',
                ],
                [
                    'OGR_FID' => 487,
                    'geometry' => '',
                    'country' => 'Ukraine',
                    'iso' => 'UKR',
                    'countryaff' => 'Ukraine',
                    'aff_iso' => 'UA',
                ],
                [
                    'OGR_FID' => 488,
                    'geometry' => '',
                    'country' => 'United Arab Emirates',
                    'iso' => 'ARE',
                    'countryaff' => 'United Arab Emirates',
                    'aff_iso' => 'AE',
                ],
                [
                    'OGR_FID' => 489,
                    'geometry' => '',
                    'country' => 'United Kingdom',
                    'iso' => 'GBR',
                    'countryaff' => 'United Kingdom',
                    'aff_iso' => 'GB',
                ],
                [
                    'OGR_FID' => 490,
                    'geometry' => '',
                    'country' => 'United States',
                    'iso' => 'USA',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 491,
                    'geometry' => '',
                    'country' => 'United States Minor Outlying Islands',
                    'iso' => 'UMI',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 492,
                    'geometry' => '',
                    'country' => 'Uruguay',
                    'iso' => 'URY',
                    'countryaff' => 'Uruguay',
                    'aff_iso' => 'UY',
                ],
                [
                    'OGR_FID' => 493,
                    'geometry' => '',
                    'country' => 'US Virgin Islands',
                    'iso' => 'VIR',
                    'countryaff' => 'United States',
                    'aff_iso' => 'US',
                ],
                [
                    'OGR_FID' => 494,
                    'geometry' => '',
                    'country' => 'Uzbekistan',
                    'iso' => 'UZB',
                    'countryaff' => 'Uzbekistan',
                    'aff_iso' => 'UZ',
                ],
                [
                    'OGR_FID' => 495,
                    'geometry' => '',
                    'country' => 'Vanuatu',
                    'iso' => 'VUT',
                    'countryaff' => 'Vanuatu',
                    'aff_iso' => 'VU',
                ],
                [
                    'OGR_FID' => 496,
                    'geometry' => '',
                    'country' => 'Vatican City',
                    'iso' => 'VAT',
                    'countryaff' => 'Holy See (Vatican City State)',
                    'aff_iso' => 'VA',
                ],
                [
                    'OGR_FID' => 497,
                    'geometry' => '',
                    'country' => 'Venezuela',
                    'iso' => 'VEN',
                    'countryaff' => 'Venezuela, Bolivarian Republic of',
                    'aff_iso' => 'VE',
                ],
                [
                    'OGR_FID' => 498,
                    'geometry' => '',
                    'country' => 'Vietnam',
                    'iso' => 'VNM',
                    'countryaff' => 'Viet Nam',
                    'aff_iso' => 'VN',
                ],
                [
                    'OGR_FID' => 499,
                    'geometry' => '',
                    'country' => 'Wallis and Futuna',
                    'iso' => 'WLF',
                    'countryaff' => 'France',
                    'aff_iso' => 'FR',
                ],
                [
                    'OGR_FID' => 500,
                    'geometry' => '',
                    'country' => 'Yemen',
                    'iso' => 'YEM',
                    'countryaff' => 'Yemen',
                    'aff_iso' => 'YE',
                ],
                [
                    'OGR_FID' => 501,
                    'geometry' => '',
                    'country' => 'Zambia',
                    'iso' => 'ZMB',
                    'countryaff' => 'Zambia',
                    'aff_iso' => 'ZM',
                ],
                [
                    'OGR_FID' => 502,
                    'geometry' => '',
                    'country' => 'Zimbabwe',
                    'iso' => 'ZWE',
                    'countryaff' => 'Zimbabwe',
                    'aff_iso' => 'ZW',
                ],
            ];

            $successCount = 0;
            $failCount = 0;

            foreach ($countries as $country) {
                try {
                    if (isset($geometry[$country['aff_iso']])) {
                        $country['geometry'] = DB::raw('ST_GeomFromGeoJSON(' . json_encode($geometry[$country['aff_iso']]) . ')');
                        $inserted = DB::table('world_countries_generalized')->insert($country);
                        
                        if ($inserted) {
                            $successCount++;
                            $this->command->info("Country {$country['country']} (ISO: {$country['iso']}) inserted successfully.");
                        } else {
                            $failCount++;
                            $this->command->warn("Failed to insert country {$country['country']} (ISO: {$country['iso']})");
                        }
                    } else {
                        $failCount++;
                        $this->command->warn("No geometry found for country {$country['country']} (ISO: {$country['iso']})");
                    }
                } catch (Exception $e) {
                    $failCount++;
                    $this->command->error("Error inserting country {$country['country']} (ISO: {$country['iso']}): " . $e->getMessage());
                }
            }
            
            $this->command->info("World countries seeding completed. Successes: $successCount, Failures: $failCount");
            
        } catch (Exception $e) {
            $this->command->error('Failed to seed world countries data: ' . $e->getMessage());
        }
    }
}
