services:
    php:
        depends_on:
            - "motocker"
        build:
            context: "."
            dockerfile: "docker/php.Dockerfile"
            network: host
        ports:
            - "8080:80"
        networks:
            - "default"
        volumes:
            - ".:/var/www/html"
        extra_hosts: # <--- this is required
            - "host.docker.internal:host-gateway" # <--- this is required
    composer:
        image: "composer:2.5.1"
        volumes:
            - ".:/app"
            - "~/.composer:/tmp"
        command: "composer about"
        networks:
            - "default"
    motocker:
        image: "picadoh/motocker"
        networks:
            - "default"
        ports:
            - "9911:9911"
        environment:
            MOTO_SERVICE: "sns"
            MOTO_HOST: "0.0.0.0"
            MOTO_PORT: "9911"
    elastictranscoder:
        image: "3sidedcube/elasticphanscoder"
        networks:
            - "default"
        ports:
            - "2323:2323"
networks:
    default:
