<?php

namespace App\Validators;

class DraftValidator extends Validator
{
    public const CREATE = [
        "name" => "required|string|between:1,255",
        "type" => "required|string|in:pitch,offer"
    ];

    public const UPDATE_DATA_OFFER = [
        // offer
        "offer" => "present|array|array_object",
        "offer.name" => "present",
        "offer.description" => "present",
        "offer.land_types" => "present|array|array_array",
        "offer.land_types.*" => "present",
        "offer.land_ownerships" => "present|array|array_array",
        "offer.land_ownerships.*" => "present",
        "offer.land_size" => "present",
        "offer.land_continent" => "present",
        "offer.land_country" => "present",
        "offer.restoration_methods" => "present|array|array_array",
        "offer.restoration_methods.*" => "present",
        "offer.restoration_goals" => "present|array|array_array",
        "offer.restoration_goals.*" => "present",
        "offer.funding_sources" => "present|array|array_array",
        "offer.funding_sources.*" => "present",
        "offer.funding_amount" => "present",
        "offer.funding_bracket" => "present",
        "offer.price_per_tree" => "present",
        "offer.long_term_engagement" => "present",
        "offer.reporting_frequency" => "present",
        "offer.reporting_level" => "present",
        "offer.sustainable_development_goals" => "present|array|array_array",
        "offer.sustainable_development_goals.*" => "present",
        "offer.cover_photo" => "present|nullable|integer|exists:uploads,id",
        "offer.video" => "present|nullable|integer|exists:uploads,id",
        // offer document
        "offer_documents" => "present|array|array_array",
        "offer_documents.*" => "array|array_object",
        "offer_documents.*.name" => "present",
        "offer_documents.*.type" => "present",
        "offer_documents.*.document" => "present|nullable|integer|exists:uploads,id",
        // offer contact
        "offer_contacts" => "present|array|array_array",
        "offer_contacts.*" => "array|array_object",
        "offer_contacts.*.team_member_id" => "sometimes|present",
        "offer_contacts.*.user_id" => "sometimes|present"
    ];

    public const UPDATE_DATA_PITCH = [
        // pitch
        "pitch" => "present|array|array_object",
        "pitch.name" => "present",
        "pitch.description" => "present",
        "pitch.land_types" => "present|array|array_array",
        "pitch.land_types.*" => "present",
        "pitch.land_ownerships" => "present|array|array_array",
        "pitch.land_ownerships.*" => "present",
        "pitch.land_size" => "present",
        "pitch.land_continent" => "present",
        "pitch.land_country" => "present",
        "pitch.land_geojson" => "present",
        "pitch.restoration_methods" => "present|array|array_array",
        "pitch.restoration_methods.*" => "present",
        "pitch.restoration_goals" => "present|array|array_array",
        "pitch.restoration_goals.*" => "present",
        "pitch.funding_sources" => "present|array|array_array",
        "pitch.funding_sources.*" => "present",
        "pitch.funding_amount" => "present",
        "pitch.funding_bracket" => "present",
        "pitch.revenue_drivers" => "present|array|array_array",
        "pitch.revenue_drivers.*" => "present",
        "pitch.estimated_timespan" => "present",
        "pitch.long_term_engagement" => "present",
        "pitch.reporting_frequency" => "present",
        "pitch.reporting_level" => "present",
        "pitch.sustainable_development_goals" => "present|array|array_array",
        "pitch.sustainable_development_goals.*" => "present",
        "pitch.cover_photo" => "present|nullable|integer|exists:uploads,id",
        "pitch.video" => "present|nullable|integer|exists:uploads,id",
        "pitch.problem" => "present",
        "pitch.anticipated_outcome" => "present",
        "pitch.who_is_involved" => "present",
        'pitch.local_community_involvement' => "present",
        'pitch.training_involved' => "present",
        'pitch.training_type' => "present",
        'pitch.training_amount_people' => "present",
        'pitch.people_working_in' => "present",
        'pitch.people_amount_nearby' => "present",
        'pitch.people_amount_abroad' => "present",
        'pitch.people_amount_employees' => "present",
        'pitch.people_amount_volunteers' => "present",
        'pitch.benefited_people' => "present",
        'pitch.future_maintenance' => "present",
        'pitch.use_of_resources' => "present",
        // pitch document
        "pitch_documents" => "present|array|array_array",
        "pitch_documents.*" => "array|array_object",
        "pitch_documents.*.name" => "present",
        "pitch_documents.*.type" => "present",
        "pitch_documents.*.document" => "present|nullable|integer|exists:uploads,id",
        // pitch contact
        "pitch_contacts" => "present|array|array_array",
        "pitch_contacts.*" => "array|array_object",
        "pitch_contacts.*.team_member_id" => "sometimes|present",
        "pitch_contacts.*.user_id" => "sometimes|present",
        // carbon certification
        "carbon_certifications" => "present|array|array_array",
        "carbon_certifications.*" => "array|array_object",
        "carbon_certifications.*.type" => "present",
        "carbon_certifications.*.other_value" => "present",
        "carbon_certifications.*.link" => "present",
        // restoration method metric
        "restoration_method_metrics" => "present|array|array_array",
        "restoration_method_metrics.*" => "array|array_object",
        "restoration_method_metrics.*.restoration_method" => "present",
        "restoration_method_metrics.*.experience" => "present",
        "restoration_method_metrics.*.land_size" => "present",
        "restoration_method_metrics.*.price_per_hectare" => "present",
        "restoration_method_metrics.*.biomass_per_hectare" => "present",
        "restoration_method_metrics.*.carbon_impact" => "present",
        "restoration_method_metrics.*.species_impacted" => "present|array|array_array",
        "restoration_method_metrics.*.species_impacted.*" => "present",
        // tree species
        "tree_species" => "present|array|array_array",
        "tree_species.*" => "array|array_object",
        "tree_species.*.name" => "present",
        "tree_species.*.is_native" => "present",
        "tree_species.*.count" => "present",
        "tree_species.*.price_to_plant" => "present",
        "tree_species.*.price_to_maintain" => "present",
        "tree_species.*.saplings" => "present",
        "tree_species.*.site_prep" => "present",
        "tree_species.*.survival_rate" => "present",
        "tree_species.*.produces_food" => "present",
        "tree_species.*.produces_firewood" => "present",
        "tree_species.*.produces_timber" => "present",
        "tree_species.*.owner" => "present",
        "tree_species.*.season" => "present"
    ];
}