<?php

namespace App\Validators;

class OrganisationValidator extends Validator
{
    public const CREATE = [
        'name' => 'required|string|between:1,255',
        'description' => 'required|string|between:1,65535',
        'address_1' => 'required|string|between:1,255',
        'address_2' => 'nullable|string|between:1,255',
        'city' => 'required|string|between:1,255',
        'state' => 'nullable|string|between:1,255',
        'zip_code' => 'nullable|string|between:1,255',
        'country' => 'required|string|country_code',
        'phone_number' => 'required|string|between:1,255',
        'full_time_permanent_employees' => 'numeric|between:0,999999',
        'seasonal_employees' => 'numeric|between:0,999999',
        'part_time_permanent_employees' => 'numeric|between:0,999999',
        'percentage_female' => 'numeric|between:0,100',
        'percentage_youth' => 'numeric|between:0,100',
        'website' => 'nullable|string|soft_url|between:1,255',
        'key_contact' => 'required|string|between:1,255',
        'type' => 'required|string|organisation_type',
        'account_type' => 'string|in:terramatch,ppc,terrafund',
        'category' => 'required|string|organisation_category',
        'facebook' => 'nullable|string|soft_url|starts_with_facebook|between:1,255',
        'twitter' => 'nullable|string|soft_url|starts_with_twitter|between:1,255',
        'linkedin' => 'nullable|string|soft_url|starts_with_linkedin|between:1,255',
        'instagram' => 'nullable|string|soft_url|starts_with_instagram|between:1,255',
        'avatar' => 'nullable|integer|exists:uploads,id',
        'cover_photo' => 'nullable|integer|exists:uploads,id',
        'video' => 'nullable|integer|exists:uploads,id',
        'revenues_19' => 'nullable|numeric|between:0,999999999999.99|regex:/^\d+(\.\d{1,2})?$/',
        'revenues_20' => 'nullable|numeric|between:0,999999999999.99|regex:/^\d+(\.\d{1,2})?$/',
        'revenues_21' => 'nullable|numeric|between:0,999999999999.99|regex:/^\d+(\.\d{1,2})?$/',
        'founded_at' => 'nullable|string|date_format:Y-m-d',
        'community_engagement_strategy' => 'nullable|string|between:1,65535',
        'three_year_community_engagement' => 'nullable|string|between:1,65535',
        'women_farmer_engagement' => 'nullable|integer|min:0|max:100',
        'young_people_engagement' => 'nullable|integer|min:0|max:100',
        'monitoring_and_evaluation_experience' => 'nullable|string|between:1,65535',
        'community_follow_up' => 'nullable|string|between:1,65535',
        'total_hectares_restored' => 'nullable|integer|min:0|max:2147483647',
        'hectares_restored_three_years' => 'nullable|integer|min:0|max:2147483647',
        'total_trees_grown' => 'nullable|integer|min:0|max:2147483647',
        'tree_survival_rate' => 'nullable|integer|min:0|max:100',
        'tree_maintenance_and_aftercare' => 'nullable|string|between:1,65535',
    ];

    public const UPDATE = [
        'name' => 'sometimes|string|between:1,255',
        'description' => 'sometimes|string|between:1,65535',
        'address_1' => 'sometimes|string|between:1,255',
        'address_2' => 'sometimes|nullable|string|between:1,255',
        'city' => 'sometimes|string|between:1,255',
        'state' => 'sometimes|nullable|string|between:1,255',
        'zip_code' => 'sometimes|nullable|string|between:1,255',
        'country' => 'sometimes|string|country_code',
        'phone_number' => 'sometimes|string|between:1,255',
        'full_time_permanent_employees' => 'sometimes|numeric|between:0,999999',
        'seasonal_employees' => 'sometimes|numeric|between:0,999999',
        'part_time_permanent_employees' => 'sometimes|numeric|between:0,999999',
        'percentage_female' => 'sometimes|numeric|between:0,100',
        'percentage_youth' => 'sometimes|numeric|between:0,100',
        'website' => 'sometimes|nullable|string|soft_url|between:1,255',
        'key_contact' => 'sometimes|string|between:1,255',
        'type' => 'sometimes|string|organisation_type',
        'category' => 'sometimes|string|organisation_category',
        'facebook' => 'sometimes|nullable|string|soft_url|starts_with_facebook|between:1,255',
        'twitter' => 'sometimes|nullable|string|soft_url|starts_with_twitter|between:1,255',
        'linkedin' => 'sometimes|nullable|string|soft_url|starts_with_linkedin|between:1,255',
        'instagram' => 'sometimes|nullable|string|soft_url|starts_with_instagram|between:1,255',
        'avatar' => 'sometimes|nullable|integer|exists:uploads,id',
        'cover_photo' => 'sometimes|nullable|integer|exists:uploads,id',
        'video' => 'sometimes|nullable|integer|exists:uploads,id',
        'founded_at' => 'sometimes|nullable|string|date_format:Y-m-d',
        'revenues_19' => "sometimes|nullable|numeric|between:0,99999999.99|regex:/^\d+(\.\d{1,2})?$/",
        'revenues_20' => "sometimes|nullable|numeric|between:0,99999999.99|regex:/^\d+(\.\d{1,2})?$/",
        'revenues_21' => "sometimes|nullable|numeric|between:0,99999999.99|regex:/^\d+(\.\d{1,2})?$/",
        'community_engagement_strategy' => 'sometimes|nullable|string|between:1,65535',
        'three_year_community_engagement' => 'sometimes|nullable|string|between:1,65535',
        'women_farmer_engagement' => 'sometimes|nullable|integer|min:0|max:100',
        'young_people_engagement' => 'sometimes|nullable|integer|min:0|max:100',
        'monitoring_and_evaluation_experience' => 'sometimes|nullable|string|between:1,65535',
        'community_follow_up' => 'sometimes|nullable|string|between:1,65535',
        'total_hectares_restored' => 'sometimes|nullable|integer|min:0|max:2147483647',
        'hectares_restored_three_years' => 'sometimes|nullable|integer|min:0|max:2147483647',
        'total_trees_grown' => 'sometimes|nullable|integer|min:0|max:2147483647',
        'tree_survival_rate' => 'sometimes|nullable|integer|min:0|max:100',
        'tree_maintenance_and_aftercare' => 'sometimes|nullable|string|between:1,65535',
    ];
}
