<?php

namespace App\Validators;

class PitchValidator extends Validator
{
    public $create = [
        "name" => "required|string|between:1,255",
        "description" => "required|string|min:8",
        "land_types" => "required|array",
        "land_types.*" => "distinct|string|land_type",
        "land_ownerships" => "required|array",
        "land_ownerships.*" => "distinct|string|land_ownership",
        "land_size" => "required|string|land_size",
        "land_continent" => "required|string|continent",
        "land_country" => "required|string|country_code",
        "land_geojson" => "required|string|json",
        "restoration_methods" => "required|array",
        "restoration_methods.*" => "distinct|string|restoration_method",
        "restoration_goals" => "required|array",
        "restoration_goals.*" => "distinct|string|restoration_goal",
        "funding_sources" => "required|array",
        "funding_sources.*" => "distinct|string|funding_source",
        "funding_amount" => "required|integer|min:1",
        "revenue_drivers" => "required|array",
        "revenue_drivers.*" => "distinct|string|revenue_driver",
        "estimated_timespan" => "required|integer|min:1",
        "long_term_engagement" => "present|nullable|boolean",
        "reporting_frequency" => "required|string|reporting_frequency",
        "reporting_level" => "required|string|reporting_level",
        "sustainable_development_goals" => "required|array",
        "sustainable_development_goals.*" => "distinct|string|sustainable_development_goal",
        "avatar" => "present|nullable|integer|exists:uploads,id",
        "cover_photo" => "present|nullable|integer|exists:uploads,id",
        "video" => "present|nullable|integer|exists:uploads,id",
        "problem" => "required|string|min:8",
        "anticipated_outcome" => "required|string|min:8",
        "who_is_involved" => "required|string|min:8",
        'local_community_involvement' => "required|boolean",
        'training_involved' => "required|boolean",
        'training_type'  => "sometimes|required|string",
        'training_amount_people' => "sometimes|required|integer",
        'people_working_in' => "required|string",
        'people_amount_nearby' => "required|integer",
        'people_amount_abroad' => "required|integer",
        'people_amount_employees' => "required|integer",
        'people_amount_volunteers' => "required|integer",
        'benefited_people' => "required|integer",
        'future_maintenance' => "required|string",
        'use_of_resources' => "required|string",
        "facebook" => "sometimes|nullable|string|soft_url|starts_with_facebook|between:1,255",
        "twitter" => "sometimes|nullable|string|soft_url|starts_with_twitter|between:1,255",
        "instagram" => "sometimes|nullable|string|soft_url|starts_with_instagram|between:1,255",
    ];

    public $update = [
        "name" => "sometimes|required|string|between:1,255",
        "description" => "sometimes|required|string|min:8",
        "land_types" => "sometimes|required|array",
        "land_types.*" => "sometimes|distinct|string|land_type",
        "land_ownerships" => "sometimes|required|array",
        "land_ownerships.*" => "distinct|string|land_ownership",
        "land_size" => "sometimes|required|string|land_size",
        "land_continent" => "sometimes|required|string|continent",
        "land_country" => "sometimes|required|string|country_code",
        "land_geojson" => "sometimes|required|string|json",
        "restoration_methods" => "sometimes|required|array",
        "restoration_methods.*" => "distinct|string|restoration_method",
        "restoration_goals" => "sometimes|required|array",
        "restoration_goals.*" => "distinct|string|restoration_goal",
        "funding_sources" => "sometimes|required|array",
        "funding_sources.*" => "distinct|string|funding_source",
        "funding_amount" => "sometimes|required|integer|min:1",
        "revenue_drivers" => "sometimes|required|array",
        "revenue_drivers.*" => "distinct|string|revenue_driver",
        "estimated_timespan" => "sometimes|required|integer|min:1",
        "long_term_engagement" => "sometimes|present|nullable|boolean",
        "reporting_frequency" => "sometimes|required|string|reporting_frequency",
        "reporting_level" => "sometimes|required|string|reporting_level",
        "sustainable_development_goals" => "sometimes|required|array",
        "sustainable_development_goals.*" => "distinct|string|sustainable_development_goal",
        "avatar" => "sometimes|present|nullable|integer|exists:uploads,id",
        "cover_photo" => "sometimes|present|nullable|integer|exists:uploads,id",
        "video" => "sometimes|present|nullable|integer|exists:uploads,id",
        "problem" => "sometimes|required|string|min:8",
        "anticipated_outcome" => "sometimes|required|string|min:8",
        "who_is_involved" => "sometimes|required|string|min:8",
        'local_community_involvement' => "sometimes|required|boolean",
        'training_involved' => "sometimes|required|boolean",
        'training_type'  => "sometimes|required|string",
        'training_amount_people' => "sometimes|required|integer",
        'people_working_in' => "sometimes|required|string",
        'people_amount_nearby' => "sometimes|required|integer",
        'people_amount_abroad' => "sometimes|required|integer",
        'people_amount_employees' => "sometimes|required|integer",
        'people_amount_volunteers' => "sometimes|required|integer",
        'benefited_people' => "sometimes|required|integer",
        'future_maintenance' => "sometimes|required|string",
        'use_of_resources' => "sometimes|required|string",
        "facebook" => "sometimes|nullable|string|soft_url|starts_with_facebook|between:1,255",
        "twitter" => "sometimes|nullable|string|soft_url|starts_with_twitter|between:1,255",
        "instagram" => "sometimes|nullable|string|soft_url|starts_with_instagram|between:1,255",
    ];

    public $complete = [
        "successful" => "required|boolean"
    ];
}
