<?php

namespace App\Validators;

class PitchValidator extends Validator
{
    public const CREATE = [
        "name" => "required|string|between:1,255",
        "description" => "required|string|between:1,65535",
        "land_types" => "required|array|array_array",
        "land_types.*" => "distinct|string|land_type",
        "land_ownerships" => "required|array|array_array",
        "land_ownerships.*" => "distinct|string|land_ownership",
        "land_size" => "required|string|land_size",
        "land_continent" => "required|string|continent",
        "land_country" => "required|string|country_code",
        "land_geojson" => "required|string|json|geo_json|between:1,65535",
        "restoration_methods" => "required|array|array_array",
        "restoration_methods.*" => "distinct|string|restoration_method",
        "restoration_goals" => "required|array|array_array",
        "restoration_goals.*" => "distinct|string|restoration_goal",
        "funding_sources" => "required|array|array_array",
        "funding_sources.*" => "distinct|string|funding_source",
        "funding_amount" => "required|integer|between:1,2147483647",
        "funding_bracket" => "required|string|funding_bracket",
        "revenue_drivers" => "present|array|array_array",
        "revenue_drivers.*" => "distinct|string|revenue_driver",
        "estimated_timespan" => "required|integer|between:1,2147483647",
        "long_term_engagement" => "present|nullable|boolean",
        "reporting_frequency" => "required|string|reporting_frequency",
        "reporting_level" => "required|string|reporting_level",
        "sustainable_development_goals" => "present|array|array_array",
        "sustainable_development_goals.*" => "distinct|string|sustainable_development_goal",
        "cover_photo" => "present|nullable|integer|exists:uploads,id",
        "video" => "present|nullable|integer|exists:uploads,id",
        "problem" => "required|string|between:1,65535",
        "anticipated_outcome" => "required|string|between:1,65535",
        "who_is_involved" => "required|string|between:1,65535",
        'local_community_involvement' => "present|nullable|boolean",
        'training_involved' => "required|boolean",
        'training_type' => "present|nullable|string|between:1,65535",
        'training_amount_people' => "present|nullable|integer|between:0,2147483647",
        'people_working_in' => "required|string|between:1,65535",
        'people_amount_nearby' => "required|integer|between:0,2147483647",
        'people_amount_abroad' => "required|integer|between:0,2147483647",
        'people_amount_employees' => "required|integer|between:0,2147483647",
        'people_amount_volunteers' => "required|integer|between:0,2147483647",
        'benefited_people' => "required|integer|between:0,2147483647",
        'future_maintenance' => "required|string|between:1,65535",
        'use_of_resources' => "required|string|between:1,65535"
    ];

    public const UPDATE = [
        "name" => "sometimes|required|string|between:1,255",
        "description" => "sometimes|required|string|between:1,65535",
        "land_types" => "sometimes|required|array|array_array",
        "land_types.*" => "distinct|string|land_type",
        "land_ownerships" => "sometimes|required|array|array_array",
        "land_ownerships.*" => "distinct|string|land_ownership",
        "land_size" => "sometimes|required|string|land_size",
        "land_continent" => "sometimes|required|string|continent",
        "land_country" => "sometimes|required|string|country_code",
        "land_geojson" => "sometimes|required|string|json|geo_json|between:1,65535",
        "restoration_methods" => "sometimes|required|array|array_array",
        "restoration_methods.*" => "distinct|string|restoration_method",
        "restoration_goals" => "sometimes|required|array|array_array",
        "restoration_goals.*" => "distinct|string|restoration_goal",
        "funding_sources" => "sometimes|required|array|array_array",
        "funding_sources.*" => "distinct|string|funding_source",
        "funding_amount" => "sometimes|required|integer|between:1,2147483647",
        "funding_bracket" => "sometimes|required|string|funding_bracket",
        "revenue_drivers" => "sometimes|present|array|array_array",
        "revenue_drivers.*" => "distinct|string|revenue_driver",
        "estimated_timespan" => "sometimes|required|integer|between:1,2147483647",
        "long_term_engagement" => "sometimes|present|nullable|boolean",
        "reporting_frequency" => "sometimes|required|string|reporting_frequency",
        "reporting_level" => "sometimes|required|string|reporting_level",
        "sustainable_development_goals" => "sometimes|present|array|array_array",
        "sustainable_development_goals.*" => "distinct|string|sustainable_development_goal",
        "cover_photo" => "sometimes|present|nullable|integer|exists:uploads,id",
        "video" => "sometimes|present|nullable|integer|exists:uploads,id",
        "problem" => "sometimes|required|string|between:1,65535",
        "anticipated_outcome" => "sometimes|required|string|between:1,65535",
        "who_is_involved" => "sometimes|required|string|between:1,65535",
        'local_community_involvement' => "sometimes|present|nullable|boolean",
        'training_involved' => "sometimes|required|boolean",
        'training_type' => "sometimes|present|nullable|string|between:1,65535",
        'training_amount_people' => "sometimes|present|nullable|integer|between:0,2147483647",
        'people_working_in' => "sometimes|required|string|between:1,65535",
        'people_amount_nearby' => "sometimes|required|integer|between:0,2147483647",
        'people_amount_abroad' => "sometimes|required|integer|between:0,2147483647",
        'people_amount_employees' => "sometimes|required|integer|between:0,2147483647",
        'people_amount_volunteers' => "sometimes|required|integer|between:0,2147483647",
        'benefited_people' => "sometimes|required|integer|between:0,2147483647",
        'future_maintenance' => "sometimes|required|string|between:1,65535",
        'use_of_resources' => "sometimes|required|string|between:1,65535"
    ];

    public const UPDATE_VISIBILITY = [
        "visibility" => "required|string|visibility"
    ];
}
