summary: Get a specific task by ID
operationId: get-v2-tasks-id
tags:
  - V2 Tasks
produces:
  - application/json
parameters:
  - type: integer
    name: ID
    in: path
    required: true
responses:
  '200':
    description: OK
    content:
      application/json:
        schema:
          title: V2TaskReadUuid
          type: object
          properties:
            uuid:
              type: string