summary: Get the reports/actions via a task
operationId: get-v2-tasks-uuid-reports
tags:
  - V2 Projects
  - V2 Tasks
description: "Available Sort : period_key (year-month) and status"
produces:
  - application/json
parameters:
  - type: string
    name: UUID
    in: path
    required: true
responses:
  '200':
    description: OK
    schema:
      type: object
      properties:
        data:
          type: array
          items:
              $ref: '../../definitions/_index.yml#/V2TaskActionRead'