<?php

return [

    "countries" => [
        "Afghanistan" => "AF",
        "Åland Islands" => "AX",
        "Albania" => "AL",
        "Algeria" => "DZ",
        "American Samoa" => "AS",
        "Andorra" => "AD",
        "Angola" => "AO",
        "Anguilla" => "AI",
        // "Antarctica" => "AQ",
        "Antigua and Barbuda" => "AG",
        "Argentina" => "AR",
        "Armenia" => "AM",
        "Aruba" => "AW",
        "Australia" => "AU",
        "Austria" => "AT",
        "Azerbaijan" => "AZ",
        "Bahamas (the)" => "BS",
        "Bahrain" => "BH",
        "Bangladesh" => "BD",
        "Barbados" => "BB",
        "Belarus" => "BY",
        "Belgium" => "BE",
        "Belize" => "BZ",
        "Benin" => "BJ",
        "Bermuda" => "BM",
        "Bhutan" => "BT",
        "Bolivia (Plurinational State of)" => "BO",
        "Bonaire, Sint Eustatius and Saba" => "BQ",
        "Bosnia and Herzegovina" => "BA",
        "Botswana" => "BW",
        // "Bouvet Island" => "BV",
        "Brazil" => "BR",
        "British Indian Ocean Territory (the)" => "IO",
        "Brunei Darussalam" => "BN",
        "Bulgaria" => "BG",
        "Burkina Faso" => "BF",
        "Burundi" => "BI",
        "Cabo Verde" => "CV",
        "Cambodia" => "KH",
        "Cameroon" => "CM",
        "Canada" => "CA",
        "Cayman Islands (the)" => "KY",
        "Central African Republic (the)" => "CF",
        "Chad" => "TD",
        "Chile" => "CL",
        "China" => "CN",
        "Christmas Island" => "CX",
        "Cocos (Keeling) Islands (the)" => "CC",
        "Colombia" => "CO",
        "Comoros (the)" => "KM",
        "Congo (the Democratic Republic of the)" => "CD",
        "Congo (the)" => "CG",
        "Cook Islands (the)" => "CK",
        "Costa Rica" => "CR",
        "Croatia" => "HR",
        "Cuba" => "CU",
        "Curaçao" => "CW",
        "Cyprus" => "CY",
        "Czechia" => "CZ",
        "Côte d'Ivoire" => "CI",
        "Denmark" => "DK",
        "Djibouti" => "DJ",
        "Dominica" => "DM",
        "Dominican Republic (the)" => "DO",
        "Ecuador" => "EC",
        "Egypt" => "EG",
        "El Salvador" => "SV",
        "Equatorial Guinea" => "GQ",
        "Eritrea" => "ER",
        "Estonia" => "EE",
        "Eswatini" => "SZ",
        "Ethiopia" => "ET",
        "Falkland Islands (the)" => "FK",
        "Faroe Islands (the)" => "FO",
        "Fiji" => "FJ",
        "Finland" => "FI",
        "France" => "FR",
        "French Guiana" => "GF",
        "French Polynesia" => "PF",
        // "French Southern Territories (the)" => "TF",
        "Gabon" => "GA",
        "Gambia (the)" => "GM",
        "Georgia" => "GE",
        "Germany" => "DE",
        "Ghana" => "GH",
        "Gibraltar" => "GI",
        "Greece" => "GR",
        "Greenland" => "GL",
        "Grenada" => "GD",
        "Guadeloupe" => "GP",
        "Guam" => "GU",
        "Guatemala" => "GT",
        "Guernsey" => "GG",
        "Guinea" => "GN",
        "Guinea-Bissau" => "GW",
        "Guyana" => "GY",
        "Haiti" => "HT",
        // "Heard Island and McDonald Islands" => "HM",
        "Holy See (the)" => "VA",
        "Honduras" => "HN",
        "Hong Kong" => "HK",
        "Hungary" => "HU",
        "Iceland" => "IS",
        "India" => "IN",
        "Indonesia" => "ID",
        "Iran (Islamic Republic of)" => "IR",
        "Iraq" => "IQ",
        "Ireland" => "IE",
        "Isle of Man" => "IM",
        "Israel" => "IL",
        "Italy" => "IT",
        "Jamaica" => "JM",
        "Japan" => "JP",
        "Jersey" => "JE",
        "Jordan" => "JO",
        "Kazakhstan" => "KZ",
        "Kenya" => "KE",
        "Kiribati" => "KI",
        "Korea (the Democratic People's Republic of)" => "KP",
        "Korea (the Republic of)" => "KR",
        "Kuwait" => "KW",
        "Kyrgyzstan" => "KG",
        "Lao People's Democratic Republic (the)" => "LA",
        "Latvia" => "LV",
        "Lebanon" => "LB",
        "Lesotho" => "LS",
        "Liberia" => "LR",
        "Libya" => "LY",
        "Liechtenstein" => "LI",
        "Lithuania" => "LT",
        "Luxembourg" => "LU",
        "Macao" => "MO",
        "Madagascar" => "MG",
        "Malawi" => "MW",
        "Malaysia" => "MY",
        "Maldives" => "MV",
        "Mali" => "ML",
        "Malta" => "MT",
        "Marshall Islands (the)" => "MH",
        "Martinique" => "MQ",
        "Mauritania" => "MR",
        "Mauritius" => "MU",
        "Mayotte" => "YT",
        "Mexico" => "MX",
        "Micronesia (Federated States of)" => "FM",
        "Moldova (the Republic of)" => "MD",
        "Monaco" => "MC",
        "Mongolia" => "MN",
        "Montenegro" => "ME",
        "Montserrat" => "MS",
        "Morocco" => "MA",
        "Mozambique" => "MZ",
        "Myanmar" => "MM",
        "Namibia" => "NA",
        "Nauru" => "NR",
        "Nepal" => "NP",
        "Netherlands (the)" => "NL",
        "New Caledonia" => "NC",
        "New Zealand" => "NZ",
        "Nicaragua" => "NI",
        "Niger (the)" => "NE",
        "Nigeria" => "NG",
        "Niue" => "NU",
        "Norfolk Island" => "NF",
        "North Macedonia" => "MK",
        "Northern Mariana Islands (the)" => "MP",
        "Norway" => "NO",
        "Oman" => "OM",
        "Pakistan" => "PK",
        "Palau" => "PW",
        "Palestine, State of" => "PS",
        "Panama" => "PA",
        "Papua New Guinea" => "PG",
        "Paraguay" => "PY",
        "Peru" => "PE",
        "Philippines (the)" => "PH",
        "Pitcairn" => "PN",
        "Poland" => "PL",
        "Portugal" => "PT",
        "Puerto Rico" => "PR",
        "Qatar" => "QA",
        "Romania" => "RO",
        "Russian Federation (the)" => "RU",
        "Rwanda" => "RW",
        "Réunion" => "RE",
        "Saint Barthélemy" => "BL",
        "Saint Helena, Ascension and Tristan da Cunha" => "SH",
        "Saint Kitts and Nevis" => "KN",
        "Saint Lucia" => "LC",
        "Saint Martin (French part)" => "MF",
        "Saint Pierre and Miquelon" => "PM",
        "Saint Vincent and the Grenadines" => "VC",
        "Samoa" => "WS",
        "San Marino" => "SM",
        "Sao Tome and Principe" => "ST",
        "Saudi Arabia" => "SA",
        "Senegal" => "SN",
        "Serbia" => "RS",
        "Seychelles" => "SC",
        "Sierra Leone" => "SL",
        "Singapore" => "SG",
        "Sint Maarten (Dutch part)" => "SX",
        "Slovakia" => "SK",
        "Slovenia" => "SI",
        "Solomon Islands" => "SB",
        "Somalia" => "SO",
        "South Africa" => "ZA",
        // "South Georgia and the South Sandwich Islands" => "GS",
        "South Sudan" => "SS",
        "Spain" => "ES",
        "Sri Lanka" => "LK",
        "Sudan (the)" => "SD",
        "Suriname" => "SR",
        "Svalbard and Jan Mayen" => "SJ",
        "Sweden" => "SE",
        "Switzerland" => "CH",
        "Syrian Arab Republic (the)" => "SY",
        "Taiwan (Province of China)" => "TW",
        "Tajikistan" => "TJ",
        "Tanzania, the United Republic of" => "TZ",
        "Thailand" => "TH",
        "Timor-Leste" => "TL",
        "Togo" => "TG",
        "Tokelau" => "TK",
        "Tonga" => "TO",
        "Trinidad and Tobago" => "TT",
        "Tunisia" => "TN",
        "Turkey" => "TR",
        "Turkmenistan" => "TM",
        "Turks and Caicos Islands (the)" => "TC",
        "Tuvalu" => "TV",
        "Uganda" => "UG",
        "Ukraine" => "UA",
        "United Arab Emirates (the)" => "AE",
        "United Kingdom of Great Britain and Northern Ireland (the)" => "GB",
        "United States Minor Outlying Islands (the)" => "UM",
        "United States of America (the)" => "US",
        "Uruguay" => "UY",
        "Uzbekistan" => "UZ",
        "Vanuatu" => "VU",
        "Venezuela (Bolivarian Republic of)" => "VE",
        "Viet Nam" => "VN",
        "Virgin Islands (British)" => "VG",
        "Virgin Islands (U.S.)" => "VI",
        "Wallis and Futuna" => "WF",
        "Western Sahara" => "EH",
        "Yemen" => "YE",
        "Zambia" => "ZM",
        "Zimbabwe" => "ZW"
    ],

    'languages' => [
        'English' => 'en',
        'French' => 'fr',
        'Spanish' => 'es',
        'Portugese' => 'pt',
    ],

    "organisation_types" => [
        "B Corporation" => "b_corporation",
        "Corporation" => "corporation",
        "Foundation" => "foundation",
        "Government" => "government",
        "International NGO" => "international_ngo",
        "LLC" => "llc",
        "NGO" => "ngo",
        "Non-profit" => "nonprofit",
        "Other" => "other"
    ],

    "organisation_categories" => [
        "Developer" => "developer",
        "Funder" => "funder",
        "Both" => "both"
    ],

    "document_types" => [
        "Award" => "award",
        "Legal" => "legal",
        "Technical" => "technical",
        "Other" => "other"
    ],

    "land_types" => [
        "Bare Land" => "bare_land",
        "Cropland" => "cropland",
        "Forest" => "forest",
        // "Grassland" => "grassland",
        "Industrial Land" => "industrial_land",
        "Mangrove" => "mangrove",
        "Peatland" => "peatland",
        "Settlement" => "settlement",
        "Shrubland" => "shrubland",
        "Wetland" => "wetland"
    ],

    "land_ownerships" => [
        "Community" => "community",
        "National Park/Reserve" => "national_park_reserve",
        "Private" => "private",
        "Public" => "public"
    ],

    "restoration_methods" => [
        "Agroforestry, terraces" => "agroforestry",
        // "Ecological restoration" => "ecological",
        "Managed natural regeneration" => "assisted_natural",
        "Mangrove restoration" => "mangrove",
        "Reforestation" => "reforestation",
        // "Reserve Corridors or Enclosures/Exclosures" => "reserve_corridors",
        "Riparian buffers" => "riparian_buffers",
        // "Sustainable land management" => "sustainable_land_management"
    ],

    "restoration_goals" => [
        "Biodiversity" => "biodiversity",
        "Climate" => "climate",
        "Ecotourism" => "ecotourism",
        "Energy" => "energy",
        "Food, Agriculture and Commodities" => "agriculture_and_commodities",
        "Forests" => "forests",
        "Livelihoods" => "livelihoods",
        "National and International Goals" => "national_and_international",
        "Soil" => "soil",
        "Water" => "water"
    ],

    "funding_sources" => [
        "Equity Investment" => "equity_investment",
        "Grant With Limited Reporting" => "grant_with_limited_reporting",
        "Grant With Reporting" => "grant_with_reporting",
        "Loan/Debt Financing" => "loan_debt"
    ],

    "sustainable_development_goals" => [
        "Goal 1: No Poverty" => "goal_1",
        "Goal 2: Zero Hunger" => "goal_2",
        "Goal 3: Good Health and Well-Being" => "goal_3",
        "Goal 4: Quality Education" => "goal_4",
        "Goal 5: Gender Equality" => "goal_5",
        "Goal 6: Clean Water and Sanitation" => "goal_6",
        "Goal 7: Affordable and Clean Energy" => "goal_7",
        "Goal 8: Decent Work and Economic Growth" => "goal_8",
        "Goal 9: Industry, Innovation, and Infrastructure" => "goal_9",
        "Goal 10: Reduced Inequalities" => "goal_10",
        "Goal 11: Sustainable Cities and Communities" => "goal_11",
        "Goal 12: Responsible Consumption and Production" => "goal_12",
        "Goal 13: Climate Action" => "goal_13",
        "Goal 14: Life Below Water" => "goal_14",
        "Goal 15: Life on Land" => "goal_15",
        "Goal 16: Peace, Justice, and Strong Institutions" => "goal_16",
        "Goal 17: Partnerships" => "goal_17"
    ],

    "continents" => [
        "Africa" => "africa",
        // "Antarctica" => "antarctica",
        "Asia" => "asia",
        "Australia" => "australia",
        "Europe" => "europe",
        "North America" => "north_america",
        "South America" => "south_america"
    ],

    "continents_countries" => [
        "africa" => [
            "Algeria" => "DZ",
            "Angola" => "AO",
            "Benin" => "BJ",
            "Botswana" => "BW",
            "Burkina Faso" => "BF",
            "Burundi" => "BI",
            "Cabo Verde" => "CV",
            "Cameroon" => "CM",
            "Central African Republic (the)" => "CF",
            "Chad" => "TD",
            "Comoros (the)" => "KM",
            "Congo (the Democratic Republic of the)" => "CD",
            "Congo (the)" => "CG",
            "Côte d'Ivoire" => "CI",
            "Djibouti" => "DJ",
            "Egypt" => "EG",
            "Equatorial Guinea" => "GQ",
            "Eritrea" => "ER",
            "Eswatini" => "SZ",
            "Ethiopia" => "ET",
            "Gabon" => "GA",
            "Gambia (the)" => "GM",
            "Ghana" => "GH",
            "Guinea" => "GN",
            "Guinea-Bissau" => "GW",
            "Kenya" => "KE",
            "Lesotho" => "LS",
            "Liberia" => "LR",
            "Libya" => "LY",
            "Madagascar" => "MG",
            "Malawi" => "MW",
            "Mali" => "ML",
            "Mauritania" => "MR",
            "Mauritius" => "MU",
            "Mayotte" => "YT",
            "Morocco" => "MA",
            "Mozambique" => "MZ",
            "Namibia" => "NA",
            "Niger (the)" => "NE",
            "Nigeria" => "NG",
            "Rwanda" => "RW",
            "Réunion" => "RE",
            "Saint Helena, Ascension and Tristan da Cunha" => "SH",
            "Sao Tome and Principe" => "ST",
            "Senegal" => "SN",
            "Seychelles" => "SC",
            "Sierra Leone" => "SL",
            "Somalia" => "SO",
            "South Africa" => "ZA",
            "South Sudan" => "SS",
            "Sudan (the)" => "SD",
            "Tanzania, the United Republic of" => "TZ",
            "Togo" => "TG",
            "Tunisia" => "TN",
            "Uganda" => "UG",
            "Western Sahara" => "EH",
            "Zambia" => "ZM",
            "Zimbabwe" => "ZW",
        ],
        // "antarctica" => [
            // "Antarctica" => "AQ",
            // "Bouvet Island" => "BV",
            // "French Southern Territories (the)" => "TF",
            // "Heard Island and McDonald Islands" => "HM",
            // "South Georgia and the South Sandwich Islands" => "GS",
        // ],
        "asia" => [
            "Afghanistan" => "AF",
            "Bahrain" => "BH",
            "Bangladesh" => "BD",
            "Bhutan" => "BT",
            "British Indian Ocean Territory (the)" => "IO",
            "Brunei Darussalam" => "BN",
            "Cambodia" => "KH",
            "China" => "CN",
            "Christmas Island" => "CX",
            "Cocos (Keeling) Islands (the)" => "CC",
            "Hong Kong" => "HK",
            "India" => "IN",
            "Indonesia" => "ID",
            "Iran (Islamic Republic of)" => "IR",
            "Iraq" => "IQ",
            "Israel" => "IL",
            "Japan" => "JP",
            "Jordan" => "JO",
            "Korea (the Democratic People's Republic of)" => "KP",
            "Korea (the Republic of)" => "KR",
            "Kuwait" => "KW",
            "Kyrgyzstan" => "KG",
            "Lao People's Democratic Republic (the)" => "LA",
            "Lebanon" => "LB",
            "Macao" => "MO",
            "Malaysia" => "MY",
            "Maldives" => "MV",
            "Mongolia" => "MN",
            "Myanmar" => "MM",
            "Nepal" => "NP",
            "Oman" => "OM",
            "Pakistan" => "PK",
            "Palestine, State of" => "PS",
            "Philippines (the)" => "PH",
            "Qatar" => "QA",
            "Saudi Arabia" => "SA",
            "Singapore" => "SG",
            "Sri Lanka" => "LK",
            "Syrian Arab Republic (the)" => "SY",
            "Taiwan (Province of China)" => "TW",
            "Tajikistan" => "TJ",
            "Thailand" => "TH",
            "Timor-Leste" => "TL",
            "Turkmenistan" => "TM",
            "United Arab Emirates (the)" => "AE",
            "Uzbekistan" => "UZ",
            "Viet Nam" => "VN",
            "Yemen" => "YE",
        ],
        "australia" => [
            "American Samoa" => "AS",
            "Australia" => "AU",
            "Cook Islands (the)" => "CK",
            "Fiji" => "FJ",
            "French Polynesia" => "PF",
            "Guam" => "GU",
            "Kiribati" => "KI",
            "Marshall Islands (the)" => "MH",
            "Micronesia (Federated States of)" => "FM",
            "Nauru" => "NR",
            "New Caledonia" => "NC",
            "New Zealand" => "NZ",
            "Niue" => "NU",
            "Norfolk Island" => "NF",
            "Northern Mariana Islands (the)" => "MP",
            "Palau" => "PW",
            "Papua New Guinea" => "PG",
            "Pitcairn" => "PN",
            "Samoa" => "WS",
            "Solomon Islands" => "SB",
            "Tokelau" => "TK",
            "Tonga" => "TO",
            "Tuvalu" => "TV",
            "United States Minor Outlying Islands (the)" => "UM",
            "Vanuatu" => "VU",
            "Wallis and Futuna" => "WF",
        ],
        "europe" => [
            "Åland Islands" => "AX",
            "Albania" => "AL",
            "Andorra" => "AD",
            "Armenia" => "AM",
            "Austria" => "AT",
            "Azerbaijan" => "AZ",
            "Belarus" => "BY",
            "Belgium" => "BE",
            "Bosnia and Herzegovina" => "BA",
            "Bulgaria" => "BG",
            "Croatia" => "HR",
            "Cyprus" => "CY",
            "Czechia" => "CZ",
            "Denmark" => "DK",
            "Estonia" => "EE",
            "Faroe Islands (the)" => "FO",
            "Finland" => "FI",
            "France" => "FR",
            "Georgia" => "GE",
            "Germany" => "DE",
            "Gibraltar" => "GI",
            "Greece" => "GR",
            "Guernsey" => "GG",
            "Holy See (the)" => "VA",
            "Hungary" => "HU",
            "Iceland" => "IS",
            "Ireland" => "IE",
            "Isle of Man" => "IM",
            "Italy" => "IT",
            "Jersey" => "JE",
            "Kazakhstan" => "KZ",
            "Latvia" => "LV",
            "Liechtenstein" => "LI",
            "Lithuania" => "LT",
            "Luxembourg" => "LU",
            "Malta" => "MT",
            "Moldova (the Republic of)" => "MD",
            "Monaco" => "MC",
            "Montenegro" => "ME",
            "Netherlands (the)" => "NL",
            "North Macedonia" => "MK",
            "Norway" => "NO",
            "Poland" => "PL",
            "Portugal" => "PT",
            "Romania" => "RO",
            "Russian Federation (the)" => "RU",
            "San Marino" => "SM",
            "Serbia" => "RS",
            "Slovakia" => "SK",
            "Slovenia" => "SI",
            "Spain" => "ES",
            "Svalbard and Jan Mayen" => "SJ",
            "Sweden" => "SE",
            "Switzerland" => "CH",
            "Turkey" => "TR",
            "Ukraine" => "UA",
            "United Kingdom of Great Britain and Northern Ireland (the)" => "GB",
        ],
        "north_america" => [
            "Anguilla" => "AI",
            "Antigua and Barbuda" => "AG",
            "Aruba" => "AW",
            "Bahamas (the)" => "BS",
            "Barbados" => "BB",
            "Belize" => "BZ",
            "Bermuda" => "BM",
            "Bonaire, Sint Eustatius and Saba" => "BQ",
            "Canada" => "CA",
            "Cayman Islands (the)" => "KY",
            "Costa Rica" => "CR",
            "Cuba" => "CU",
            "Curaçao" => "CW",
            "Dominica" => "DM",
            "Dominican Republic (the)" => "DO",
            "El Salvador" => "SV",
            "Greenland" => "GL",
            "Grenada" => "GD",
            "Guadeloupe" => "GP",
            "Guatemala" => "GT",
            "Haiti" => "HT",
            "Honduras" => "HN",
            "Jamaica" => "JM",
            "Martinique" => "MQ",
            "Mexico" => "MX",
            "Montserrat" => "MS",
            "Nicaragua" => "NI",
            "Panama" => "PA",
            "Puerto Rico" => "PR",
            "Saint Barthélemy" => "BL",
            "Saint Kitts and Nevis" => "KN",
            "Saint Lucia" => "LC",
            "Saint Martin (French part)" => "MF",
            "Saint Pierre and Miquelon" => "PM",
            "Saint Vincent and the Grenadines" => "VC",
            "Sint Maarten (Dutch part)" => "SX",
            "Trinidad and Tobago" => "TT",
            "Turks and Caicos Islands (the)" => "TC",
            "United States of America (the)" => "US",
            "Virgin Islands (British)" => "VG",
            "Virgin Islands (U.S.)" => "VI",
        ],
        "south_america" => [
            "Argentina" => "AR",
            "Bolivia (Plurinational State of)" => "BO",
            "Brazil" => "BR",
            "Chile" => "CL",
            "Colombia" => "CO",
            "Ecuador" => "EC",
            "Falkland Islands (the)" => "FK",
            "French Guiana" => "GF",
            "Guyana" => "GY",
            "Paraguay" => "PY",
            "Peru" => "PE",
            "Suriname" => "SR",
            "Uruguay" => "UY",
            "Venezuela (Bolivarian Republic of)" => "VE",
        ]
    ],

    "reporting_frequencies" => [
        "Greater Than Quarterly" => "gt_quarterly",
        "Quarterly" => "quarterly",
        "Bi-Annually" => "bi_annually",
        "Annually" => "annually",
        "Less Than Annually" => "lt_annually"
    ],

    "reporting_levels" => [
        "High" => "high",
        "Medium" => "medium",
        "Low" => "low"
    ],

    "revenue_drivers" => [
        "Carbon Credits" => "carbon_credits",
        "Fruits" => "fruits",
        "Pulp and Paper Products" => "pulp_and_paper",
        "Vegetables" => "vegetables"
    ],

    "carbon_certification_types" => [
        "FSC" => "fsc",
        "Gold Standard" => "gold_standard",
        "Plan Vivo" => "plan_vivo",
        "Verified Carbon Standard" => "verified_carbon_standard",
        "Other" => "other"
    ],

    "land_sizes" => [
        "< 10" => "lt_10",
        "10 - 100" => "10_to_100",
        "> 100" => "gt_100"
    ],

    "rejected_reasons" => [
        "Cannot Verify Information" => "cannot_verify",
        "Does Not Meet Requirements" => "does_not_meet_requirements",
        "Follow Up Information Required" => "follow_up_required",
        "Not Enough Information" => "not_enough_information",
        "Unrelated Sector" => "unrelated_sector",
        "Other" => "other"
    ],

    "funding_brackets" => [
        "< $50,000" => "lt_50k",
        "$50,000 - $250,000" => "50k_to_250k",
        "$250,000 to $1,000,000" => "250k_to_1m",
        "> $1,000,000" => "gt_1m"
    ],

    "visibilities" => [
        "Archived" => "archived", // unsuccessfully completed
        "Still Looking" => "looking",
        "Talking" => "talking",
        "Entering Contracts" => "entering_contracts",
        "Partially Invested/Funded" => "partially_invested_funded",
        "Fully Invested/Funded" => "fully_invested_funded", // successfully completed
        /**
         * This comment removes the finished visibility from MOB and FED. As far as
         * this codebase is concerned "finished" is a valid visibility, but because
         * it's not shown in the UI no one is using it.
         *
         * The visibility was created to handle projects which had been
         * "fully_invested_funded" (AKA successfully completed) but are no longer to
         * be publicly shown against an organisation.
         *
         * You could do this with the "archived" visibility, but then there is no way
         * of distinguishing between projects which are "archived" due to success or
         * failure. That difference is something which is important in reports!
         */
        // "Finished" => "finished"
    ],

    "organisation_file_types" => [
        "Financial Statement" => 'financial_statement',
        "Profit & Loss Statement" => 'profit_loss_statement',
        "Bank Statement" => 'bank_statement',
        "Letter of Reference" => 'letter_of_reference',
    ],

    "terrafund" => [
        "programme" => [
            "type" => [
                "Multiple Sites" => "multiple_sites",
                "One Contiguous Area" => "one_contiguous_area",
            ],
            "status" => [
                "New Project" => "new_project",
                "Existing Expansion" => "existing_expansion",
            ],
        ],
        "nursery" => [
            "type" => [
                "Managing" => "managing",
                "Building" => "building",
                "Expanding" => "expanding",
            ]
        ],
        "site" => [
            "restoration_methods" => [
                "Mangrove Tree Restoration" => "mangrove_tree_restoration",
                "Assisted Natural Regeneration" => "assisted_natural_regeneration",
                "Agroforestry" => "agroforestry",
                "Plantations" => "plantations",
                "Wetland / Riparian" => "wetland_riparian",
                "Enrichment Planting" => "enrichment_planting",
                "Applied Nucleation / Tree Island" => "applied_nucleation_tree_island",
                "Silvopasture" => "silvopasture",
                "Seed Dispersal / Direct Seeding" => "seed_dispersal_direct_seeding"
            ],
            "land_tenures" => [
                "Public" => "public",
                "Private" => "private",
                "Indigenous" => "indigenous",
                "Communal" => "communal",
                "National Protected Area" => "national_protected_area",
                "Other" => "other",
            ],
        ],
        "disturbances" => [
            "Manmade" => "manmade",
            "Ecological" => "ecological",
            "Climatic" => "climatic",
        ],
    ],

    "capacity_building_needs" => [
        "Site Selection" => "site_selection",
        "Nursery Management" => "nursery_management",
        "Species" => "species",
        "Community" => "community",
        "Narrative" => "narrative",
        "Field Monitoring" => "field_monitoring",
        "Remote Sensing" => "remote_sensing",
        "Accounting" => "accounting",
        "Proposal" => "proposal",
        "Government" => "government",
        "Certifications" => "certifications",
        "Communications" => "communications",
        "Product" => "product",
    ],

    "restoration_intervention_types" => [
        "Mangrove Tree Restoration" => "mangrove_tree_restoration",
        "Assisted Natural Regeneration" => "assisted_natural_regeneration",
        "Agroforestry" => "agroforestry",
        "Plantations" => "plantations",
        "Wetland / Riparian" => "wetland_riparian",
        "Enrichment Planting" => "enrichment_planting",
        "Applied Nucleation / Tree Island" => "applied_nucleation_tree_island",
        "Silvopasture" => "silvopasture",
        "Seed Dispersal / Direct Seeding" => "seed_dispersal_direct_seeding"
    ],

];
