title: ApplicationLiteRead
type: object
properties:
  uuid:
    type: string
  current_submission:
    $ref: './_index.yml#/FormSubmissionLiteRead'
  funding_programme_name:
    type: string
  funding_programme_uuid:
    type: string
  organisation_name:
    type: string
  organisation_uuid:
    type: string
  created_at:
    type: string
    format: date-time
  updated_at:
    type: string
    format: date-time
