<?php

return [
    'models' => [
        'organisation' => [
            'label' => 'Organisation',
            'model' => App\Models\V2\Organisation::class,
            'fields' => [
                'org-type' => ['property' => 'type', 'label' => 'Type', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'organisation-type'],
                'org-sub-type' => ['property' => 'subtype', 'label' => 'Subtype', 'input_type' => 'select', 'multichoice' => false,  'option_list_key' => 'business-type'],
                'org-name' => ['property' => 'name', 'label' => 'Name', 'input_type' => 'text'],
                'org-phone' => ['property' => 'phone', 'label' => 'Phone', 'input_type' => 'text'],
                'org-hq-st1' => ['property' => 'hq_street_1', 'label' => 'HQ street 1', 'input_type' => 'text'],
                'org-hq-st2' => ['property' => 'hq_street_2', 'label' => 'HQ street 2', 'input_type' => 'text'],
                'org-hq-city' => ['property' => 'hq_city', 'label' => 'HQ city', 'input_type' => 'text'],
                'org-hq-state' => ['property' => 'hq_state', 'label' => 'HQ state', 'input_type' => 'text'],
                'org-hq-zip' => ['property' => 'hq_zipcode', 'label' => 'HQ zipcode', 'input_type' => 'text'],
                'org-hq-country' => ['property' => 'hq_country', 'label' => 'HQ country', 'input_type' => 'select',  'multichoice' => false, 'option_list_key' => 'countries'],
                'org-countries' => ['property' => 'countries', 'label' => 'Countries', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'countries'],
                'org-languages' => ['property' => 'languages', 'label' => 'Languages', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'languages'],
                'org-fdg-dte' => ['property' => 'founding_date', 'label' => 'Founding date', 'input_type' => 'date'],
                'org-web-url' => ['property' => 'web_url', 'label' => 'Web url', 'input_type' => 'text'],
                'org-fb-url' => ['property' => 'facebook_url', 'label' => 'Facebook url', 'input_type' => 'text'],
                'org-inst-url' => ['property' => 'instagram_url', 'label' => 'Instagram url', 'input_type' => 'text'],
                'org-lnkn-url' => ['property' => 'linkedin_url', 'label' => 'Linkedin url', 'input_type' => 'text'],
                'org-twi-url' => ['property' => 'twitter_url', 'label' => 'Twitter url', 'input_type' => 'text'],
                'org-description' => ['property' => 'description', 'label' => 'Description', 'input_type' => 'long-text'],
                'org-ldr-shp-team' => ['property' => 'leadership_team_txt', 'label' => 'Leadership Team Text', 'input_type' => 'long-text'],
                'org-business-model' => ['property' => 'business_model', 'label' => 'Business Model', 'input_type' => 'long-text'],
                'org-rel-exp-years' => ['property' => 'relevant_experience_years', 'label' => 'Relevant experience years', 'input_type' => 'number'],
                'org-ha-res-tot' => ['property' => 'ha_restored_total', 'label' => 'Ha restored total', 'input_type' => 'number'],
                'org-ha-res-3yr' => ['property' => 'ha_restored_3year', 'label' => 'Ha restored -3 year', 'input_type' => 'number'],
                'org-tre-gro-tot' => ['property' => 'trees_grown_total', 'label' => 'Trees grown total', 'input_type' => 'number'],
                'org-tre-gro-3yr' => ['property' => 'trees_grown_3year', 'label' => 'Trees grown -3 year', 'input_type' => 'number'],
                'org-fin_start_month' => ['property' => 'fin_start_month', 'label' => 'Start of financial year (month)', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'months'],
                'org-fin-bgt-cur-year' => ['property' => 'fin_budget_current_year', 'label' => 'Budget current year', 'input_type' => 'number'],
                'org-fin-bgt-1year' => ['property' => 'fin_budget_1year', 'label' => 'Budget -1 year', 'input_type' => 'number'],
                'org-fin-bgt-2year' => ['property' => 'fin_budget_2year', 'label' => 'Budget -2 year', 'input_type' => 'number'],
                'org-fin-bgt-3year' => ['property' => 'fin_budget_3year', 'label' => 'Budget -3 year', 'input_type' => 'number'],
                'org-eng-farmers' => ['property' => 'engagement_farmers', 'label' => 'Engagement farmers', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-farmers'],
                'org-eng-women' => ['property' => 'engagement_women', 'label' => 'Engagement women', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-women'],
                'org-eng-youth' => ['property' => 'engagement_youth', 'label' => 'Engagement youth', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-youth'],
                'org-eng-non-youth' => ['property' => 'engagement_non_youth', 'label' => 'Engagement non-youth', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-non-youth'],
                'org-ha-rst-tot' => ['property' => 'ha_restored_total', 'label' => 'Ha restored Total', 'input_type' => 'number'],
                'org-ha-rst-3year' => ['property' => 'ha_restored_3year', 'label' => 'Ha restored -3 year', 'input_type' => 'number'],

                'org-community-experience' => ['property' => 'community_experience', 'label' => 'Community engagement experience', 'input_type' => 'long-text'],
                'org-tot-eng-comty-mbrs-3yr' => ['property' => 'total_engaged_community_members_3yr', 'label' => 'Total # of community members engaged over the last 3 years', 'input_type' => 'number'],
                'org-female-employees' => ['property' => 'female_employees', 'label' => 'Number of female employees', 'input_type' => 'number'],
                'org-male-employees' => ['property' => 'male_employees', 'label' => 'Number of male employees', 'input_type' => 'number'],
                'org-young-employees' => ['property' => 'young_employees', 'label' => 'Number of employees between and including ages 18 and 35', 'input_type' => 'number'],
                'org-temp-employees' => ['property' => 'temp_employees', 'label' => 'Number of temporary employees', 'input_type' => 'number'],
                'org-ft-perm-employees' => ['property' => 'ft_permanent_employees', 'label' => 'Number of full-time permanent employees', 'input_type' => 'number'],
                'org-pt-perm-employees' => ['property' => 'pt_permanent_employees', 'label' => 'Number of part-time permanent employees', 'input_type' => 'number'],
                'org-over-35-employees' => ['property' => 'over_35_employees', 'label' => 'Number of employees older than 35 years of age', 'input_type' => 'number'],

                'org-engagement-farmers' => ['property' => 'engagement_farmers', 'label' => 'Enagement: Farmers', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-farmers'],
                'org-engagement-women' => ['property' => 'engagement_women', 'label' => 'Enagement: Women', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-women'],
                'org-engagement-youth' => ['property' => 'engagement_youth', 'label' => 'Enagement: Youth', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-youth'],

                'org-add-fund-details' => ['property' => 'additional_funding_details', 'label' => 'Additional funding details', 'input_type' => 'long-text'],
                'org-total-trees-grown' => ['property' => 'total_trees_grown', 'label' => 'Total trees grown', 'input_type' => 'number'],
                'org-avg-tree-survival-rate' => ['property' => 'avg_tree_survival_rate', 'label' => 'Average tree survival rate', 'input_type' => 'number'],
                'org-tree-maint-aftercare-aprch' => ['property' => 'tree_maintenance_aftercare_approach', 'label' => 'Tree maintenance and aftercare approach', 'input_type' => 'long-text'],
                'org-restored-areas-desc' => ['property' => 'restored_areas_description', 'label' => 'Restored areas description', 'input_type' => 'long-text'],
                'org-mon-eval-exp' => ['property' => 'monitoring_evaluation_experience', 'label' => 'Monitoring evaluation experience', 'input_type' => 'long-text'],

                'org-pct-engaged-women-3yr' => ['property' => 'percent_engaged_women_3yr', 'label' => 'Percent women engaged (3yr)', 'input_type' => 'number-percentage'],
                'org-pct-engaged-men-3yr' => ['property' => 'percent_engaged_men_3yr', 'label' => 'Percent men engaged (3yr)', 'input_type' => 'number-percentage'],
                'org-pct-engaged-young-3yr' => ['property' => 'percent_engaged_under_35_3yr', 'label' => 'Percent youth engaged (3yr)', 'input_type' => 'number-percentage'],
                'org-pct-engaged-old-3yr' => ['property' => 'percent_engaged_over_35_3yr', 'label' => 'Percent non-youth engaged (3yr)', 'input_type' => 'number-percentage'],
                'org-pct-engaged-smallholder-3yr' => ['property' => 'percent_engaged_smallholder_3yr', 'label' => 'Percent smallholder engaged (3yr)', 'input_type' => 'number-percentage'],
                'org-rev-this-year' => ['property' => 'organisation_revenue_this_year', 'label' => 'Organization revenue for this year', 'input_type' => 'number'],

                'org-restoration-types-implemented' => ['property' => 'restoration_types_implemented', 'label' => 'Restoration Intervention Types Implemented', 'multichoice' => true, 'input_type' => 'select'],
                'org-historic-monitoring-geojson' => ['property' => 'historic_monitoring_geojson', 'label' => 'Historic monitoring shapefile upload', 'input_type' => 'mapInput'],

                'org-states' => ['property' => 'states', 'label' => 'States', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'states'],
                'org-district' => ['property' => 'district', 'label' => 'District', 'input_type' => 'text'],
                'org-acc-num-1' => ['property' => 'account_number_1', 'label' => 'Account Number 1', 'input_type' => 'text'],
                'org-acc-num-2' => ['property' => 'account_number_2', 'label' => 'Account Number 2', 'input_type' => 'text'],
                'org-loan-status-amount' => ['property' => 'loan_status_amount', 'label' => 'Loan Status Amount', 'input_type' => 'number'],
                'org-loan-status-types' => ['property' => 'loan_status_types', 'label' => 'Loan Status Types', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'loan-status'],
                'org-marg-com-appr' => ['property' => 'approach_of_marginalized_communities', 'label' => 'Approach of Marginalized Communities', 'input_type' => 'long-text'],
                'org-marg-com-eng-num' => ['property' => 'community_engagement_numbers_marginalized', 'label' => 'Marginalized Community Engagement Numbers', 'input_type' => 'long-text'],
                'org-land-systems' => ['property' => 'land_systems', 'label' => 'Land Systems', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-systems'],
                'org-fund-utilisation' => ['property' => 'fund_utilisation', 'label' => 'Fund Utilisation', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'loan-status'],
                'org-tree-restoration-practices' => ['property' => 'tree_restoration_practices', 'label' => 'Tree Restoration Practices', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-practices'],
                'org-detailed-interventions' => ['property' => 'detailed_intervention_types', 'label' => 'Detailed Intervention Types', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'interventions'],

                'org-com-eng-3yr' => ['property' => 'community_members_engaged_3yr', 'label' => 'Community Members Engaged (3 years)', 'input_type' => 'number'],
                'org-com-eng-3yr-men' => ['property' => 'community_members_engaged_3yr_men', 'label' => 'Community Members Engaged - Men (3 years)', 'input_type' => 'number'],
                'org-com-eng-3yr-women' => ['property' => 'community_members_engaged_3yr_women', 'label' => 'Community Members Engaged - Women (3 years)', 'input_type' => 'number'],
                'org-com-eng-3yr-youth' => ['property' => 'community_members_engaged_3yr_youth', 'label' => 'Community Members Engaged - Youth (3 years)', 'input_type' => 'number'],
                'org-com-eng-3yr-non-youth' => ['property' => 'community_members_engaged_3yr_non_youth', 'label' => 'Community Members Engaged - Non-Youth (3 years)', 'input_type' => 'number'],
                'org-com-eng-3yr-smallholder' => ['property' => 'community_members_engaged_3yr_smallholder', 'label' => 'Community Members Engaged - Smallholder (3 years)', 'input_type' => 'number'],
                'org-com-eng-3yr-backward-class' => ['property' => 'community_members_engaged_3yr_backward_class', 'label' => 'Community Members Engaged - Backward Class (3 years)', 'input_type' => 'number'],

                'org-total-board-members' => ['property' => 'total_board_members', 'label' => 'Total Number of Board Members', 'input_type' => 'number'],
                'org-pct-board-women' => ['property' => 'pct_board_women', 'label' => '% of board members that are women', 'input_type' => 'number-percentage'],
                'org-pct-board-men' => ['property' => 'pct_board_men', 'label' => '% of board members that are men', 'input_type' => 'number-percentage'],
                'org-pct-board-youth' => ['property' => 'pct_board_youth', 'label' => '% of board members that are youth', 'input_type' => 'number-percentage'],
                'org-pct-board-non-youth' => ['property' => 'pct_board_non_youth', 'label' => '% of board members that are non-youth', 'input_type' => 'number-percentage'],

                'org-field-staff-skills' => ['property' => 'field_staff_skills', 'label' => 'Field staff skills', 'input_type' => 'long-text'],
                'org-fpc-company' => ['property' => 'fpc_company', 'label' => 'FPC company', 'input_type' => 'radio', 'multichoice' => false, 'option_list_key' => 'yes-no'],
                'org-num-of-farmers-on-board' => ['property' => 'num_of_farmers_on_board', 'label' => 'How many farmers on board: FPC company', 'input_type' => 'number'],
                'org-num_of-marginalised-employees' => ['property' => 'num_of_marginalised_employees', 'label' => 'Number of employees from Marginalised statuses', 'input_type' => 'number'],
                'org-benefactors-fpc-company' => ['property' => 'benefactors_fpc_company', 'label' => 'Supporters/benefactors: FPC company', 'input_type' => 'long-text'],
                'org-board-remuneration-fpc-company' => ['property' => 'board_remuneration_fpc_company', 'label' => 'Board remuneration: FPC company', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'board-remuneration'],
                'org-board-engagement-fpc-company' => ['property' => 'board_engagement_fpc_company', 'label' => 'Board engagement: FPC company', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'board-engagement'],
                'org-biodiversity-focus' => ['property' => 'biodiversity_focus', 'label' => 'Biodiversity focus', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'biodiversity'],
                'org-global-planning-frameworks' => ['property' => 'global_planning_frameworks', 'label' => 'Global planning frameworks', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'planning-frameworks'],
                'org-past-gov-collaboration' => ['property' => 'past_gov_collaboration', 'label' => 'Past Government Collaboration', 'input_type' => 'long-text'],
                'org-engagement-landless' => ['property' => 'engagement_landless', 'label' => 'Engagement: Landless', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'engagement-landless'],
            ],
            'file-collections' => [
                'org-fcol-cover' => ['property' => 'cover', 'label' => 'Cover image', 'input_type' => 'file', 'multichoice' => false],
                'org-fcol-lgl-reg' => ['property' => 'legal_registration', 'label' => 'Legal registration', 'input_type' => 'file',  'multichoice' => true],
                'org-fcol-logo' => ['property' => 'logo', 'label' => 'Logo image', 'input_type' => 'file', 'multichoice' => false],
                'org-fcol-ref' => ['property' => 'reference', 'label' => 'Reference documents', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-op-bgt-1year' => ['property' => 'op_budget_1year', 'label' => 'Budget -1 year documents', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-op-bgt-2year' => ['property' => 'op_budget_2year', 'label' => 'Budget -2 year documents', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-op-bgt-3year' => ['property' => 'op_budget_3year', 'label' => 'Budget -3 year documents', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-op-this-year' => ['property' => 'op_budget_this_year', 'label' => 'Organization Budget for this year', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-op-next-year' => ['property' => 'op_budget_next_year', 'label' => 'Organization Budget for next year', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-hst-rest' => ['property' => 'historic_restoration', 'label' => 'Historic restoration', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-additional' => ['property' => 'additional', 'label' => 'Additional documents', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-bank-statments' => ['property' => 'bank_statements', 'label' => 'Bank statements', 'input_type' => 'file', 'multichoice' => true],
                'org-fcol-prev-annual-rpts' => ['property' => 'previous_annual_reports', 'label' => 'Previous annual reports', 'input_type' => 'file', 'multichoice' => true],
                'org-avg-tree-surv-rate-proof' => ['property' => 'avg_tree_survival_rate_proof', 'label' => 'Average tree survival rate proof', 'input_type' => 'file', 'multichoice' => true],
                'org-equ-ownership' => ['property' => 'equity_ownership', 'label' => 'Equity Ownership', 'input_type' => 'file', 'multichoice' => false],
                'org-loan-status' => ['property' => 'loan_status', 'label' => 'Loan Status', 'input_type' => 'file', 'multichoice' => true],
                'org-past-rest-photos' => ['property' =>  'restoration_photos', 'label' => 'Past Restoration Photos', 'input_type' => 'file', 'multichoice' => true],
                'org-startup-recognition-cert' => ['property' =>  'startup_recognition_cert', 'label' => 'Certificate of Startup Recognition', 'input_type' => 'file', 'multichoice' => true],
            ],
            'relations' => [
                'org-funding-types' => [
                    'property' => 'fundingTypes',
                    'label' => 'Funding Type',
                    'resource' => 'App\Http\Resources\V2\FundingTypeResource',
                    'input_type' => 'fundingType',
                ],
                'org-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                ],
                'org-leadership-team' => [
                    'property' => 'leadershipTeam',
                    'label' => 'Leadership Team',
                    'resource' => 'App\Http\Resources\V2\LeadershipTeamResource',
                    'input_type' => 'leadershipTeam',
                ],
                'org-core-team-leaders' => [
                    'property' => 'coreTeamLeaders',
                    'label' => 'Core Team Leaders',
                    'resource' => 'App\Http\Resources\V2\CoreTeamLeaderResource',
                    'input_type' => 'coreTeamLeaders',
                ],
                'org-tree-species-restored' => [
                    'property' => 'treeSpeciesRestored',
                    'label' => 'Tree species restored in landscape',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'restored'
                ],
            ],
        ],
        'project-pitch' => [
            'label' => 'Project Pitch',
            'model' => App\Models\V2\ProjectPitch::class,
            'fields' => [
                'pro-pit-name' => ['property' => 'project_name', 'label' => 'Name', 'input_type' => 'text'],
                'pro-pit-objectives' => ['property' => 'project_objectives', 'label' => 'Objectives', 'input_type' => 'long-text'],
                'pro-pit-district' => ['property' => 'project_county_district', 'label' => 'County district', 'input_type' => 'text'],
                'pro-pit-country' => ['property' => 'project_country', 'label' => 'Country', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'countries'],
                'pro-pit-rst-inv-types' => ['property' => 'restoration_intervention_types', 'label' => 'Restoration intervention types', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-systems'],
                'pro-pit-detailed-rst-inv-types' => ['property' => 'detailed_intervention_types', 'label' => 'Detailed intervention types', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'interventions'],
                'pro-pit-tot-ha' => ['property' => 'total_hectares', 'label' => 'Total hectares', 'input_type' => 'number'],
                'pro-pit-tot-trees' => ['property' => 'total_trees', 'label' => 'Total trees', 'input_type' => 'number'],
                'pro-pit-bgt' => ['property' => 'project_budget', 'label' => 'Project budget', 'input_type' => 'number'],
                'pro-pit-cap-bld-needs' => ['property' => 'capacity_building_needs', 'label' => 'Capacity building needs', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'building-needs'],
                'pro-pit-how-discovered' => ['property' => 'how_discovered', 'label' => 'How discovered WRI', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'media-channels'],
                'pro-pit-land-tenure-proj-area' => ['property' => 'land_tenure_proj_area', 'label' => 'Land tenure project area', 'input_type' => 'select', 'multichoice' => true],

                'pro-pit-expected-active-rest-start-date' => ['property' => 'expected_active_restoration_start_date', 'label' => 'Expected active restoration start date', 'input_type' => 'date'],
                'pro-pit-expected-active-rest-end-date' => ['property' => 'expected_active_restoration_end_date', 'label' => 'Expected active restoration end date', 'input_type' => 'date'],
                'pro-pit-desc-of-proj-timeline' => ['property' => 'description_of_project_timeline', 'label' => 'Description of project timeline', 'input_type' => 'long-text'],
                'pro-pit-proj-partner-info' => ['property' => 'proj_partner_info', 'label' => 'Project partner info', 'input_type' => 'long-text'],
                'pro-pit-landholder-comm-engage' => ['property' => 'landholder_comm_engage', 'label' => 'Landholder & Community Engagement Strategy', 'input_type' => 'long-text'],
                'pro-pit-proj-success-risks' => ['property' => 'proj_success_risks', 'label' => 'Project risks to success', 'input_type' => 'long-text'],
                'pro-pit-monitor-eval-plan' => ['property' => 'monitor_eval_plan', 'label' => 'Monitoring and evaluation plan', 'input_type' => 'long-text'],
                'pro-pit-proj-boundary' => ['property' => 'proj_boundary', 'label' => 'Project Boundary', 'input_type' => 'mapInput'],
                'pro-pit-sustainable-dev-goals' => ['property' => 'sustainable_dev_goals', 'label' => 'Sustainable Development Goals', 'input_type' => 'select-image', 'multichoice' => true],

                'pro-pit-proj-area-desc' => ['property' => 'proj_area_description', 'label' => 'Description of Project Area', 'input_type' => 'long-text'],
                'pro-pit-curr-land-degradation' => ['property' => 'curr_land_degradation', 'label' => 'Main causes of degradation', 'input_type' => 'long-text'],
                'pro-pit-proposed-num-sites' => ['property' => 'proposed_num_sites', 'label' => 'Proposed Number of Sites', 'input_type' => 'number'],
                'pro-pit-environmental-goals' => ['property' => 'environmental_goals', 'label' => 'Environmental goals', 'input_type' => 'long-text'],
                'pro-pit-proposed-num-nurseries' => ['property' => 'proposed_num_nurseries', 'label' => 'Proposed Number of Nurseries', 'input_type' => 'number'],
                'pro-pit-proj-impact-socieconom' => ['property' => 'proj_impact_socieconom', 'label' => 'Potential project impact: socioeconomic', 'input_type' => 'long-text'],
                'pro-pit-proj-impact-foodsec' => ['property' => 'proj_impact_foodsec', 'label' => 'Potential project impact: food security', 'input_type' => 'long-text'],
                'pro-pit-proj-impact-watersec' => ['property' => 'proj_impact_watersec', 'label' => 'Potential project impact: water security', 'input_type' => 'long-text'],
                'pro-pit-proj-impact-jobtypes' => ['property' => 'proj_impact_jobtypes', 'label' => 'Potential project impact: types of jobs created', 'input_type' => 'long-text'],
                'pro-pit-num-jobs-created' => ['property' => 'num_jobs_created', 'label' => 'Number of jobs created', 'input_type' => 'number'],
                'pro-pit-beneficiaries' => ['property' => 'proj_beneficiaries', 'label' => 'Total Expected project beneficiaries', 'input_type' => 'number'],
                'pro-pit-pct-beneficiaries-small' => ['property' => 'pct_beneficiaries_small', 'label' => '% Beneficiaries smallholder', 'input_type' => 'number-percentage'],
                'pro-pit-pct-beneficiaries-large' => ['property' => 'pct_beneficiaries_large', 'label' => '% Beneficiaries large', 'input_type' => 'number-percentage'],
                'pro-pit-pct-beneficiaries-women' => ['property' => 'pct_beneficiaries_women', 'label' => '% Beneficiaries women', 'input_type' => 'number-percentage'],
                'pro-pit-pct-beneficiaries-35below' => ['property' => 'pct_beneficiaries_youth', 'label' => '% Beneficiaries youth', 'input_type' => 'number-percentage'],
                'pro-pit-pct-beneficiaries-sch-classes' => ['property' => 'pct_beneficiaries_scheduled_classes', 'label' => '% Beneficiaries Scheduled Classes', 'input_type' => 'number-percentage'],
                'pro-pit-pct-beneficiaries-sch-tribes' => ['property' => 'pct_beneficiaries_scheduled_tribes', 'label' => '% Beneficiaries Scheduled Tribes', 'input_type' => 'number-percentage'],

                'pro-pit-main-degradation_causes' => ['property' => 'main_degradation_causes', 'label' => 'Main degradation causes', 'input_type' => 'long-text'],
                'pro-pit-seedlings-source' => ['property' => 'seedlings_source', 'label' => 'Seedlings source', 'input_type' => 'long-text'],
                'pro-pit-pct-employees-men' => ['property' => 'pct_employees_men', 'label' => '% of total employees that would be men', 'input_type' => 'number-percentage'],
                'pro-pit-pct-employees-women' => ['property' => 'pct_employees_women', 'label' => '% of total employees that would be women', 'input_type' => 'number-percentage'],
                'pro-pit-pct-employees-18to35' => ['property' => 'pct_employees_18to35', 'label' => '% of total employees that would be between the ages of 18 and 35', 'input_type' => 'number-percentage'],
                'pro-pit-pct-employees-older35' => ['property' => 'pct_employees_older35', 'label' => '% of total employees that would be older than 35 years of age', 'input_type' => 'number-percentage'],

                'pro-pit-states' => ['property' => 'states', 'label' => 'States', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'states'],
                'pro-pit-hec-yr1' => ['property' => 'hectares_first_yr', 'label' => 'Hectares to be restored in the first year', 'input_type' => 'number'],
                'pro-pit-trees-yr1' => ['property' => 'total_trees_first_yr', 'label' => 'Trees planted in the first year', 'input_type' => 'number'],
                'pro-pit-pct-beneficiaries-backward-class' => ['property' => 'pct_beneficiaries_backward_class', 'label' => '% Beneficiaries backward class', 'input_type' => 'number-percentage'],
                'pro-pit-land-systems' => ['property' => 'land_systems', 'label' => 'Land systems', 'input_type' => 'select', 'multichoice' => true, 'option_list_key' => 'restoration-systems'],
                'pro-pit-tree-rest-prac' => ['property' => 'tree_restoration_practices', 'label' => 'Tree Restoration Practices', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-practices'],
                'pro-pit-main-cause-deg' => ['property' => 'main_causes_of_degradation', 'label' => 'Main causes of degradation', 'input_type' => 'long-text'],
                'pro-theory-of-change' => ['property' => 'theory_of_change', 'label' => 'Theory of change', 'input_type' => 'long-text'],
                'pro-proposed-gov-partners' => ['property' => 'proposed_gov_partners', 'label' => 'Proposed government partners', 'input_type' => 'long-text'],
                'pro-pct-sch-tribe' => ['property' => 'pct_sch_tribe', 'label' => '% of total employees that would be Scheduled Caste/Other Backward Class/Scheduled Tribe', 'input_type' => 'number-percentage'],
                'pro-sustainability-plan' => ['property' => 'sustainability_plan', 'label' => 'Project sustainability plan', 'input_type' => 'long-text'],
                'pro-replication-plan' => ['property' => 'replication_plan', 'label' => 'Project replication plan', 'input_type' => 'long-text'],
                'pro-replication-challenges' => ['property' => 'replication_challenges', 'label' => 'Project replication challenges', 'input_type' => 'long-text'],
                'pro-solution-market-size' => ['property' => 'solution_market_size', 'label' => 'Solution market size', 'input_type' => 'long-text'],
                'pro-affordability-of-solution' => ['property' => 'affordability_of_solution', 'label' => 'Affordability of solution/products', 'input_type' => 'long-text'],
                'pro-growth-trends-business' => ['property' => 'growth_trends_business', 'label' => 'Growth trends of business', 'input_type' => 'long-text'],
                'pro-limitations-on-scope' => ['property' => 'limitations_on_scope', 'label' => 'Limitations on scope of operations', 'input_type' => 'long-text'],
                'pro-business-model-replication_plan' => ['property' => 'business_model_replication_plan', 'label' => 'Business model replication plan', 'input_type' => 'long-text'],
                'pro-biodiversity-impact' => ['property' => 'biodiversity_impact', 'label' => 'Biodiversity Impact (project)', 'input_type' => 'long-text'],
                'pro-water-source' => ['property' => 'water_source', 'label' => 'Water Source (project)', 'input_type' => 'long-text'],
                'pro-climate-resilience' => ['property' => 'climate_resilience', 'label' => 'Climate resilience (project)', 'input_type' => 'long-text'],
                'pro-soil-health' => ['property' => 'soil_health', 'label' => 'Soil Health (project)', 'input_type' => 'long-text'],
                'pro-pit-land-use-types' => ['property' => 'land_use_types', 'label' => 'Land use types', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-systems'],
                'pro-pit-restoration_strategy' => ['property' => 'restoration_strategy', 'label' => 'Restoration strategy', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-practices'],
            ],
            'file-collections' => [
                'pro-pit-fcol-cover' => ['property' =>  'cover', 'label' => 'Cover Image', 'input_type' => 'file', 'multichoice' => false],
                'pro-pit-fcol-add' => ['property' =>  'additional', 'label' => 'Additional documents', 'input_type' => 'file', 'multichoice' => true],
                'pro-pit-fcol-rest-photos' => ['property' =>  'restoration_photos', 'label' => 'Past Restoration Photos', 'input_type' => 'file', 'multichoice' => true],
                'pro-pit-fcol-detail-proj-bdgt' => ['property' =>  'detailed_project_budget', 'label' => 'Detailed project budget', 'input_type' => 'file', 'multichoice' => false],
                'pro-pit-proof-of-land-tenure-mou' => ['property' =>  'proof_of_land_tenure_mou', 'label' => 'Proof of land tenure MOU', 'input_type' => 'file', 'multichoice' => true],
            ],
            'relations' => [
                'pro-pit-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource::class,
                    'input_type' => 'treeSpecies',
                    'collection' => 'primary',
                ],
            ],
        ],
        'project' => [
            'label' => 'Project',
            'model' => 'App\Models\V2\Projects\Project',
            'fields' => [
                'pro-name' => ['property' => 'name', 'label' => 'Name', 'input_type' => 'text'],
                'pro-land-use-types' => ['property' => 'land_use_types', 'label' => 'Land use types', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-systems'],
                'pro-restoration_strategy' => ['property' => 'restoration_strategy', 'label' => 'Restoration strategy', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-practices'],
                'pro-land-tenure-proj-area' => ['property' => 'land_tenure_project_area', 'label' => 'Land tenure', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'project-land-tenures'],
                'pro-country' => ['property' => 'country', 'label' => 'Country', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'countries'],
                'pro-continent' => ['property' => 'continent', 'label' => 'Continent', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'continents'],
                'pro-plant_start_dte' => ['property' => 'planting_start_date', 'label' => 'planting start date', 'input_type' => 'date'],
                'pro-plant_end_dte' => ['property' => 'planting_end_date', 'label' => 'Planting end date', 'input_type' => 'date'],
                'pro-description' => ['property' => 'description', 'label' => 'Description', 'input_type' => 'long-text'],
                'pro-history' => ['property' => 'history', 'label' => 'History', 'input_type' => 'long-text'],
                'pro-objectives' => ['property' => 'objectives', 'label' => 'Objectives', 'input_type' => 'long-text'],
                'pro-environmental-goals' => ['property' => 'environmental_goals', 'label' => 'Environmental goals', 'input_type' => 'long-text'],
                'pro-socioeconomic-goals' => ['property' => 'socioeconomic_goals', 'label' => 'Socioeconomic goals', 'input_type' => 'long-text'],
                'pro-sdgs-impacted' => ['property' => 'sdgs_impacted', 'label' => 'SDGS impacted', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'sdgs-impacted-type'],
                'pro-long-term-growth' => ['property' => 'long_term_growth', 'label' => 'Long term growth', 'input_type' => 'long-text'],
                'pro-community-incentives' => ['property' => 'community_incentives', 'label' => 'Community incentives', 'input_type' => 'long-text'],
                'pro-budget' => ['property' => 'budget', 'label' => 'budget', 'input_type' => 'number'],
                'pro-jobs-created-goal' => ['property' => 'jobs_created_goal', 'label' => 'Jobs created goal', 'input_type' => 'number'],
                'pro-total-hectares-restored-goal' => ['property' => 'total_hectares_restored_goal', 'label' => 'Total hectares restored goal', 'input_type' => 'number'],
                'pro-trees-grown-goal' => ['property' => 'trees_grown_goal', 'label' => 'Trees grown goal', 'input_type' => 'number'],
                'pro-survival-rate' => ['property' => 'survival_rate', 'label' => 'Survival rate', 'input_type' => 'number'],
                'pro-year-five-crown-cover' => ['property' => 'year_five_crown_cover', 'label' => 'Year five crown cover', 'input_type' => 'number'],
                'pro-monitored-tree-cover' => ['property' => 'monitored_tree_cover', 'label' => 'monitored tree cover', 'input_type' => 'number'],
                'pro-organization-name' => ['property' => 'organization_name', 'label' => 'Organisation Name', 'input_type' => 'text'],
                'pro-county-district' => ['property' => 'project_county_district', 'label' => 'Project District', 'input_type' => 'text'],
                'pro-desc-of-proj-timeline' => ['property' => 'description_of_project_timeline', 'label' => 'Key stages of this project’s implementation', 'input_type' => 'long-text'],
                'pro-siting-strategy-description' => ['property' => 'siting_strategy_description', 'label' => 'Siting Strategy Description', 'input_type' => 'long-text'],
                'pro-siting-strategy' => ['property' => 'siting_strategy', 'label' => 'Siting Strategy', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'siting-strategy'],
                'pro-landholder-comm-engage' => ['property' => 'landholder_comm_engage', 'label' => 'Landholder & Community Engagement Strategy', 'input_type' => 'long-text'],
                'pro-proj-partner-info' => ['property' => 'proj_partner_info', 'label' => 'Proposed project partner information', 'input_type' => 'long-text'],
                'pro-proj-success-risks' => ['property' => 'proj_success_risks', 'label' => 'Risk + Mitigate strategy', 'input_type' => 'long-text'],
                'pro-monitor-eval-plan' => ['property' => 'monitor_eval_plan', 'label' => 'Report, Monitor, Verification Strategy', 'input_type' => 'long-text'],
                'pro-seedlings-source' => ['property' => 'seedlings_source', 'label' => 'Sources of tree seedlings for the project', 'input_type' => 'long-text'],
                'pro-pct-employees-men' => ['property' => 'pct_employees_men', 'label' => '% of total employees that would be men', 'input_type' => 'number-percentage'],
                'pro-pct-employees-women' => ['property' => 'pct_employees_women', 'label' => '% of total employees that would be women', 'input_type' => 'number-percentage'],
                'pro-pct-employees-18to35' => ['property' => 'pct_employees_18to35', 'label' => '% of total employees that would be between the ages of 18 and 35', 'input_type' => 'number-percentage'],
                'pro-pct-employees-older35' => ['property' => 'pct_employees_older35', 'label' => '% of total employees that would be older than 35 years of age', 'input_type' => 'number-percentage'],
                'pro-beneficiaries' => ['property' => 'proj_beneficiaries', 'label' => 'Project beneficiaries Total', 'input_type' => 'number'],
                'pro-pct-beneficiaries-women' => ['property' => 'pct_beneficiaries_women', 'label' => '% of female beneficiaries', 'input_type' => 'number-percentage'],
                'pro-pct-beneficiaries-small' => ['property' => 'pct_beneficiaries_small', 'label' => '% of smallholder farmers beneficiaries', 'input_type' => 'number-percentage'],
                'pro-pct-beneficiaries-large' => ['property' => 'pct_beneficiaries_large', 'label' => '% of large-scale farmers beneficiaries', 'input_type' => 'number-percentage'],
                'pro-pct-beneficiaries-35below' => ['property' => 'pct_beneficiaries_youth', 'label' => '% of beneficiaries younger than 36', 'input_type' => 'number-percentage'],
            ],
            'file-collections' => [
                'pro-col-media' => ['property' =>  'media', 'label' => 'Media', 'input_type' => 'file', 'multichoice' => true],
                'pro-col-socioeconomic-benefits' => ['property' =>  'socioeconomic_benefits', 'label' => 'Socioeconomic benefits', 'input_type' => 'file', 'multichoice' => true],
                'pro-col-file' => ['property' =>  'file', 'label' => 'File', 'input_type' => 'file', 'multichoice' => true],
                'pro-col-other-additional-documents' => ['property' =>  'other_additional_documents', 'label' => 'Other additional documents', 'input_type' => 'file', 'multichoice' => true],
                'pro-col-photos' => ['property' =>  'photos', 'label' => 'Photos', 'input_type' => 'file', 'multichoice' => true],
                'pro-col-document-files' => ['property' =>  'document_files', 'label' => 'Document Files', 'input_type' => 'file', 'multichoice' => true],
                'pro-col-programme-submission' => ['property' =>  'programme_submission', 'label' => 'programme_submission', 'input_type' => 'file', 'multichoice' => true],
                // new collections
                'pro-col-detailed-project-budget' => ['property' => 'detailed_project_budget', 'label' => 'Detailed project budget', 'input_type' => 'file', 'multichoice' => false],
                'pro-col-proof-of-land-tenure-mou' => ['property' =>  'proof_of_land_tenure_mou', 'label' => 'Documentation on project area’s land tenure', 'input_type' => 'file', 'multichoice' => true],
            ],
            'relations' => [
                'pro-pit-rel-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'primary',
                ],
            ],
        ],
        'project-report' => [
            'label' => 'Project Report',
            'model' => 'App\Models\V2\Projects\ProjectReport',
            'fields' => [
                'pro-rep-title' => ['property' => 'title', 'label' => 'Title', 'input_type' => 'text'],
                'pro-rep-ind-1' => ['property' => 'ethnic_indigenous_1', 'label' => 'Indigenous 1', 'input_type' => 'number'],
                'pro-rep-ind-2' => ['property' => 'ethnic_indigenous_2', 'label' => 'Indigenous 2', 'input_type' => 'number'],
                'pro-rep-ind-3' => ['property' => 'ethnic_indigenous_3', 'label' => 'Indigenous 3', 'input_type' => 'number'],
                'pro-rep-ind-4' => ['property' => 'ethnic_indigenous_4', 'label' => 'Indigenous 4', 'input_type' => 'number'],
                'pro-rep-ind-5' => ['property' => 'ethnic_indigenous_5', 'label' => 'Indigenous 5', 'input_type' => 'number'],
                'pro-rep-other-1' => ['property' => 'ethnic_other_1', 'label' => 'Other 1', 'input_type' => 'number'],
                'pro-rep-other-2' => ['property' => 'ethnic_other_2', 'label' => 'Other 2', 'input_type' => 'number'],
                'pro-rep-other-3' => ['property' => 'ethnic_other_3', 'label' => 'Other 3', 'input_type' => 'number'],
                'pro-rep-other-4' => ['property' => 'ethnic_other_4', 'label' => 'Other 4', 'input_type' => 'number'],
                'pro-rep-other-5' => ['property' => 'ethnic_other_5', 'label' => 'Other 5', 'input_type' => 'number'],
                'pro-rep-workdays-paid' => ['property' => 'workdays_paid', 'label' => 'Workdays Paid', 'input_type' => 'number'],
                'pro-rep-workdays-volunteer' => ['property' => 'workdays_volunteer', 'label' => 'Workdays Volunteer', 'input_type' => 'number'],
                'pro-rep-tech-nar' => ['property' => 'technical_narrative', 'label' => 'Technical narrative', 'input_type' => 'long-text'],
                'pro-rep-pub-nar' => ['property' => 'public_narrative', 'label' => 'Public narrative', 'input_type' => 'long-text'],
                'pro-rep-landscape-com-con' => ['property' => 'landscape_community_contribution', 'label' => 'Landscape Progress', 'input_type' => 'long-text'],
                'pro-rep-top-three-successes' => ['property' => 'top_three_successes', 'label' => 'Top Three Successes', 'input_type' => 'long-text'],
                'pro-rep-chal-faced' => ['property' => 'challenges_faced', 'label' => 'Challenges Faced', 'input_type' => 'long-text'],
                'pro-rep-lessons' => ['property' => 'lessons_learned', 'label' => 'Lessons Learned', 'input_type' => 'long-text'],
                'pro-rep-maint-mon-act' => ['property' => 'maintenance_and_monitoring_activities', 'label' => 'Maintenance and Monitoring Activities', 'input_type' => 'long-text'],
                'pro-rep-sig-change' => ['property' => 'significant_change', 'label' => 'Significant Change', 'input_type' => 'long-text'],
                'pro-rep-pct-surv' => ['property' => 'pct_survival_to_date', 'label' => 'Percentage Survival to Date', 'input_type' => 'number-percentage'],
                'pro-rep-surv-calc' => ['property' => 'survival_calculation', 'label' => 'Survival Calculation', 'input_type' => 'long-text'],
                'pro-rep-surv-comp' => ['property' => 'survival_comparison', 'label' => 'Survival Comparison', 'input_type' => 'long-text'],
                'pro-rep-ft-women' => ['property' => 'ft_women', 'label' => 'FT Women', 'input_type' => 'number'],
                'pro-rep-ft-men' => ['property' => 'ft_men', 'label' => 'FT Men', 'input_type' => 'number'],
                'pro-rep-ft-youth' => ['property' => 'ft_youth', 'label' => 'FT Youth', 'input_type' => 'number'],
                'pro-rep-ft-smallholder' => ['property' => 'ft_smallholder_farmers', 'label' => 'FT Smallholder', 'input_type' => 'number'],
                'pro-rep-ft-total' => ['property' => 'ft_total', 'label' => 'FT Total', 'input_type' => 'number'],
                'pro-rep-pt-women' => ['property' => 'pt_women', 'label' => 'PT Women', 'input_type' => 'number'],
                'pro-rep-pt-men' => ['property' => 'pt_men', 'label' => 'PT Men', 'input_type' => 'number'],
                'pro-rep-pt-youth' => ['property' => 'pt_youth', 'label' => 'PT Youth', 'input_type' => 'number'],
                'pro-rep-pt-non-youth' => ['property' => 'pt_non_youth', 'label' => 'PT Non-Youth', 'input_type' => 'number'],
                'pro-rep-pt-smallholder' => ['property' => 'pt_smallholder_farmers', 'label' => 'PT Smallholder', 'input_type' => 'number'],
                'pro-rep-pt-total' => ['property' => 'pt_total', 'label' => 'PT Total', 'input_type' => 'number'],
                'pro-rep-seasonal-women' => ['property' => 'seasonal_women', 'label' => 'Seasonal Women', 'input_type' => 'number'],
                'pro-rep-seasonal-men' => ['property' => 'seasonal_men', 'label' => 'Seasonal Men', 'input_type' => 'number'],
                'pro-rep-seasonal-youth' => ['property' => 'seasonal_youth', 'label' => 'Seasonal Youth', 'input_type' => 'number'],
                'pro-rep-seasonal-smallholder' => ['property' => 'seasonal_smallholder_farmers', 'label' => 'Seasonal Smallholder', 'input_type' => 'number'],
                'pro-rep-seasonal-total' => ['property' => 'seasonal_total', 'label' => 'Seasonal Total', 'input_type' => 'number'],
                'pro-rep-volunteer-women' => ['property' => 'volunteer_women', 'label' => 'Volunteer Women', 'input_type' => 'number'],
                'pro-rep-volunteer-men' => ['property' => 'volunteer_men', 'label' => 'Volunteer Men', 'input_type' => 'number'],
                'pro-rep-volunteer-youth' => ['property' => 'volunteer_youth', 'label' => 'Volunteer Youth', 'input_type' => 'number'],
                'pro-rep-volunteer-smallholder' => ['property' => 'volunteer_smallholder_farmers', 'label' => 'Volunteer Smallholder', 'input_type' => 'number'],
                'pro-rep-volunteer-total' => ['property' => 'volunteer_total', 'label' => 'Volunteer Total', 'input_type' => 'number'],
                'pro-rep-shared-drive' => ['property' => 'shared_drive_link', 'label' => 'Shared Drive Link', 'input_type' => 'url'],
                'pro-rep-planted-trees' => ['property' => 'planted_trees', 'label' => 'Planted Trees', 'input_type' => 'number'],
                'pro-rep-new-jobs-desc' => ['property' => 'new_jobs_description', 'label' => 'New Jobs Description', 'input_type' => 'long-text'],
                'pro-rep-volunteer-desc' => ['property' => 'volunteers_work_description', 'label' => 'Volunteers Work Description', 'input_type' => 'long-text'],
                'pro-rep-ft-non-youth' => ['property' => 'ft_jobs_non_youth', 'label' => 'FT Jobs Non-Youth', 'input_type' => 'number'],
                'pro-rep-volunteer-non-youth' => ['property' => 'volunteer_non_youth', 'label' => 'Volunteer Non-Youth', 'input_type' => 'number'],
                'pro-rep-beneficiaries' => ['property' => 'beneficiaries', 'label' => 'Beneficiaries', 'input_type' => 'number'],
                'pro-rep-beneficiaries-desc' => ['property' => 'beneficiaries_description', 'label' => 'Beneficiaries Description', 'input_type' => 'long-text'],
                'pro-rep-beneficiaries-women' => ['property' => 'beneficiaries_women', 'label' => 'Beneficiaries Women', 'input_type' => 'number'],
                'pro-rep-beneficiaries-men' => ['property' => 'beneficiaries_men', 'label' => 'Beneficiaries Men', 'input_type' => 'number'],
                'pro-rep-beneficiaries-non-youth' => ['property' => 'beneficiaries_non_youth', 'label' => 'Beneficiaries Non-Youth', 'input_type' => 'number'],
                'pro-rep-beneficiaries-youth' => ['property' => 'beneficiaries_youth', 'label' => 'Beneficiaries Youth', 'input_type' => 'number'],
                'pro-rep-beneficiaries-smallholder' => ['property' => 'beneficiaries_smallholder', 'label' => 'Beneficiaries Smallholder', 'input_type' => 'number'],
                'pro-rep-beneficiaries-large-scl' => ['property' => 'beneficiaries_large_scale', 'label' => 'Beneficiaries Large Scale', 'input_type' => 'number'],
                'pro-rep-beneficiaries-income-inc' => ['property' => 'beneficiaries_income_increase', 'label' => 'Beneficiaries Income Increase', 'input_type' => 'number'],
                'pro-rep-beneficiaries-income-desc' => ['property' => 'beneficiaries_income_increase_description', 'label' => 'Beneficiaries Income Increase Description', 'input_type' => 'long-text'],
                'pro-rep-beneficiaries-skill-inc' => ['property' => 'beneficiaries_skills_knowledge_increase', 'label' => 'Beneficiaries Skills Knowledge Increased', 'input_type' => 'number'],
                'pro-rep-beneficiaries-skill-inc-desc' => ['property' => 'beneficiaries_skills_knowledge_increase_description', 'label' => 'Beneficiaries Skills Knowledge Description', 'input_type' => 'long-text'],
                'pro-rep-people_knowledge-skills-increased' => ['property' => 'people_knowledge_skills_increased', 'label' => 'People Knowledge Skills Increased', 'input_type' => 'number'],
                'pro-rep-community-progress' => ['property' => 'community_progress', 'label' => 'Community Engagement Progress', 'input_type' => 'long-text'],
                'pro-rep-equitable-opportunities' => ['property' => 'equitable_opportunities', 'label' => 'Equitable Opportunities for Women + Youth', 'input_type' => 'long-text'],
                'pro-rep-local-engagement' => ['property' => 'local_engagement', 'label' => 'Community Engagement Approach', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'local-engagement'],
                'pro-rep-site-addition' => ['property' => 'site_addition', 'label' => 'Site Addition', 'input_type' => 'boolean'],
                'pro-rep-paid-other-activity-description' => ['property' => 'paid_other_activity_description', 'label' => 'Paid Other Activities Description', 'input_type' => 'long-text'],
            ],
            'relations' => [
                'pro-rep-rel-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'tree-planted',
                ],
                // 'pro-rep-rel-paid-project-establishment' => [
                //     'property' => 'workdaysPaidProjectEstablishment',
                //     'label' => 'Paid Project Establishment',
                //     'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                //     'input_type' => 'workdays',
                //     'collection' => 'paid-project-establishment',
                //     'option_list_key' => 'workdays-ethnicity',
                // ],
                'pro-rep-rel-paid-nursery-operations' => [
                    'property' => 'workdaysPaidNurseryOperations',
                    'label' => 'Paid Nursery Operations',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-nursery-operations',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'pro-rep-rel-paid-project-management' => [
                    'property' => 'workdaysPaidProjectManagement',
                    'label' => 'Paid Project Management',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-project-management',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                // 'pro-rep-rel-paid-seed-collection' => [
                //     'property' => 'workdaysPaidSeedCollection',
                //     'label' => 'Paid Seed Collection',
                //     'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                //     'input_type' => 'workdays',
                //     'collection' => 'paid-seed-collection',
                //     'option_list_key' => 'workdays-ethnicity',
                // ],
                'pro-rep-rel-paid-other-activities' => [
                    'property' => 'workdaysPaidOtherActivitiesCollection',
                    'label' => 'Paid Other Activities',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-other-activities',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                // 'pro-rep-rel-volunteer-project-establishment' => [
                //     'property' => 'workdaysVolunteerProjectEstablishment',
                //     'label' => 'Volunteer Project Establishment',
                //     'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                //     'input_type' => 'workdays',
                //     'collection' => 'volunteer-project-establishment',
                //     'option_list_key' => 'workdays-ethnicity',
                // ],
                'pro-rep-rel-volunteer-nursery-operations' => [
                    'property' => 'workdaysVolunteerNurseryOperations',
                    'label' => 'Volunteer Nursery Operations',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-nursery-operations',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'pro-rep-rel-volunteer-project-management' => [
                    'property' => 'workdaysVolunteerProjectManagement',
                    'label' => 'Volunteer Project Management',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-project-management',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                // 'pro-rep-rel-volunteer-seed-collection' => [
                //     'property' => 'workdaysVolunteerSeedCollection',
                //     'label' => 'Volunteer Seed Collection',
                //     'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                //     'input_type' => 'workdays',
                //     'collection' => 'volunteer-seed-collection',
                //     'option_list_key' => 'workdays-ethnicity',
                // ],
                'pro-rep-rel-volunteer-other-activities' => [
                    'property' => 'workdaysVolunteerOtherActivities',
                    'label' => 'Volunteer Other Activities',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-other-activities',
                    'option_list_key' => 'workdays-ethnicity',
                ],
            ],
            'file-collections' => [
                'pro-rep-col-media' => ['property' =>  'media', 'label' => 'Media', 'input_type' => 'file', 'multichoice' => true],
                'pro-rep-col-socioeconomic-benefits' => ['property' =>  'socioeconomic_benefits', 'label' => 'Socioeconomic benefits', 'input_type' => 'file', 'multichoice' => true],
                'pro-rep-col-file' => ['property' =>  'file', 'label' => 'File', 'input_type' => 'file', 'multichoice' => true],
                'pro-rep-col-other-additional-documents' => ['property' =>  'other_additional_documents', 'label' => 'Other additional documents', 'input_type' => 'file', 'multichoice' => true],
                'pro-rep-col-photos' => ['property' =>  'photos', 'label' => 'Photos', 'input_type' => 'file', 'multichoice' => true],
            ],
        ],
        'site' => [
            'label' => 'Site',
            'model' => 'App\Models\V2\Sites\Site',
            'fields' => [
                'site-name' => ['property' => 'name', 'label' => 'Name', 'input_type' => 'text'],
                'site-control-site' => ['property' => 'control_site', 'label' => 'Control site', 'input_type' => 'boolean'],
                'site-boundary-geojson' => ['property' => 'boundary_geojson', 'label' => 'Boundary geojson', 'input_type' => 'mapInput'],
                'site-land-use-types' => ['property' => 'land_use_types', 'label' => 'Land use types', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-systems'],
                'site-restoration-strategy' => ['property' => 'restoration_strategy', 'label' => 'Restoration strategy', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'restoration-practices'],
                'site-description' => ['property' => 'description', 'label' => 'Description', 'input_type' => 'long-text'],
                'site-history' => ['property' => 'history', 'label' => 'History', 'input_type' => 'long-text'],
                'site-land-tenures' => ['property' => 'land_tenures', 'label' => 'Land tenures', 'input_type' => 'select-image', 'multichoice' => true, 'option_list_key' => 'land-tenures'],
                'site-landscape-community-contribution' => ['property' => 'landscape_community_contribution', 'label' => 'Landscape community contribution', 'input_type' => 'long-text'],
                'site-planting-pattern' => ['property' => 'planting_pattern', 'label' => 'Planting pattern', 'input_type' => 'long-text'],
                'site-soil-condition' => ['property' => 'soil_condition', 'label' => 'Soil condition', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'soil-condition'],
                'site-survival-rate-planted' => ['property' => 'survival_rate_planted', 'label' => 'Survival rate planted', 'input_type' => 'number'],
                'site-direct-seeding-survival-rate' => ['property' => 'direct_seeding_survival_rate', 'label' => 'Direct seeding survival rate', 'input_type' => 'number'],
                'site-a-nat-regeneration-trees-per-hectare' => ['property' => 'a_nat_regeneration_trees_per_hectare', 'label' => 'A natural regeneration trees per hectare', 'input_type' => 'number'],
                'site-a-nat-regeneration' => ['property' => 'a_nat_regeneration', 'label' => 'A natural regeneration', 'input_type' => 'number'],
                'site-hectares_to_restore-goal' => ['property' => 'hectares_to_restore_goal', 'label' => 'Hectares to restore_goal', 'input_type' => 'number'],
                'site-aim-year-five-crown-cover' => ['property' => 'aim_year_five_crown_cover', 'label' => 'Aim year five crown cover', 'input_type' => 'number'],
                'site-aim-number-of-mature-trees' => ['property' => 'aim_number_of_mature_trees', 'label' => 'Aim number of mature trees', 'input_type' => 'number'],
                'site-start-date' => ['property' => 'start_date', 'label' => 'Start date', 'input_type' => 'date'],
                'site-end-date' => ['property' => 'end_date', 'label' => 'End date', 'input_type' => 'date'],
            ],
            'file-collections' => [
                'site-col-media' => ['property' =>  'media', 'label' => 'Media', 'input_type' => 'file', 'multichoice' => true],
                'site-col-socioeconomic-benefits' => ['property' =>  'socioeconomic_benefits', 'label' => 'Socioeconomic benefits', 'input_type' => 'file', 'multichoice' => true],
                'site-col-file' => ['property' =>  'file', 'label' => 'File', 'input_type' => 'file', 'multichoice' => true],
                'site-col-other-additional-documents' => ['property' =>  'other_additional_documents', 'label' => 'Other additional documents', 'input_type' => 'file', 'multichoice' => true],
                'site-col-photos' => ['property' =>  'photos', 'label' => 'Photos', 'input_type' => 'file', 'multichoice' => true],
                'site-col-document-files' => ['property' =>  'document_files', 'label' => 'Document files', 'input_type' => 'file', 'multichoice' => true],
                'site-col-tree-species' => ['property' =>  'tree_species', 'label' => 'programme_submission', 'input_type' => 'file', 'multichoice' => true],
                'site-col-strat-for-heterogeneity' => ['property' => 'stratification_for_heterogeneity', 'label' => 'Stratification for heterogeneity', 'input_type' => 'file', 'multichoice' => false],
            ],
            'relations' => [
                'site-rel-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'tree-planted',
                ],
                'site-rel-non-tree-species' => [
                    'property' => 'nonTreeSpecies',
                    'label' => 'Non Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'non-tree',
                ],
                'site-rel-disturbances' => [
                    'property' => 'disturbances',
                    'label' => 'Disturbances',
                    'resource' => 'App\Http\Resources\V2\Disturbances\DisturbanceResource',
                    'input_type' => 'disturbances',
                    'collection' => 'disturbance'
                ],
                'site-rel-invasive' => [
                    'property' => 'invasives',
                    'label' => 'Invasives',
                    'resource' => 'App\Http\Resources\V2\Invasives\InvasiveResource',
                    'input_type' => 'invasive',
                    'collection' => 'invasive'
                ],
                'site-rel-seedings' => [
                    'property' => 'seedings',
                    'label' => 'Seedings',
                    'resource' => 'App\Http\Resources\V2\Seedings\SeedingResource',
                    'input_type' => 'seedings',
                ],
                'site-rel-stratas' => [
                    'property' => 'stratas',
                    'label' => 'Stratas',
                    'resource' => 'App\Http\Resources\V2\Stratas\StrataResource',
                    'input_type' => 'stratas',
                ],
            ],
        ],
        'site-report' => [
            'label' => 'Site Report',
            'model' => 'App\Models\V2\Sites\SiteReport',
            'fields' => [
                'site-rep-title' => ['property' => 'title', 'label' => 'Title', 'input_type' => 'text'],
                'site-rep-shared-drive-link' => ['property' => 'shared_drive_link', 'label' => 'Shared drive link', 'input_type' => 'url'],
                'site-rep-technical-narrative' => ['property' => 'technical_narrative', 'label' => 'Technical narrative', 'input_type' => 'long-text'],
                'site-rep-public-narrative' => ['property' => 'public_narrative', 'label' => 'Public narrative', 'input_type' => 'long-text'],
                'site-rep-disturbance-details' => ['property' => 'disturbance_details', 'label' => 'Additional Disturbance Details', 'input_type' => 'long-text'],
                'site-rep-workdays-paid' => ['property' => 'workdays_paid', 'label' => 'Workdays paid', 'input_type' => 'number'],
                'site-rep-seeds-planted' => ['property' => 'seeds_planted', 'label' => 'Seeds planted', 'input_type' => 'number'],
                'site-rep-workdays-volunteer' => ['property' => 'workdays_volunteer', 'label' => 'Workdays volunteer', 'input_type' => 'number'],
                'site-rep-polygon-status' => ['property' => 'polygon_status', 'label' => 'Polygon status', 'input_type' => 'long-text'],
                'site-rep-paid-other-activity-description' => ['property' => 'paid_other_activity_description', 'label' => 'Paid Other Activities Description', 'input_type' => 'long-text'],
            ],
            'file-collections' => [
                'site-rep-col-media' => ['property' =>  'media', 'label' => 'Media', 'input_type' => 'file', 'multichoice' => true],
                'site-rep-col-socioeconomic-benefits' => ['property' =>  'socioeconomic_benefits', 'label' => 'Socioeconomic benefits', 'input_type' => 'file', 'multichoice' => true],
                'site-rep-col-file' => ['property' =>  'file', 'label' => 'File', 'input_type' => 'file', 'multichoice' => true],
                'site-rep-col-other-additional-documents' => ['property' =>  'other_additional_documents', 'label' => 'Other additional documents', 'input_type' => 'file', 'multichoice' => true],
                'site-rep-col-photos' => ['property' =>  'photos', 'label' => 'Photos', 'input_type' => 'file', 'multichoice' => true],
                'site-rep-col-document-files' => ['property' =>  'document_files', 'label' => 'Photos', 'input_type' => 'file', 'multichoice' => true],
                'site-rep-col-tree-species' => ['property' =>  'tree_species', 'label' => 'programme_submission', 'input_type' => 'file', 'multichoice' => true],
                'site-rep-col-site-submission' => ['property' =>  'site_submission', 'label' => 'Site submission', 'input_type' => 'file', 'multichoice' => true],
            ],
            'relations' => [
                'site-rep-rel-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'tree-planted',
                ],
                'site-rep-rel-non-tree-species' => [
                    'property' => 'nonTreeSpecies',
                    'label' => 'Non Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'non-tree',
                ],
                'site-rep-rel-disturbances' => [
                    'property' => 'disturbances',
                    'label' => 'Disturbances',
                    'resource' => 'App\Http\Resources\V2\Disturbances\DisturbanceResource',
                    'input_type' => 'disturbances',
                    'collection' => 'disturbance'
                ],
                'site-rep-rel-seedings' => [
                    'property' => 'seedings',
                    'label' => 'Seedings',
                    'resource' => 'App\Http\Resources\V2\Seedings\SeedingResource',
                    'input_type' => 'seedings',
                ],
                'site-rep-rel-paid-site-establishment' => [
                    'property' => 'workdaysPaidSiteEstablishment',
                    'label' => 'Paid Site Establishment',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-site-establishment',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-paid-planting' => [
                    'property' => 'workdaysPaidPlanting',
                    'label' => 'Paid Planting',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-planting',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-paid-site-maintenance' => [
                    'property' => 'workdaysPaidSiteMaintenance',
                    'label' => 'Paid Site Maintenance',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-site-maintenance',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-paid-site-monitoring' => [
                    'property' => 'workdaysPaidSiteMonitoring',
                    'label' => 'Paid Site Monitoring',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-site-monitoring',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-paid-other-activities' => [
                    'property' => 'workdaysPaidOtherActivities',
                    'label' => 'Paid Other Activities',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'paid-other-activities',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-volunteer-site-establishment' => [
                    'property' => 'workdaysVolunteerSiteEstablishment',
                    'label' => 'Volunteer Site Establishment',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-site-establishment',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-volunteer-planting' => [
                    'property' => 'workdaysVolunteerPlanting',
                    'label' => 'Volunteer Planting',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-planting',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-volunteer-site-maintenance' => [
                    'property' => 'workdaysVolunteerSiteMaintenance',
                    'label' => 'volunteer Site Maintenance',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-site-maintenance',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-volunteer-site-monitoring' => [
                    'property' => 'workdaysVolunteerSiteMonitoring',
                    'label' => 'Volunteer Site Monitoring',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-site-monitoring',
                    'option_list_key' => 'workdays-ethnicity',
                ],
                'site-rep-rel-volunteer-other-activities' => [
                    'property' => 'workdaysVolunteerOtherActivities',
                    'label' => 'Volunteer Other Activities',
                    'resource' => 'App\Http\Resources\V2\Workdays\WorkdayResource',
                    'input_type' => 'workdays',
                    'collection' => 'volunteer-other-activities',
                    'option_list_key' => 'workdays-ethnicity',
                ],
            ],
        ],
        'nursery' => [
            'label' => 'Nursery',
            'model' => 'App\Models\V2\Nurseries\Nursery',
            'fields' => [
                'nur-name' => ['property' => 'name', 'label' => 'Name', 'input_type' => 'text'],
                'nur-type' => ['property' => 'type', 'label' => 'type', 'input_type' => 'select', 'multichoice' => false, 'option_list_key' => 'nursery-type'],
                'nur-start_date' => ['property' => 'start_date', 'label' => 'Start date', 'input_type' => 'date'],
                'nur-end_date' => ['property' => 'end_date', 'label' => 'End date', 'input_type' => 'date'],
                'nur-seedling_grown' => ['property' => 'seedling_grown', 'label' => 'Seedlings grown', 'input_type' => 'number'],
                'nur-planting_contribution' => ['property' => 'planting_contribution', 'label' => 'Planting contribution', 'input_type' => 'long-text'],
            ],
            'file-collections' => [
                'nur-col-file' => ['property' =>  'file', 'label' => 'File', 'input_type' => 'file', 'multichoice' => true],
                'nur-col-other-additional-documents' => ['property' =>  'other_additional_documents', 'label' => 'Other additional documents', 'input_type' => 'file', 'multichoice' => true],
                'nur-col-photos' => ['property' =>  'photos', 'label' => 'Photos', 'input_type' => 'file', 'multichoice' => true],
            ],
            'relations' => [
                'nur-rel-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'nursery-seedling',
                ],
            ],
        ],
        'nursery-report' => [
            'label' => 'Nursery Report',
            'model' => 'App\Models\V2\Nurseries\NurseryReport',
            'fields' => [
                'nur-rep-title' => ['property' => 'title', 'label' => 'Title', 'input_type' => 'text'],
                'nur-rep-seedlings-young-trees' => ['property' => 'seedlings_young_trees', 'label' => 'Seedlings young trees', 'input_type' => 'number'],
                'nur-rep-interesting-facts' => ['property' => 'interesting_facts', 'label' => 'Interesting facts', 'input_type' => 'long-text'],
                'nur-rep-site-prep' => ['property' => 'site_prep', 'label' => 'Site prep', 'input_type' => 'long-text'],
                'nur-rep-shared-drive-link' => ['property' => 'shared_drive_link', 'label' => 'Shared drive link', 'input_type' => 'url'],
            ],
            'file-collections' => [
                'nur-rep-col-file' => ['property' =>  'file', 'label' => 'File', 'input_type' => 'file', 'multichoice' => true],
                'nur-rep-col-other-additional-documents' => ['property' =>  'other_additional_documents', 'label' => 'Other additional documents', 'input_type' => 'file', 'multichoice' => true],
                'nur-rep-col-photos' => ['property' =>  'photos', 'label' => 'Photos', 'input_type' => 'file', 'multichoice' => true],
                'nur-rep-col-tree-seedling-contributions' => ['property' =>  'tree_seedling_contributions', 'label' => 'Tree seedling contributions', 'input_type' => 'file', 'multichoice' => true],
            ],
            'relations' => [
                'nur-rep-rel-tree-species' => [
                    'property' => 'treeSpecies',
                    'label' => 'Tree Species',
                    'resource' => 'App\Http\Resources\V2\TreeSpecies\TreeSpeciesResource',
                    'input_type' => 'treeSpecies',
                    'collection' => 'nursery-seedling',
                ],
            ],
        ],
    ],
];
