name: pull-request
on:
  pull_request:
jobs:
  lintTest:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install deps
        run: make composer
      - name: Bring up Docker
        run: make up
      - name: Lint & Test
        run: make test
      - name: Store logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: PHP Logs
          path: storage/logs/
          if-no-files-found: ignore
