name: pull-request
on:
  pull_request:
    branches: [main, staging, release/**]
jobs:
  lintTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: test
        run: make ls
      - name: test2
        run: whereis docker-compose
      - name: Install deps
        run: make composer
      - name: Bring up Docker
        run: make up
      - name: Lint & Test
        run: make test
      - name: Store logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: PHP Logs
          path: storage/logs/
          if-no-files-found: ignore
