name: pull-request
on:
  pull_request:
jobs:
  lintTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker
        uses: docker/bake-action@v6
        with:
          source: .
          push: false
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
          files: |
            docker-compose.yml
      - name: Install deps
        run: make composer
      - name: Bring up Docker
        run: make up
      - name: Lint & Test
        run: make test
      - name: Store logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: PHP Logs
          path: storage/logs/
          if-no-files-found: ignore
